<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <None Update="bootstrap.exe">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="bootstrapc.exe">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="chrome_elf.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="d3dcompiler_47.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="dxcompiler.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="dxil.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="libcef.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="libcef.lib">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="libEGL.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="libGLESv2.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="v8_context_snapshot.bin">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="vk_swiftshader.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="vk_swiftshader_icd.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="vulkan-1.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="icudtl.dat">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <!-- Resource pak files - flattened to output root alongside libcef.dll -->
      <None Remove="Resources\**\*.pak" />
      <Content Include="Resources\*.pak">
        <Link>%(Filename)%(Extension)</Link>
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <Content Include="Resources\locales\*.pak">
        <Link>locales\%(Filename)%(Extension)</Link>
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

</Project>
