using System.Collections.Generic;
using System.Text;
using CefRaw.BindingsParser.Models;
using WorldXaml.Generator.Common;

namespace CefRaw.SourceGen;

/// <summary>
/// Emits C# source text for managed wrapper classes from extracted CEF struct models.
/// </summary>
internal static class Emitter
{
    public static string GenerateNative(StructDefinition structDef)
    {
        var sb = new IndentedStringBuilder();

        // Header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace RawCef.Native;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Managed binding for the {structDef.Name} struct.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"{structDef.Access} unsafe partial struct {structDef.Name}");
        sb.AppendLine("{");
        using (sb.Indent())
        {
            foreach (var field in structDef.Fields)
            {
                sb.AppendLine("/// <summary>");
                sb.AppendLine($"/// Managed binding for the {field.Name} field.");
                sb.AppendLine("/// </summary>");
                sb.AppendLine("/// <remarks>");
                sb.AppendLine($"/// Native type: <code>{field.Type.Native}</code>");
                sb.AppendLine("/// </remarks>");
                sb.AppendLine($"{field.Access} {field.Type.CSharpType} {field.Name};");
            }
        }
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string GenerateWrapper(StructDefinition structDef)
    {
        var sb = new IndentedStringBuilder();

        var nativeName = structDef.Name;
        var managedName = TypeMapper.GetManagedName(structDef.Name);

        // Header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using RawCef.Native;");
        sb.AppendLine();
        sb.AppendLine("namespace RawCef;");
        sb.AppendLine();
        
        var baseClass = GetBaseType(structDef) switch
        {
            "_cef_base_ref_counted_t" => "CefBaseRefCounted",
            "_cef_base_scoped_t" => "CefBaseScoped",
            _ => null
        };

        // Interface declaration
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Represents an instance of the <code>{structDef.Name}</code> type.");
        sb.AppendLine("/// </summary>");
        sb.Append($"public unsafe partial interface I{managedName}");
        if (baseClass != null)
            sb.Append($" : I{baseClass}");
        sb.AppendLine();

        sb.AppendLine("{");
        
        using (sb.Indent())
        {
            sb.AppendLine($"public {nativeName}* NativePtr {{ get; }}");
        }

        sb.AppendLine("}");
        sb.AppendLine();

        if (baseClass == "CefBaseRefCounted")
        {
            // Class declaration
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// Represents a library-owned instance of the <code>{structDef.Name}</code> type.");
            sb.AppendLine("/// </summary>");
            sb.Append($"public unsafe partial class {managedName}Ref");
            if (baseClass != null)
                sb.Append($" : {baseClass}, I{managedName}");
            else
                sb.Append($" : I{managedName}");
            sb.AppendLine();

            sb.AppendLine("{");

            using (sb.Indent())
            {
                // Private pointer field
                sb.Append($"private readonly {nativeName}* _ptr;");
                sb.AppendLine();

                // Constructor
                sb.AppendLine();
                sb.Append($"public {managedName}({nativeName}* ptr)");
                if (baseClass != null)
                {
                    sb.Append(" : base(&ptr->@base)");
                }

                sb.AppendLine();
                sb.AppendLine("{");
                sb.AppendLine("    _ptr = ptr;");
                sb.AppendLine("    Initialize();");
                sb.AppendLine("}");
                sb.AppendLine();
                sb.AppendLine("partial void Initialize();");

                // Internal pointer accessor for other wrappers
                sb.AppendLine();
                sb.AppendLine($"public {nativeName}* NativePtr => _ptr;");

                // Methods for function-pointer fields
                foreach (var field in structDef.Fields.Where(field => field.Type.CSharpType.Contains("delegate*")))
                {
                    sb.AppendLine();
                    EmitMethod(sb, structDef, field);
                }

                // Properties for data fields (data-only structs)
                foreach (var field in structDef.Fields.Where(field => !field.Type.CSharpType.Contains("delegate*")))
                {
                    sb.AppendLine();
                    EmitDataProperty(sb, field);
                }
            }

            sb.AppendLine("}");

        }
        else
        {
            sb.Append($"public unsafe partial class {managedName}");
            if (baseClass != null)
                sb.Append($" : {baseClass}");
            sb.AppendLine();

            sb.AppendLine("{");
            
            using (sb.Indent())
            {
                // Private pointer field
                sb.Append($"private readonly {nativeName}* _ptr;");
                sb.AppendLine();

                // Constructor
                sb.AppendLine();
                sb.Append($"public {managedName}({nativeName}* ptr)");
                if (baseClass != null)
                {
                    sb.Append(" : base(&ptr->@base)");
                }

                sb.AppendLine();
                sb.AppendLine("{");
                sb.AppendLine("    _ptr = ptr;");
                sb.AppendLine("    Initialize();");
                sb.AppendLine("}");
                sb.AppendLine();
                sb.AppendLine("partial void Initialize();");

                // Internal pointer accessor for other wrappers
                sb.AppendLine();
                sb.AppendLine($"public {nativeName}* NativePtr => _ptr;");

                // Methods for function-pointer fields
                foreach (var field in structDef.Fields.Where(field => field.Type.CSharpType.Contains("delegate*")))
                {
                    sb.AppendLine();
                    EmitMethod(sb, structDef, field);
                }

                // Properties for data fields (data-only structs)
                foreach (var field in structDef.Fields.Where(field => !field.Type.CSharpType.Contains("delegate*")))
                {
                    sb.AppendLine();
                    EmitDataProperty(sb, field);
                }
            }

            sb.AppendLine("}");

        }

        return sb.ToString();

        static string? GetBaseType(StructDefinition structDefinition)
        {
            return structDefinition.Fields.FirstOrDefault(f => f.Name == "@base")?.Type.CSharpType;
        }
    }

    private static void EmitMethod(IndentedStringBuilder sb, StructDefinition model, FieldDefinition method)
    {
        if (method.Name == "dtor") return; // Intentionally not implemented. dtor is not an instance method.

        var (args, @return) = TypeMapper.GetTypeListFromDelegate(method.Type.CSharpType);

        var returnManaged = TypeMapper.MapNativeToManaged(@return, out var returnIsString, out var returnIsCefObject, out var returnCefObjectName);
        var argsManaged = args
            .Skip(1) // skip instance
            .Select((arg, idx) =>
            {
                var managed =
                    TypeMapper.MapNativeToManaged(arg, out var isString, out var isCefObject, out var cefObjectName);

                return (Native: arg, Managed: managed, IsString: isString, IsCefObject: isCefObject, CefObjectName: cefObjectName, Index: idx);
            })
            .ToArray();

        // Method signature
        sb.Append($"public {(returnIsCefObject ? returnCefObjectName : returnManaged)} {TypeMapper.SnakeToPascal(method.Name)}(");

        for (int i = 0; i < argsManaged.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append($"{argsManaged[i].Managed} arg{argsManaged[i].Index}");
        }
        sb.AppendLine(")");
        sb.AppendLine("{");

        using (sb.Indent())
        {
            // Collect string params for fixed blocks
            var stringParams = argsManaged.Where(p => p.IsString).ToArray();
            var hasStrings = stringParams.Length > 0;

            // Emit fixed blocks for each string param
            if (hasStrings)
            {
                foreach (var p in stringParams)
                {
                    sb.AppendLine($"fixed (char* _p{p.Index} = arg{p.Index})");
                }

                sb.AppendLine("{");
                sb.IncrementIndent();

                // Declare string struct locals inside fixed block
                foreach (var sp in stringParams)
                {
                    sb.AppendLine($"_cef_string_utf16_t _s{sp.Index};");
                    sb.AppendLine($"CefStringRef.FillFromPinned(&_s{sp.Index}, _p{sp.Index}, arg{sp.Index}?.Length ?? 0);");
                }
            }

            // Marshal parameters: build native arg list
            List<string> nativeArgs = ["_ptr"];

            foreach (var p in argsManaged)
            {
                if (p.IsString)
                {
                    nativeArgs.Add("&_s" + p.Index);
                }
                else if (p.IsCefObject)
                {
                    nativeArgs.Add($"arg{p.Index} is null ? null : arg{p.Index}.NativePtr");
                }
                else
                {
                    nativeArgs.Add($"arg{p.Index}");
                }
            }

            // Call native
            if (returnManaged == "void")
            {
                sb.AppendLine($"_ptr->{method.Name}({string.Join(", ", nativeArgs)});");
            }
            else
            {
                sb.AppendLine($"var _result = _ptr->{method.Name}({string.Join(", ", nativeArgs)});");
                sb.AppendLine();

                // Marshal return
                if (returnIsString)
                {
                    sb.AppendLine("return CefStringRef.ToStringAndFree(_result);");
                }
                else if (returnIsCefObject)
                {
                    sb.AppendLine($"return _result != null ? new {returnCefObjectName}(_result) : null;");
                }
                else
                {
                    sb.AppendLine("return _result;");
                }
            }

            // Close fixed blocks
            if (hasStrings)
            {
                sb.DecrementIndent();
                sb.AppendLine("}");
            }

        }

        sb.AppendLine("}");
    }

    private static void EmitDataProperty(IndentedStringBuilder sb, FieldDefinition field)
    {
        var propName = TypeMapper.SnakeToPascal(field.Name);

        if (TypeMapper.IsStringValueField(field.Type.CSharpType, field.Type.Native))
        {
            // _cef_string_utf16_t embedded by value → CefString wrapper
            // We need to be careful: the CefString holds a pointer to the embedded field
            sb.AppendLine($"public string? {propName}");
            sb.AppendLine("{");
            sb.AppendLine($"    get => new CefString(&_ptr->{field.Name}).Value;");
            sb.AppendLine($"    set => new CefString(&_ptr->{field.Name}).Value = value;");
            sb.AppendLine("}");
        }
        else if (TypeMapper.IsCefEnum(field.Type.CSharpType))
        {
            // Use raw native enum type (no Cef* wrapper)
            sb.AppendLine($"public {field.Type.CSharpType} {propName}");
            sb.AppendLine("{");
            sb.AppendLine($"    get => _ptr->{field.Name};");
            sb.AppendLine($"    set => _ptr->{field.Name} = value;");
            sb.AppendLine("}");
        }
        else
        {
            sb.AppendLine($"public {field.Type.CSharpType} {propName}");
            sb.AppendLine("{");
            sb.AppendLine($"    get => _ptr->{field.Name};");
            sb.AppendLine($"    set => _ptr->{field.Name} = value;");
            sb.AppendLine("}");
        }
    }

    public static string GenerateEnum(EnumerationDefinition enumeration)
    {
        var sb = new IndentedStringBuilder();

        // Header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace RawCef.Native;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Managed binding for the {enumeration.Name} enum.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"{enumeration.Access} enum {TypeMapper.GetManagedName(enumeration.Name)} : {enumeration.Type}");
        sb.AppendLine("{");
        using (sb.Indent())
        {
            foreach (var enumerator in enumeration.Enumerators)
            {
                var value = enumerator.Value;
                if (value?.Code is not null && !string.IsNullOrWhiteSpace(value.Code))
                {
                    if (value.IsUnchecked)
                        sb.AppendLine($"{enumerator.Name} = unchecked(({enumeration.Type})({value.Code})),");
                    else
                        sb.AppendLine($"{enumerator.Name} = {value.Code},");
                }
                else
                {
                    sb.AppendLine($"{enumerator.Name},");
                }
            }
        }
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static void GenerateNativeMethods(ClassDefinition cls, IndentedStringBuilder sb, string platform)
    {
        // Header
        sb.AppendLine($"#if OS_{platform.ToUpperInvariant()}");
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("using RawCef.Native;");
        sb.AppendLine();
        sb.AppendLine("namespace RawCef;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Entry points for the Chromium Embedded Framework.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public unsafe partial class CefUnsafe");
        sb.AppendLine("{");
        using (sb.Indent())
        {
            foreach (var constant in cls.Constants.DistinctBy(x => x.Name))
            {
                // XML doc comment
                sb.AppendLine("/// <summary>");
                sb.AppendLine($"/// {GetConstantSummary(constant)}");
                sb.AppendLine("/// </summary>");

                if (constant.Value?.IsDeref == true)
                {
                    sb.AppendLine($"{constant.Access} static readonly {constant.Type} {TypeMapper.CefFunctionToCSharp(constant.Name)} = &{TypeMapper.CefFunctionToCSharp(constant.Value.Code!)};");
                }
                else if (constant.IsPrimitive)
                {
                    // Primitive constant — can be emitted as a const
                    var val = constant.Value?.Code ?? "0";
                    sb.AppendLine($"{constant.Access} const {constant.Type} {constant.Name} = {val};");
                }
                else if (constant.Value?.Code is { } code)
                {
                    // Non-primitive value (e.g. ReadOnlySpan<byte>) — emit as static property
                    sb.AppendLine($"{constant.Access} static {constant.Type} {constant.Name} => {code};");
                }
                else
                {
                    // Fallback: static readonly field
                    sb.AppendLine($"{constant.Access} static readonly {constant.Type} {constant.Name};");
                }

                sb.AppendLine();
            }

            foreach (var function in cls.Functions.DistinctBy(x => x.Name))
            {
                // XML doc comment
                sb.AppendLine("/// <summary>");
                sb.AppendLine($"/// Native export: {function.Name} from {function.Lib ?? "libcef"}.");
                sb.AppendLine("/// </summary>");

                // DllImport attribute
                var lib = function.Lib ?? "libcef";
                var callingConvention = function.Convention switch
                {
                    "Cdecl" => "CallingConvention.Cdecl",
                    "StdCall" => "CallingConvention.StdCall",
                    "ThisCall" => "CallingConvention.ThisCall",
                    "FastCall" => "CallingConvention.FastCall",
                    _ => "CallingConvention.Cdecl"
                };
                sb.AppendLine($"[DllImport(\"{lib}\", EntryPoint = \"{function.Name}\", CallingConvention = {callingConvention})]");

                // Method signature
                var modifiers = "";
                if (function.Static) modifiers += "static ";
                if (function.Unsafe) modifiers += "unsafe ";
                modifiers += "extern ";

                var returnType = string.IsNullOrEmpty(function.ReturnType) ? "void" : function.ReturnType;
                var parameters = string.Join(", ", function.Parameters.Select(p => $"{p.Type} {p.Name}"));

                sb.AppendLine($"{function.Access} {modifiers}{returnType} {TypeMapper.CefFunctionToCSharp(function.Name)}({parameters});");
                sb.AppendLine();
            }
        }
        sb.AppendLine("}");
        sb.AppendLine("#endif");
    }

    private static string GetConstantSummary(ConstantDefinition constant)
    {
        if (constant.Value?.IsDeref == true && constant.Value.Code is { } code)
            return $"Native entry point for {code}.";
        if (constant.IsPrimitive)
            return $"Constant value for {constant.Name}.";
        return $"Value for {constant.Name}.";
    }
}
