namespace RawCef.Native;

public enum cef_component_state_t
{
    CEF_COMPONENT_STATE_NEW = 0,
    CEF_COMPONENT_STATE_CHECKING = 1,
    CEF_COMPONENT_STATE_CAN_UPDATE = 2,
    CEF_COMPONENT_STATE_DOWNLOADING = 3,
    CEF_COMPONENT_STATE_DECOMPRESSING = 4,
    CEF_COMPONENT_STATE_PATCHING = 5,
    CEF_COMPONENT_STATE_UPDATING = 6,
    CEF_COMPONENT_STATE_UPDATED = 7,
    CEF_COMPONENT_STATE_UP_TO_DATE = 8,
    CEF_COMPONENT_STATE_UPDATE_ERROR = 9,
    CEF_COMPONENT_STATE_RUN = 10,
}
