namespace RawCef.Native;

public enum cef_ssl_version_t
{
    SSL_CONNECTION_VERSION_UNKNOWN,
    SSL_CONNECTION_VERSION_SSL2,
    SSL_CONNECTION_VERSION_SSL3,
    SSL_CONNECTION_VERSION_TLS1,
    SSL_CONNECTION_VERSION_TLS1_1,
    SSL_CONNECTION_VERSION_TLS1_2,
    SSL_CONNECTION_VERSION_TLS1_3,
    SSL_CONNECTION_VERSION_QUIC,
    SSL_CONNECTION_VERSION_NUM_VALUES,
}
