namespace RawCef.Native;

public enum cef_task_type_t
{
    CEF_TASK_TYPE_UNKNOWN,
    CEF_TASK_TYPE_BROWSER,
    CEF_TASK_TYPE_GPU,
    CEF_TASK_TYPE_ZYGOTE,
    CEF_TASK_TYPE_UTILITY,
    CEF_TASK_TYPE_RENDERER,
    CEF_TASK_TYPE_EXTENSION,
    CEF_TASK_TYPE_GUEST,
    CEF_TASK_TYPE_PLUGIN_DEPRECATED,
    CEF_TASK_TYPE_SANDBOX_HELPER,
    CEF_TASK_TYPE_DEDICATED_WORKER,
    CEF_TASK_TYPE_SHARED_WORKER,
    CEF_TASK_TYPE_SERVICE_WORKER,
    CEF_TASK_TYPE_NUM_VALUES,
}
