namespace RawCef.Native;

public enum cef_scale_factor_t
{
    SCALE_FACTOR_NONE,
    SCALE_FACTOR_100P,
    SCALE_FACTOR_125P,
    SCALE_FACTOR_133P,
    SCALE_FACTOR_140P,
    SCALE_FACTOR_150P,
    SCALE_FACTOR_180P,
    SCALE_FACTOR_200P,
    SCALE_FACTOR_250P,
    SCALE_FACTOR_300P,
    SCALE_FACTOR_NUM_VALUES,
}
