namespace RawCef.Native;

public enum cef_dom_event_phase_t
{
    DOM_EVENT_PHASE_UNKNOWN,
    DOM_EVENT_PHASE_CAPTURING,
    DOM_EVENT_PHASE_AT_TARGET,
    DOM_EVENT_PHASE_BUBBLING,
    DOM_EVENT_PHASE_NUM_VALUES,
}
