namespace RawCef.Native;

public enum cef_axis_alignment_t
{
    CEF_AXIS_ALIGNMENT_START,
    CEF_AXIS_ALIGNMENT_CENTER,
    CEF_AXIS_ALIGNMENT_END,
    CEF_AXIS_ALIGNMENT_STRETCH,
    CEF_AXIS_ALIGNMENT_NUM_VALUES,
}
