namespace RawCef.Native;

public enum cef_component_update_error_t
{
    CEF_COMPONENT_UPDATE_ERROR_NONE = 0,
    CEF_COMPONENT_UPDATE_ERROR_UPDATE_IN_PROGRESS = 1,
    CEF_COMPONENT_UPDATE_ERROR_UPDATE_CANCELED = 2,
    CEF_COMPONENT_UPDATE_ERROR_RETRY_LATER = 3,
    CEF_COMPONENT_UPDATE_ERROR_SERVICE_ERROR = 4,
    CEF_COMPONENT_UPDATE_ERROR_UPDATE_CHECK_ERROR = 5,
    CEF_COMPONENT_UPDATE_ERROR_CRX_NOT_FOUND = 6,
    CEF_COMPONENT_UPDATE_ERROR_INVALID_ARGUMENT = 7,
    CEF_COMPONENT_UPDATE_ERROR_BAD_CRX_DATA_CALLBACK = 8,
}
