// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the _cef_frame_handler_t struct.
/// </summary>
public unsafe partial struct _cef_frame_handler_t
{
    /// <summary>
    /// Managed binding for the @base field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_base_ref_counted_t</code>
    /// </remarks>
    public _cef_base_ref_counted_t @base;
    /// <summary>
    /// Managed binding for the on_frame_created field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_frame_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_frame_handler_t*, _cef_browser_t*, _cef_frame_t*, void> on_frame_created;
    /// <summary>
    /// Managed binding for the on_frame_destroyed field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_frame_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_frame_handler_t*, _cef_browser_t*, _cef_frame_t*, void> on_frame_destroyed;
    /// <summary>
    /// Managed binding for the on_frame_attached field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_frame_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *, int) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_frame_handler_t*, _cef_browser_t*, _cef_frame_t*, int, void> on_frame_attached;
    /// <summary>
    /// Managed binding for the on_frame_detached field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_frame_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_frame_handler_t*, _cef_browser_t*, _cef_frame_t*, void> on_frame_detached;
    /// <summary>
    /// Managed binding for the on_main_frame_changed field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_frame_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *, struct _cef_frame_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_frame_handler_t*, _cef_browser_t*, _cef_frame_t*, _cef_frame_t*, void> on_main_frame_changed;
}
