// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the _cef_x509_cert_principal_t struct.
/// </summary>
public unsafe partial struct _cef_x509_cert_principal_t
{
    /// <summary>
    /// Managed binding for the @base field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_base_ref_counted_t</code>
    /// </remarks>
    public _cef_base_ref_counted_t @base;
    /// <summary>
    /// Managed binding for the get_display_name field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_userfree_t (*)(struct _cef_x509_cert_principal_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_x509_cert_principal_t*, _cef_string_utf16_t*> get_display_name;
    /// <summary>
    /// Managed binding for the get_common_name field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_userfree_t (*)(struct _cef_x509_cert_principal_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_x509_cert_principal_t*, _cef_string_utf16_t*> get_common_name;
    /// <summary>
    /// Managed binding for the get_locality_name field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_userfree_t (*)(struct _cef_x509_cert_principal_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_x509_cert_principal_t*, _cef_string_utf16_t*> get_locality_name;
    /// <summary>
    /// Managed binding for the get_state_or_province_name field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_userfree_t (*)(struct _cef_x509_cert_principal_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_x509_cert_principal_t*, _cef_string_utf16_t*> get_state_or_province_name;
    /// <summary>
    /// Managed binding for the get_country_name field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_userfree_t (*)(struct _cef_x509_cert_principal_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_x509_cert_principal_t*, _cef_string_utf16_t*> get_country_name;
    /// <summary>
    /// Managed binding for the get_organization_names field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_x509_cert_principal_t *, cef_string_list_t) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_x509_cert_principal_t*, _cef_string_list_t*, void> get_organization_names;
    /// <summary>
    /// Managed binding for the get_organization_unit_names field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_x509_cert_principal_t *, cef_string_list_t) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_x509_cert_principal_t*, _cef_string_list_t*, void> get_organization_unit_names;
}
