#if OS_WIN
// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the _cef_print_handler_t struct.
/// </summary>
public unsafe partial struct _cef_print_handler_t
{
    /// <summary>
    /// Managed binding for the @base field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_base_ref_counted_t</code>
    /// </remarks>
    public _cef_base_ref_counted_t @base;
    /// <summary>
    /// Managed binding for the on_print_start field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_print_handler_t *, struct _cef_browser_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_print_handler_t*, _cef_browser_t*, void> on_print_start;
    /// <summary>
    /// Managed binding for the on_print_settings field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_print_handler_t *, struct _cef_browser_t *, struct _cef_print_settings_t *, int) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_print_handler_t*, _cef_browser_t*, _cef_print_settings_t*, int, void> on_print_settings;
    /// <summary>
    /// Managed binding for the on_print_dialog field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_print_handler_t *, struct _cef_browser_t *, int, struct _cef_print_dialog_callback_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_print_handler_t*, _cef_browser_t*, int, _cef_print_dialog_callback_t*, int> on_print_dialog;
    /// <summary>
    /// Managed binding for the on_print_job field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_print_handler_t *, struct _cef_browser_t *, const cef_string_t *, const cef_string_t *, struct _cef_print_job_callback_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_print_handler_t*, _cef_browser_t*, _cef_string_utf16_t*, _cef_string_utf16_t*, _cef_print_job_callback_t*, int> on_print_job;
    /// <summary>
    /// Managed binding for the on_print_reset field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_print_handler_t *, struct _cef_browser_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_print_handler_t*, _cef_browser_t*, void> on_print_reset;
    /// <summary>
    /// Managed binding for the get_pdf_paper_size field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_size_t (*)(struct _cef_print_handler_t *, struct _cef_browser_t *, int) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_print_handler_t*, _cef_browser_t*, int, _cef_size_t> get_pdf_paper_size;
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the _cef_print_handler_t struct.
/// </summary>
public unsafe partial struct _cef_print_handler_t
{
    /// <summary>
    /// Managed binding for the @base field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_base_ref_counted_t</code>
    /// </remarks>
    public _cef_base_ref_counted_t @base;
    /// <summary>
    /// Managed binding for the on_print_start field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_print_handler_t *, struct _cef_browser_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_print_handler_t*, _cef_browser_t*, void> on_print_start;
    /// <summary>
    /// Managed binding for the on_print_settings field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_print_handler_t *, struct _cef_browser_t *, struct _cef_print_settings_t *, int)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_print_handler_t*, _cef_browser_t*, _cef_print_settings_t*, int, void> on_print_settings;
    /// <summary>
    /// Managed binding for the on_print_dialog field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_print_handler_t *, struct _cef_browser_t *, int, struct _cef_print_dialog_callback_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_print_handler_t*, _cef_browser_t*, int, _cef_print_dialog_callback_t*, int> on_print_dialog;
    /// <summary>
    /// Managed binding for the on_print_job field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_print_handler_t *, struct _cef_browser_t *, const cef_string_t *, const cef_string_t *, struct _cef_print_job_callback_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_print_handler_t*, _cef_browser_t*, _cef_string_utf16_t*, _cef_string_utf16_t*, _cef_print_job_callback_t*, int> on_print_job;
    /// <summary>
    /// Managed binding for the on_print_reset field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_print_handler_t *, struct _cef_browser_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_print_handler_t*, _cef_browser_t*, void> on_print_reset;
    /// <summary>
    /// Managed binding for the get_pdf_paper_size field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_size_t (*)(struct _cef_print_handler_t *, struct _cef_browser_t *, int)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_print_handler_t*, _cef_browser_t*, int, _cef_size_t> get_pdf_paper_size;
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the _cef_print_handler_t struct.
/// </summary>
public unsafe partial struct _cef_print_handler_t
{
    /// <summary>
    /// Managed binding for the @base field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_base_ref_counted_t</code>
    /// </remarks>
    public _cef_base_ref_counted_t @base;
    /// <summary>
    /// Managed binding for the on_print_start field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_print_handler_t *, struct _cef_browser_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_print_handler_t*, _cef_browser_t*, void> on_print_start;
    /// <summary>
    /// Managed binding for the on_print_settings field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_print_handler_t *, struct _cef_browser_t *, struct _cef_print_settings_t *, int)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_print_handler_t*, _cef_browser_t*, _cef_print_settings_t*, int, void> on_print_settings;
    /// <summary>
    /// Managed binding for the on_print_dialog field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_print_handler_t *, struct _cef_browser_t *, int, struct _cef_print_dialog_callback_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_print_handler_t*, _cef_browser_t*, int, _cef_print_dialog_callback_t*, int> on_print_dialog;
    /// <summary>
    /// Managed binding for the on_print_job field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_print_handler_t *, struct _cef_browser_t *, const cef_string_t *, const cef_string_t *, struct _cef_print_job_callback_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_print_handler_t*, _cef_browser_t*, _cef_string_utf16_t*, _cef_string_utf16_t*, _cef_print_job_callback_t*, int> on_print_job;
    /// <summary>
    /// Managed binding for the on_print_reset field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_print_handler_t *, struct _cef_browser_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_print_handler_t*, _cef_browser_t*, void> on_print_reset;
    /// <summary>
    /// Managed binding for the get_pdf_paper_size field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_size_t (*)(struct _cef_print_handler_t *, struct _cef_browser_t *, int)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_print_handler_t*, _cef_browser_t*, int, _cef_size_t> get_pdf_paper_size;
}
#endif