#if OS_WIN
// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the _cef_urlparts_t struct.
/// </summary>
public unsafe partial struct _cef_urlparts_t
{
    /// <summary>
    /// Managed binding for the size field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>size_t</code>
    /// </remarks>
    public nuint size;
    /// <summary>
    /// Managed binding for the spec field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t spec;
    /// <summary>
    /// Managed binding for the scheme field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t scheme;
    /// <summary>
    /// Managed binding for the username field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t username;
    /// <summary>
    /// Managed binding for the password field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t password;
    /// <summary>
    /// Managed binding for the host field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t host;
    /// <summary>
    /// Managed binding for the port field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t port;
    /// <summary>
    /// Managed binding for the origin field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t origin;
    /// <summary>
    /// Managed binding for the path field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t path;
    /// <summary>
    /// Managed binding for the query field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t query;
    /// <summary>
    /// Managed binding for the fragment field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t fragment;
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the _cef_urlparts_t struct.
/// </summary>
public unsafe partial struct _cef_urlparts_t
{
    /// <summary>
    /// Managed binding for the size field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>size_t</code>
    /// </remarks>
    public nuint size;
    /// <summary>
    /// Managed binding for the spec field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t spec;
    /// <summary>
    /// Managed binding for the scheme field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t scheme;
    /// <summary>
    /// Managed binding for the username field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t username;
    /// <summary>
    /// Managed binding for the password field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t password;
    /// <summary>
    /// Managed binding for the host field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t host;
    /// <summary>
    /// Managed binding for the port field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t port;
    /// <summary>
    /// Managed binding for the origin field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t origin;
    /// <summary>
    /// Managed binding for the path field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t path;
    /// <summary>
    /// Managed binding for the query field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t query;
    /// <summary>
    /// Managed binding for the fragment field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t fragment;
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the _cef_urlparts_t struct.
/// </summary>
public unsafe partial struct _cef_urlparts_t
{
    /// <summary>
    /// Managed binding for the size field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>size_t</code>
    /// </remarks>
    public nuint size;
    /// <summary>
    /// Managed binding for the spec field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t spec;
    /// <summary>
    /// Managed binding for the scheme field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t scheme;
    /// <summary>
    /// Managed binding for the username field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t username;
    /// <summary>
    /// Managed binding for the password field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t password;
    /// <summary>
    /// Managed binding for the host field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t host;
    /// <summary>
    /// Managed binding for the port field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t port;
    /// <summary>
    /// Managed binding for the origin field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t origin;
    /// <summary>
    /// Managed binding for the path field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t path;
    /// <summary>
    /// Managed binding for the query field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t query;
    /// <summary>
    /// Managed binding for the fragment field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_t</code>
    /// </remarks>
    public _cef_string_utf16_t fragment;
}
#endif