#if OS_WIN
// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the _cef_value_t struct.
/// </summary>
public unsafe partial struct _cef_value_t
{
    /// <summary>
    /// Managed binding for the @base field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_base_ref_counted_t</code>
    /// </remarks>
    public _cef_base_ref_counted_t @base;
    /// <summary>
    /// Managed binding for the is_valid field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_value_t*, int> is_valid;
    /// <summary>
    /// Managed binding for the is_owned field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_value_t*, int> is_owned;
    /// <summary>
    /// Managed binding for the is_read_only field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_value_t*, int> is_read_only;
    /// <summary>
    /// Managed binding for the is_same field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *, struct _cef_value_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_value_t*, _cef_value_t*, int> is_same;
    /// <summary>
    /// Managed binding for the is_equal field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *, struct _cef_value_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_value_t*, _cef_value_t*, int> is_equal;
    /// <summary>
    /// Managed binding for the copy field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>struct _cef_value_t *(*)(struct _cef_value_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_value_t*, _cef_value_t*> copy;
    /// <summary>
    /// Managed binding for the get_type field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_value_type_t (*)(struct _cef_value_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_value_t*, cef_value_type_t> get_type;
    /// <summary>
    /// Managed binding for the get_bool field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_value_t*, int> get_bool;
    /// <summary>
    /// Managed binding for the get_int field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_value_t*, int> get_int;
    /// <summary>
    /// Managed binding for the get_double field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>double (*)(struct _cef_value_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_value_t*, double> get_double;
    /// <summary>
    /// Managed binding for the get_string field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_userfree_t (*)(struct _cef_value_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_value_t*, cef_string_userfree_utf16_t> get_string;
    /// <summary>
    /// Managed binding for the get_binary field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>struct _cef_binary_value_t *(*)(struct _cef_value_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_value_t*, _cef_binary_value_t*> get_binary;
    /// <summary>
    /// Managed binding for the get_dictionary field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>struct _cef_dictionary_value_t *(*)(struct _cef_value_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_value_t*, _cef_dictionary_value_t*> get_dictionary;
    /// <summary>
    /// Managed binding for the get_list field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>struct _cef_list_value_t *(*)(struct _cef_value_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_value_t*, _cef_list_value_t*> get_list;
    /// <summary>
    /// Managed binding for the set_null field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_value_t*, int> set_null;
    /// <summary>
    /// Managed binding for the set_bool field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *, int) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_value_t*, int, int> set_bool;
    /// <summary>
    /// Managed binding for the set_int field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *, int) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_value_t*, int, int> set_int;
    /// <summary>
    /// Managed binding for the set_double field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *, double) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_value_t*, double, int> set_double;
    /// <summary>
    /// Managed binding for the set_string field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *, const cef_string_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_value_t*, _cef_string_utf16_t*, int> set_string;
    /// <summary>
    /// Managed binding for the set_binary field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *, struct _cef_binary_value_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_value_t*, _cef_binary_value_t*, int> set_binary;
    /// <summary>
    /// Managed binding for the set_dictionary field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *, struct _cef_dictionary_value_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_value_t*, _cef_dictionary_value_t*, int> set_dictionary;
    /// <summary>
    /// Managed binding for the set_list field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *, struct _cef_list_value_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_value_t*, _cef_list_value_t*, int> set_list;
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the _cef_value_t struct.
/// </summary>
public unsafe partial struct _cef_value_t
{
    /// <summary>
    /// Managed binding for the @base field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_base_ref_counted_t</code>
    /// </remarks>
    public _cef_base_ref_counted_t @base;
    /// <summary>
    /// Managed binding for the is_valid field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, int> is_valid;
    /// <summary>
    /// Managed binding for the is_owned field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, int> is_owned;
    /// <summary>
    /// Managed binding for the is_read_only field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, int> is_read_only;
    /// <summary>
    /// Managed binding for the is_same field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *, struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, _cef_value_t*, int> is_same;
    /// <summary>
    /// Managed binding for the is_equal field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *, struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, _cef_value_t*, int> is_equal;
    /// <summary>
    /// Managed binding for the copy field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>struct _cef_value_t *(*)(struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, _cef_value_t*> copy;
    /// <summary>
    /// Managed binding for the get_type field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_value_type_t (*)(struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, cef_value_type_t> get_type;
    /// <summary>
    /// Managed binding for the get_bool field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, int> get_bool;
    /// <summary>
    /// Managed binding for the get_int field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, int> get_int;
    /// <summary>
    /// Managed binding for the get_double field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>double (*)(struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, double> get_double;
    /// <summary>
    /// Managed binding for the get_string field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_userfree_t (*)(struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, cef_string_userfree_utf16_t> get_string;
    /// <summary>
    /// Managed binding for the get_binary field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>struct _cef_binary_value_t *(*)(struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, _cef_binary_value_t*> get_binary;
    /// <summary>
    /// Managed binding for the get_dictionary field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>struct _cef_dictionary_value_t *(*)(struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, _cef_dictionary_value_t*> get_dictionary;
    /// <summary>
    /// Managed binding for the get_list field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>struct _cef_list_value_t *(*)(struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, _cef_list_value_t*> get_list;
    /// <summary>
    /// Managed binding for the set_null field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, int> set_null;
    /// <summary>
    /// Managed binding for the set_bool field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *, int)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, int, int> set_bool;
    /// <summary>
    /// Managed binding for the set_int field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *, int)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, int, int> set_int;
    /// <summary>
    /// Managed binding for the set_double field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *, double)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, double, int> set_double;
    /// <summary>
    /// Managed binding for the set_string field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *, const cef_string_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, _cef_string_utf16_t*, int> set_string;
    /// <summary>
    /// Managed binding for the set_binary field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *, struct _cef_binary_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, _cef_binary_value_t*, int> set_binary;
    /// <summary>
    /// Managed binding for the set_dictionary field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *, struct _cef_dictionary_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, _cef_dictionary_value_t*, int> set_dictionary;
    /// <summary>
    /// Managed binding for the set_list field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *, struct _cef_list_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, _cef_list_value_t*, int> set_list;
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the _cef_value_t struct.
/// </summary>
public unsafe partial struct _cef_value_t
{
    /// <summary>
    /// Managed binding for the @base field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_base_ref_counted_t</code>
    /// </remarks>
    public _cef_base_ref_counted_t @base;
    /// <summary>
    /// Managed binding for the is_valid field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, int> is_valid;
    /// <summary>
    /// Managed binding for the is_owned field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, int> is_owned;
    /// <summary>
    /// Managed binding for the is_read_only field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, int> is_read_only;
    /// <summary>
    /// Managed binding for the is_same field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *, struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, _cef_value_t*, int> is_same;
    /// <summary>
    /// Managed binding for the is_equal field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *, struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, _cef_value_t*, int> is_equal;
    /// <summary>
    /// Managed binding for the copy field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>struct _cef_value_t *(*)(struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, _cef_value_t*> copy;
    /// <summary>
    /// Managed binding for the get_type field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_value_type_t (*)(struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, cef_value_type_t> get_type;
    /// <summary>
    /// Managed binding for the get_bool field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, int> get_bool;
    /// <summary>
    /// Managed binding for the get_int field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, int> get_int;
    /// <summary>
    /// Managed binding for the get_double field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>double (*)(struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, double> get_double;
    /// <summary>
    /// Managed binding for the get_string field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_string_userfree_t (*)(struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, cef_string_userfree_utf16_t> get_string;
    /// <summary>
    /// Managed binding for the get_binary field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>struct _cef_binary_value_t *(*)(struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, _cef_binary_value_t*> get_binary;
    /// <summary>
    /// Managed binding for the get_dictionary field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>struct _cef_dictionary_value_t *(*)(struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, _cef_dictionary_value_t*> get_dictionary;
    /// <summary>
    /// Managed binding for the get_list field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>struct _cef_list_value_t *(*)(struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, _cef_list_value_t*> get_list;
    /// <summary>
    /// Managed binding for the set_null field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, int> set_null;
    /// <summary>
    /// Managed binding for the set_bool field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *, int)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, int, int> set_bool;
    /// <summary>
    /// Managed binding for the set_int field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *, int)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, int, int> set_int;
    /// <summary>
    /// Managed binding for the set_double field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *, double)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, double, int> set_double;
    /// <summary>
    /// Managed binding for the set_string field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *, const cef_string_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, _cef_string_utf16_t*, int> set_string;
    /// <summary>
    /// Managed binding for the set_binary field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *, struct _cef_binary_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, _cef_binary_value_t*, int> set_binary;
    /// <summary>
    /// Managed binding for the set_dictionary field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *, struct _cef_dictionary_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, _cef_dictionary_value_t*, int> set_dictionary;
    /// <summary>
    /// Managed binding for the set_list field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_value_t *, struct _cef_list_value_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_value_t*, _cef_list_value_t*, int> set_list;
}
#endif