#if OS_WIN
// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the _cef_pdf_print_callback_t struct.
/// </summary>
public unsafe partial struct _cef_pdf_print_callback_t
{
    /// <summary>
    /// Managed binding for the @base field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_base_ref_counted_t</code>
    /// </remarks>
    public _cef_base_ref_counted_t @base;
    /// <summary>
    /// Managed binding for the on_pdf_print_finished field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_pdf_print_callback_t *, const cef_string_t *, int) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_pdf_print_callback_t*, _cef_string_utf16_t*, int, void> on_pdf_print_finished;
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the _cef_pdf_print_callback_t struct.
/// </summary>
public unsafe partial struct _cef_pdf_print_callback_t
{
    /// <summary>
    /// Managed binding for the @base field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_base_ref_counted_t</code>
    /// </remarks>
    public _cef_base_ref_counted_t @base;
    /// <summary>
    /// Managed binding for the on_pdf_print_finished field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_pdf_print_callback_t *, const cef_string_t *, int)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_pdf_print_callback_t*, _cef_string_utf16_t*, int, void> on_pdf_print_finished;
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the _cef_pdf_print_callback_t struct.
/// </summary>
public unsafe partial struct _cef_pdf_print_callback_t
{
    /// <summary>
    /// Managed binding for the @base field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_base_ref_counted_t</code>
    /// </remarks>
    public _cef_base_ref_counted_t @base;
    /// <summary>
    /// Managed binding for the on_pdf_print_finished field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_pdf_print_callback_t *, const cef_string_t *, int)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_pdf_print_callback_t*, _cef_string_utf16_t*, int, void> on_pdf_print_finished;
}
#endif