// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the _cef_read_handler_t struct.
/// </summary>
public unsafe partial struct _cef_read_handler_t
{
    /// <summary>
    /// Managed binding for the @base field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_base_ref_counted_t</code>
    /// </remarks>
    public _cef_base_ref_counted_t @base;
    /// <summary>
    /// Managed binding for the read field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>size_t (*)(struct _cef_read_handler_t *, void *, size_t, size_t) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_read_handler_t*, void*, nuint, nuint, nuint> read;
    /// <summary>
    /// Managed binding for the seek field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_read_handler_t *, int64_t, int) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_read_handler_t*, long, int, int> seek;
    /// <summary>
    /// Managed binding for the tell field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int64_t (*)(struct _cef_read_handler_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_read_handler_t*, long> tell;
    /// <summary>
    /// Managed binding for the eof field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_read_handler_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_read_handler_t*, int> eof;
    /// <summary>
    /// Managed binding for the may_block field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_read_handler_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_read_handler_t*, int> may_block;
}
