#if OS_WIN
// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the _cef_mouse_event_t struct.
/// </summary>
public unsafe partial struct _cef_mouse_event_t
{
    /// <summary>
    /// Managed binding for the x field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int x;
    /// <summary>
    /// Managed binding for the y field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int y;
    /// <summary>
    /// Managed binding for the modifiers field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>uint32_t</code>
    /// </remarks>
    public uint modifiers;
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the _cef_mouse_event_t struct.
/// </summary>
public unsafe partial struct _cef_mouse_event_t
{
    /// <summary>
    /// Managed binding for the x field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int x;
    /// <summary>
    /// Managed binding for the y field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int y;
    /// <summary>
    /// Managed binding for the modifiers field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>uint32_t</code>
    /// </remarks>
    public uint modifiers;
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the _cef_mouse_event_t struct.
/// </summary>
public unsafe partial struct _cef_mouse_event_t
{
    /// <summary>
    /// Managed binding for the x field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int x;
    /// <summary>
    /// Managed binding for the y field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int y;
    /// <summary>
    /// Managed binding for the modifiers field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>uint32_t</code>
    /// </remarks>
    public uint modifiers;
}
#endif