// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the _cef_resource_skip_callback_t struct.
/// </summary>
public unsafe partial struct _cef_resource_skip_callback_t
{
    /// <summary>
    /// Managed binding for the @base field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_base_ref_counted_t</code>
    /// </remarks>
    public _cef_base_ref_counted_t @base;
    /// <summary>
    /// Managed binding for the cont field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_resource_skip_callback_t *, int64_t) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_resource_skip_callback_t*, long, void> cont;
}
