// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the _cef_accelerated_paint_info_t struct.
/// </summary>
public unsafe partial struct _cef_accelerated_paint_info_t
{
    /// <summary>
    /// Managed binding for the size field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>size_t</code>
    /// </remarks>
    public nuint size;
    /// <summary>
    /// Managed binding for the shared_texture_handle field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_shared_texture_handle_t</code>
    /// </remarks>
    public void* shared_texture_handle;
    /// <summary>
    /// Managed binding for the format field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public cef_color_type_t format;
    /// <summary>
    /// Managed binding for the extra field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_accelerated_paint_info_common_t</code>
    /// </remarks>
    public _cef_accelerated_paint_info_common_t extra;
}
