// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the _cef_navigation_entry_visitor_t struct.
/// </summary>
public unsafe partial struct _cef_navigation_entry_visitor_t
{
    /// <summary>
    /// Managed binding for the @base field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_base_ref_counted_t</code>
    /// </remarks>
    public _cef_base_ref_counted_t @base;
    /// <summary>
    /// Managed binding for the visit field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_navigation_entry_visitor_t *, struct _cef_navigation_entry_t *, int, int, int) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_navigation_entry_visitor_t*, _cef_navigation_entry_t*, int, int, int, int> visit;
}
