#if OS_WIN
// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the _cef_popup_features_t struct.
/// </summary>
public unsafe partial struct _cef_popup_features_t
{
    /// <summary>
    /// Managed binding for the size field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>size_t</code>
    /// </remarks>
    public nuint size;
    /// <summary>
    /// Managed binding for the x field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int x;
    /// <summary>
    /// Managed binding for the xSet field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int xSet;
    /// <summary>
    /// Managed binding for the y field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int y;
    /// <summary>
    /// Managed binding for the ySet field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int ySet;
    /// <summary>
    /// Managed binding for the width field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int width;
    /// <summary>
    /// Managed binding for the widthSet field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int widthSet;
    /// <summary>
    /// Managed binding for the height field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int height;
    /// <summary>
    /// Managed binding for the heightSet field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int heightSet;
    /// <summary>
    /// Managed binding for the isPopup field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int isPopup;
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the _cef_popup_features_t struct.
/// </summary>
public unsafe partial struct _cef_popup_features_t
{
    /// <summary>
    /// Managed binding for the size field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>size_t</code>
    /// </remarks>
    public nuint size;
    /// <summary>
    /// Managed binding for the x field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int x;
    /// <summary>
    /// Managed binding for the xSet field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int xSet;
    /// <summary>
    /// Managed binding for the y field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int y;
    /// <summary>
    /// Managed binding for the ySet field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int ySet;
    /// <summary>
    /// Managed binding for the width field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int width;
    /// <summary>
    /// Managed binding for the widthSet field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int widthSet;
    /// <summary>
    /// Managed binding for the height field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int height;
    /// <summary>
    /// Managed binding for the heightSet field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int heightSet;
    /// <summary>
    /// Managed binding for the isPopup field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int isPopup;
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the _cef_popup_features_t struct.
/// </summary>
public unsafe partial struct _cef_popup_features_t
{
    /// <summary>
    /// Managed binding for the size field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>size_t</code>
    /// </remarks>
    public nuint size;
    /// <summary>
    /// Managed binding for the x field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int x;
    /// <summary>
    /// Managed binding for the xSet field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int xSet;
    /// <summary>
    /// Managed binding for the y field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int y;
    /// <summary>
    /// Managed binding for the ySet field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int ySet;
    /// <summary>
    /// Managed binding for the width field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int width;
    /// <summary>
    /// Managed binding for the widthSet field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int widthSet;
    /// <summary>
    /// Managed binding for the height field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int height;
    /// <summary>
    /// Managed binding for the heightSet field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int heightSet;
    /// <summary>
    /// Managed binding for the isPopup field.
    /// </summary>
    /// <remarks>
    /// Native type: <code></code>
    /// </remarks>
    public int isPopup;
}
#endif