// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the _cef_audio_handler_t struct.
/// </summary>
public unsafe partial struct _cef_audio_handler_t
{
    /// <summary>
    /// Managed binding for the @base field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_base_ref_counted_t</code>
    /// </remarks>
    public _cef_base_ref_counted_t @base;
    /// <summary>
    /// Managed binding for the get_audio_parameters field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_audio_handler_t *, struct _cef_browser_t *, cef_audio_parameters_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_audio_handler_t*, _cef_browser_t*, _cef_audio_parameters_t*, int> get_audio_parameters;
    /// <summary>
    /// Managed binding for the on_audio_stream_started field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_audio_handler_t *, struct _cef_browser_t *, const cef_audio_parameters_t *, int) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_audio_handler_t*, _cef_browser_t*, _cef_audio_parameters_t*, int, void> on_audio_stream_started;
    /// <summary>
    /// Managed binding for the on_audio_stream_packet field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_audio_handler_t *, struct _cef_browser_t *, const float **, int, int64_t) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_audio_handler_t*, _cef_browser_t*, float**, int, long, void> on_audio_stream_packet;
    /// <summary>
    /// Managed binding for the on_audio_stream_stopped field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_audio_handler_t *, struct _cef_browser_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_audio_handler_t*, _cef_browser_t*, void> on_audio_stream_stopped;
    /// <summary>
    /// Managed binding for the on_audio_stream_error field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_audio_handler_t *, struct _cef_browser_t *, const cef_string_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_audio_handler_t*, _cef_browser_t*, _cef_string_utf16_t*, void> on_audio_stream_error;
}
