#if OS_WIN
// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the _cef_context_menu_handler_t struct.
/// </summary>
public unsafe partial struct _cef_context_menu_handler_t
{
    /// <summary>
    /// Managed binding for the @base field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_base_ref_counted_t</code>
    /// </remarks>
    public _cef_base_ref_counted_t @base;
    /// <summary>
    /// Managed binding for the on_before_context_menu field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_context_menu_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *, struct _cef_context_menu_params_t *, struct _cef_menu_model_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_context_menu_handler_t*, _cef_browser_t*, _cef_frame_t*, _cef_context_menu_params_t*, _cef_menu_model_t*, void> on_before_context_menu;
    /// <summary>
    /// Managed binding for the run_context_menu field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_context_menu_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *, struct _cef_context_menu_params_t *, struct _cef_menu_model_t *, struct _cef_run_context_menu_callback_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_context_menu_handler_t*, _cef_browser_t*, _cef_frame_t*, _cef_context_menu_params_t*, _cef_menu_model_t*, _cef_run_context_menu_callback_t*, int> run_context_menu;
    /// <summary>
    /// Managed binding for the on_context_menu_command field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_context_menu_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *, struct _cef_context_menu_params_t *, int, cef_event_flags_t) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_context_menu_handler_t*, _cef_browser_t*, _cef_frame_t*, _cef_context_menu_params_t*, int, cef_event_flags_t, int> on_context_menu_command;
    /// <summary>
    /// Managed binding for the on_context_menu_dismissed field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_context_menu_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_context_menu_handler_t*, _cef_browser_t*, _cef_frame_t*, void> on_context_menu_dismissed;
    /// <summary>
    /// Managed binding for the run_quick_menu field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_context_menu_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *, const cef_point_t *, const cef_size_t *, cef_quick_menu_edit_state_flags_t, struct _cef_run_quick_menu_callback_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_context_menu_handler_t*, _cef_browser_t*, _cef_frame_t*, _cef_point_t*, _cef_size_t*, cef_quick_menu_edit_state_flags_t, _cef_run_quick_menu_callback_t*, int> run_quick_menu;
    /// <summary>
    /// Managed binding for the on_quick_menu_command field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_context_menu_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *, int, cef_event_flags_t) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_context_menu_handler_t*, _cef_browser_t*, _cef_frame_t*, int, cef_event_flags_t, int> on_quick_menu_command;
    /// <summary>
    /// Managed binding for the on_quick_menu_dismissed field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_context_menu_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *) __attribute__((stdcall))</code>
    /// </remarks>
    public delegate* unmanaged[Stdcall]<_cef_context_menu_handler_t*, _cef_browser_t*, _cef_frame_t*, void> on_quick_menu_dismissed;
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the _cef_context_menu_handler_t struct.
/// </summary>
public unsafe partial struct _cef_context_menu_handler_t
{
    /// <summary>
    /// Managed binding for the @base field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_base_ref_counted_t</code>
    /// </remarks>
    public _cef_base_ref_counted_t @base;
    /// <summary>
    /// Managed binding for the on_before_context_menu field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_context_menu_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *, struct _cef_context_menu_params_t *, struct _cef_menu_model_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_context_menu_handler_t*, _cef_browser_t*, _cef_frame_t*, _cef_context_menu_params_t*, _cef_menu_model_t*, void> on_before_context_menu;
    /// <summary>
    /// Managed binding for the run_context_menu field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_context_menu_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *, struct _cef_context_menu_params_t *, struct _cef_menu_model_t *, struct _cef_run_context_menu_callback_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_context_menu_handler_t*, _cef_browser_t*, _cef_frame_t*, _cef_context_menu_params_t*, _cef_menu_model_t*, _cef_run_context_menu_callback_t*, int> run_context_menu;
    /// <summary>
    /// Managed binding for the on_context_menu_command field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_context_menu_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *, struct _cef_context_menu_params_t *, int, cef_event_flags_t)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_context_menu_handler_t*, _cef_browser_t*, _cef_frame_t*, _cef_context_menu_params_t*, int, cef_event_flags_t, int> on_context_menu_command;
    /// <summary>
    /// Managed binding for the on_context_menu_dismissed field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_context_menu_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_context_menu_handler_t*, _cef_browser_t*, _cef_frame_t*, void> on_context_menu_dismissed;
    /// <summary>
    /// Managed binding for the run_quick_menu field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_context_menu_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *, const cef_point_t *, const cef_size_t *, cef_quick_menu_edit_state_flags_t, struct _cef_run_quick_menu_callback_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_context_menu_handler_t*, _cef_browser_t*, _cef_frame_t*, _cef_point_t*, _cef_size_t*, cef_quick_menu_edit_state_flags_t, _cef_run_quick_menu_callback_t*, int> run_quick_menu;
    /// <summary>
    /// Managed binding for the on_quick_menu_command field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_context_menu_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *, int, cef_event_flags_t)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_context_menu_handler_t*, _cef_browser_t*, _cef_frame_t*, int, cef_event_flags_t, int> on_quick_menu_command;
    /// <summary>
    /// Managed binding for the on_quick_menu_dismissed field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_context_menu_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_context_menu_handler_t*, _cef_browser_t*, _cef_frame_t*, void> on_quick_menu_dismissed;
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the _cef_context_menu_handler_t struct.
/// </summary>
public unsafe partial struct _cef_context_menu_handler_t
{
    /// <summary>
    /// Managed binding for the @base field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>cef_base_ref_counted_t</code>
    /// </remarks>
    public _cef_base_ref_counted_t @base;
    /// <summary>
    /// Managed binding for the on_before_context_menu field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_context_menu_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *, struct _cef_context_menu_params_t *, struct _cef_menu_model_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_context_menu_handler_t*, _cef_browser_t*, _cef_frame_t*, _cef_context_menu_params_t*, _cef_menu_model_t*, void> on_before_context_menu;
    /// <summary>
    /// Managed binding for the run_context_menu field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_context_menu_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *, struct _cef_context_menu_params_t *, struct _cef_menu_model_t *, struct _cef_run_context_menu_callback_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_context_menu_handler_t*, _cef_browser_t*, _cef_frame_t*, _cef_context_menu_params_t*, _cef_menu_model_t*, _cef_run_context_menu_callback_t*, int> run_context_menu;
    /// <summary>
    /// Managed binding for the on_context_menu_command field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_context_menu_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *, struct _cef_context_menu_params_t *, int, cef_event_flags_t)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_context_menu_handler_t*, _cef_browser_t*, _cef_frame_t*, _cef_context_menu_params_t*, int, cef_event_flags_t, int> on_context_menu_command;
    /// <summary>
    /// Managed binding for the on_context_menu_dismissed field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_context_menu_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_context_menu_handler_t*, _cef_browser_t*, _cef_frame_t*, void> on_context_menu_dismissed;
    /// <summary>
    /// Managed binding for the run_quick_menu field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_context_menu_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *, const cef_point_t *, const cef_size_t *, cef_quick_menu_edit_state_flags_t, struct _cef_run_quick_menu_callback_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_context_menu_handler_t*, _cef_browser_t*, _cef_frame_t*, _cef_point_t*, _cef_size_t*, cef_quick_menu_edit_state_flags_t, _cef_run_quick_menu_callback_t*, int> run_quick_menu;
    /// <summary>
    /// Managed binding for the on_quick_menu_command field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>int (*)(struct _cef_context_menu_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *, int, cef_event_flags_t)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_context_menu_handler_t*, _cef_browser_t*, _cef_frame_t*, int, cef_event_flags_t, int> on_quick_menu_command;
    /// <summary>
    /// Managed binding for the on_quick_menu_dismissed field.
    /// </summary>
    /// <remarks>
    /// Native type: <code>void (*)(struct _cef_context_menu_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *)</code>
    /// </remarks>
    public delegate* unmanaged[Cdecl]<_cef_context_menu_handler_t*, _cef_browser_t*, _cef_frame_t*, void> on_quick_menu_dismissed;
}
#endif