// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Wraps a library-owned instance of <c>_cef_accessibility_handler_t</c>.
/// Calls <c>add_ref</c> on construction and <c>release</c> on dispose
/// (for ref-counted types) or <c>del</c> on dispose (for scoped types).
/// </summary>
public unsafe partial class CefAccessibilityHandlerRef : CefBaseRefCountedRef, ICefAccessibilityHandler
{
    private readonly _cef_accessibility_handler_t* _ptr;

    public CefAccessibilityHandlerRef(_cef_accessibility_handler_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    _cef_accessibility_handler_t* ICefAccessibilityHandler.NativePtr => _ptr;


    public void OnAccessibilityTreeChange(ICefValue? arg0)
    {
        _ptr->on_accessibility_tree_change(_ptr, arg0 is null ? null : arg0.NativePtr);
    }

    public void OnAccessibilityLocationChange(ICefValue? arg0)
    {
        _ptr->on_accessibility_location_change(_ptr, arg0 is null ? null : arg0.NativePtr);
    }

    public _cef_base_ref_counted_t @base
    {
        get => _ptr->@base;
        set => _ptr->@base = value;
    }
}
