// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Wraps a library-owned instance of <c>_cef_box_layout_settings_t</c>.
/// </summary>
public unsafe partial class CefBoxLayoutSettingsRef : ICefBoxLayoutSettings
{
    private readonly _cef_box_layout_settings_t* _ptr;

    public CefBoxLayoutSettingsRef(_cef_box_layout_settings_t* ptr)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    _cef_box_layout_settings_t* ICefBoxLayoutSettings.NativePtr => _ptr;


    public nuint Size
    {
        get => _ptr->size;
        set => _ptr->size = value;
    }

    public int Horizontal
    {
        get => _ptr->horizontal;
        set => _ptr->horizontal = value;
    }

    public int InsideBorderHorizontalSpacing
    {
        get => _ptr->inside_border_horizontal_spacing;
        set => _ptr->inside_border_horizontal_spacing = value;
    }

    public int InsideBorderVerticalSpacing
    {
        get => _ptr->inside_border_vertical_spacing;
        set => _ptr->inside_border_vertical_spacing = value;
    }

    public _cef_insets_t InsideBorderInsets
    {
        get => _ptr->inside_border_insets;
        set => _ptr->inside_border_insets = value;
    }

    public int BetweenChildSpacing
    {
        get => _ptr->between_child_spacing;
        set => _ptr->between_child_spacing = value;
    }

    public cef_axis_alignment_t MainAxisAlignment
    {
        get => _ptr->main_axis_alignment;
        set => _ptr->main_axis_alignment = value;
    }

    public cef_axis_alignment_t CrossAxisAlignment
    {
        get => _ptr->cross_axis_alignment;
        set => _ptr->cross_axis_alignment = value;
    }

    public int MinimumCrossAxisSize
    {
        get => _ptr->minimum_cross_axis_size;
        set => _ptr->minimum_cross_axis_size = value;
    }

    public int DefaultFlex
    {
        get => _ptr->default_flex;
        set => _ptr->default_flex = value;
    }
}
