// <auto-generated/>
#nullable enable

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using RawCef.Native;

namespace RawCef;

/// <summary>
/// Abstract base class for client-side implementations of <c>_cef_before_download_callback_t</c>.
/// Subclass this to implement a custom CefBeforeDownloadCallback.
/// </summary>
public unsafe abstract partial class CefBeforeDownloadCallback : CefBaseRefCounted, ICefBeforeDownloadCallback
{
    private _cef_before_download_callback_t* _typedPtr;

    protected CefBeforeDownloadCallback() : this((nuint)sizeof(_cef_before_download_callback_t))
    {
    }

    protected CefBeforeDownloadCallback(nuint structSize) : base(structSize)
    {
        _typedPtr = (_cef_before_download_callback_t*)NativePtr;
        InitializeNativeStruct();
    }

    _cef_before_download_callback_t* ICefBeforeDownloadCallback.NativePtr => _typedPtr;

    /// <inheritdoc />
    protected override void InitializeNativeStruct()
    {
        base.InitializeNativeStruct();

        _typedPtr->cont = &Bridge_Cont;
    }


    /// <summary>
    /// Implement the <c>cont</c> callback.
    /// </summary>
    public abstract void Cont(string? arg0, int arg1);

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_Cont(_cef_before_download_callback_t* self, _cef_string_utf16_t* arg0, int arg1)
    {
        var _m = GetManaged<CefBeforeDownloadCallback>(self);

        var _a0 = CefStringRef.ToStringAndFree(arg0);
        var _a1 = arg1;
        _m.Cont(_a0, _a1);
    }
}
