// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

public unsafe partial class CefClient : CefBaseRefCounted
{
    private readonly _cef_client_t* _ptr;

    public CefClient(_cef_client_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    internal _cef_client_t* NativePtr => _ptr;

    public CefAudioHandler GetAudioHandler()
    {
        var _result = _ptr->get_audio_handler(_ptr);

        return _result != null ? new CefAudioHandler(_result) : null;
    }

    public CefCommandHandler GetCommandHandler()
    {
        var _result = _ptr->get_command_handler(_ptr);

        return _result != null ? new CefCommandHandler(_result) : null;
    }

    public CefContextMenuHandler GetContextMenuHandler()
    {
        var _result = _ptr->get_context_menu_handler(_ptr);

        return _result != null ? new CefContextMenuHandler(_result) : null;
    }

    public CefDialogHandler GetDialogHandler()
    {
        var _result = _ptr->get_dialog_handler(_ptr);

        return _result != null ? new CefDialogHandler(_result) : null;
    }

    public CefDisplayHandler GetDisplayHandler()
    {
        var _result = _ptr->get_display_handler(_ptr);

        return _result != null ? new CefDisplayHandler(_result) : null;
    }

    public CefDownloadHandler GetDownloadHandler()
    {
        var _result = _ptr->get_download_handler(_ptr);

        return _result != null ? new CefDownloadHandler(_result) : null;
    }

    public CefDragHandler GetDragHandler()
    {
        var _result = _ptr->get_drag_handler(_ptr);

        return _result != null ? new CefDragHandler(_result) : null;
    }

    public CefFindHandler GetFindHandler()
    {
        var _result = _ptr->get_find_handler(_ptr);

        return _result != null ? new CefFindHandler(_result) : null;
    }

    public CefFocusHandler GetFocusHandler()
    {
        var _result = _ptr->get_focus_handler(_ptr);

        return _result != null ? new CefFocusHandler(_result) : null;
    }

    public CefFrameHandler GetFrameHandler()
    {
        var _result = _ptr->get_frame_handler(_ptr);

        return _result != null ? new CefFrameHandler(_result) : null;
    }

    public CefPermissionHandler GetPermissionHandler()
    {
        var _result = _ptr->get_permission_handler(_ptr);

        return _result != null ? new CefPermissionHandler(_result) : null;
    }

    public CefJsdialogHandler GetJsdialogHandler()
    {
        var _result = _ptr->get_jsdialog_handler(_ptr);

        return _result != null ? new CefJsdialogHandler(_result) : null;
    }

    public CefKeyboardHandler GetKeyboardHandler()
    {
        var _result = _ptr->get_keyboard_handler(_ptr);

        return _result != null ? new CefKeyboardHandler(_result) : null;
    }

    public CefLifeSpanHandler GetLifeSpanHandler()
    {
        var _result = _ptr->get_life_span_handler(_ptr);

        return _result != null ? new CefLifeSpanHandler(_result) : null;
    }

    public CefLoadHandler GetLoadHandler()
    {
        var _result = _ptr->get_load_handler(_ptr);

        return _result != null ? new CefLoadHandler(_result) : null;
    }

    public CefPrintHandler GetPrintHandler()
    {
        var _result = _ptr->get_print_handler(_ptr);

        return _result != null ? new CefPrintHandler(_result) : null;
    }

    public CefRenderHandler GetRenderHandler()
    {
        var _result = _ptr->get_render_handler(_ptr);

        return _result != null ? new CefRenderHandler(_result) : null;
    }

    public CefRequestHandler GetRequestHandler()
    {
        var _result = _ptr->get_request_handler(_ptr);

        return _result != null ? new CefRequestHandler(_result) : null;
    }

    public int OnProcessMessageReceived(CefBrowser? arg0, CefFrame? arg1, cef_process_id_t arg2, CefProcessMessage? arg3)
    {
        var _result = _ptr->on_process_message_received(_ptr, arg0 is null ? null : arg0.NativePtr, arg1 is null ? null : arg1.NativePtr, arg2, arg3 is null ? null : arg3.NativePtr);

        return _result;
    }

        public _cef_base_ref_counted_t @base
        {
            get => _ptr->@base;
            set => _ptr->@base = value;
        }
}
