// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Wraps a library-owned instance of <c>_cef_completion_callback_t</c>.
/// Calls <c>add_ref</c> on construction and <c>release</c> on dispose
/// (for ref-counted types) or <c>del</c> on dispose (for scoped types).
/// </summary>
public unsafe partial class CefCompletionCallbackRef : CefBaseRefCountedRef, ICefCompletionCallback
{
    private readonly _cef_completion_callback_t* _ptr;

    public CefCompletionCallbackRef(_cef_completion_callback_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    _cef_completion_callback_t* ICefCompletionCallback.NativePtr => _ptr;


    public void OnComplete()
    {
        _ptr->on_complete(_ptr);
    }

    public _cef_base_ref_counted_t @base
    {
        get => _ptr->@base;
        set => _ptr->@base = value;
    }
}
