// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

public unsafe partial class CefContextMenuParams : CefBaseRefCounted
{
    private readonly _cef_context_menu_params_t* _ptr;

    public CefContextMenuParams(_cef_context_menu_params_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    internal _cef_context_menu_params_t* NativePtr => _ptr;

    public int GetXcoord()
    {
        var _result = _ptr->get_xcoord(_ptr);

        return _result;
    }

    public int GetYcoord()
    {
        var _result = _ptr->get_ycoord(_ptr);

        return _result;
    }

    public cef_context_menu_type_flags_t GetTypeFlags()
    {
        var _result = _ptr->get_type_flags(_ptr);

        return _result;
    }

    public string? GetLinkUrl()
    {
        var _result = _ptr->get_link_url(_ptr);

        return CefStringRef.ToStringAndFree(_result);
    }

    public string? GetUnfilteredLinkUrl()
    {
        var _result = _ptr->get_unfiltered_link_url(_ptr);

        return CefStringRef.ToStringAndFree(_result);
    }

    public string? GetSourceUrl()
    {
        var _result = _ptr->get_source_url(_ptr);

        return CefStringRef.ToStringAndFree(_result);
    }

    public int HasImageContents()
    {
        var _result = _ptr->has_image_contents(_ptr);

        return _result;
    }

    public string? GetTitleText()
    {
        var _result = _ptr->get_title_text(_ptr);

        return CefStringRef.ToStringAndFree(_result);
    }

    public string? GetPageUrl()
    {
        var _result = _ptr->get_page_url(_ptr);

        return CefStringRef.ToStringAndFree(_result);
    }

    public string? GetFrameUrl()
    {
        var _result = _ptr->get_frame_url(_ptr);

        return CefStringRef.ToStringAndFree(_result);
    }

    public string? GetFrameCharset()
    {
        var _result = _ptr->get_frame_charset(_ptr);

        return CefStringRef.ToStringAndFree(_result);
    }

    public cef_context_menu_media_type_t GetMediaType()
    {
        var _result = _ptr->get_media_type(_ptr);

        return _result;
    }

    public cef_context_menu_media_state_flags_t GetMediaStateFlags()
    {
        var _result = _ptr->get_media_state_flags(_ptr);

        return _result;
    }

    public string? GetSelectionText()
    {
        var _result = _ptr->get_selection_text(_ptr);

        return CefStringRef.ToStringAndFree(_result);
    }

    public string? GetMisspelledWord()
    {
        var _result = _ptr->get_misspelled_word(_ptr);

        return CefStringRef.ToStringAndFree(_result);
    }

    public int GetDictionarySuggestions(_cef_string_list_t* arg0)
    {
        var _result = _ptr->get_dictionary_suggestions(_ptr, arg0);

        return _result;
    }

    public int IsEditable()
    {
        var _result = _ptr->is_editable(_ptr);

        return _result;
    }

    public int IsSpellCheckEnabled()
    {
        var _result = _ptr->is_spell_check_enabled(_ptr);

        return _result;
    }

    public cef_context_menu_edit_state_flags_t GetEditStateFlags()
    {
        var _result = _ptr->get_edit_state_flags(_ptr);

        return _result;
    }

    public int IsCustomMenu()
    {
        var _result = _ptr->is_custom_menu(_ptr);

        return _result;
    }

        public _cef_base_ref_counted_t @base
        {
            get => _ptr->@base;
            set => _ptr->@base = value;
        }
}
