// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Wraps a library-owned instance of <c>_cef_composition_underline_t</c>.
/// </summary>
public unsafe partial class CefCompositionUnderlineRef : ICefCompositionUnderline
{
    private readonly _cef_composition_underline_t* _ptr;

    public CefCompositionUnderlineRef(_cef_composition_underline_t* ptr)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    _cef_composition_underline_t* ICefCompositionUnderline.NativePtr => _ptr;


    public nuint Size
    {
        get => _ptr->size;
        set => _ptr->size = value;
    }

    public _cef_range_t Range
    {
        get => _ptr->range;
        set => _ptr->range = value;
    }

    public uint Color
    {
        get => _ptr->color;
        set => _ptr->color = value;
    }

    public uint BackgroundColor
    {
        get => _ptr->background_color;
        set => _ptr->background_color = value;
    }

    public int Thick
    {
        get => _ptr->thick;
        set => _ptr->thick = value;
    }

    public cef_composition_underline_style_t Style
    {
        get => _ptr->style;
        set => _ptr->style = value;
    }
}
