#if OS_WIN
// <auto-generated/>
#nullable enable

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using RawCef.Native;

namespace RawCef;

/// <summary>
/// Abstract base class for client-side implementations of <c>_cef_dialog_handler_t</c>.
/// Subclass this to implement a custom CefDialogHandler.
/// </summary>
public unsafe abstract partial class CefDialogHandler : CefBaseRefCounted, ICefDialogHandler
{
    private _cef_dialog_handler_t* _typedPtr;

    protected CefDialogHandler() : this((nuint)sizeof(_cef_dialog_handler_t))
    {
    }

    protected CefDialogHandler(nuint structSize) : base(structSize)
    {
        _typedPtr = (_cef_dialog_handler_t*)NativePtr;
        InitializeNativeStruct();
    }

    _cef_dialog_handler_t* ICefDialogHandler.NativePtr => _typedPtr;

    /// <inheritdoc />
    protected override void InitializeNativeStruct()
    {
        base.InitializeNativeStruct();

        _typedPtr->on_file_dialog = &Bridge_OnFileDialog;
    }


    /// <summary>
    /// Implement the <c>on_file_dialog</c> callback.
    /// </summary>
    public abstract int OnFileDialog(ICefBrowser? arg0, cef_file_dialog_mode_t arg1, string? arg2, string? arg3, ICefStringList? arg4, ICefStringList? arg5, ICefStringList? arg6, ICefFileDialogCallback? arg7);

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_OnFileDialog(_cef_dialog_handler_t* self, _cef_browser_t* arg0, cef_file_dialog_mode_t arg1, _cef_string_utf16_t* arg2, _cef_string_utf16_t* arg3, _cef_string_list_t* arg4, _cef_string_list_t* arg5, _cef_string_list_t* arg6, _cef_file_dialog_callback_t* arg7)
    {
        var _m = GetManaged<CefDialogHandler>(self);

        var _a0 = arg0 != null ? new CefBrowserRef(arg0) : null;
        var _a1 = arg1;
        var _a2 = CefStringRef.ToStringAndFree(arg2);
        var _a3 = CefStringRef.ToStringAndFree(arg3);
        var _a4 = arg4 != null ? new CefStringListRef(arg4) : null;
        var _a5 = arg5 != null ? new CefStringListRef(arg5) : null;
        var _a6 = arg6 != null ? new CefStringListRef(arg6) : null;
        var _a7 = arg7 != null ? new CefFileDialogCallbackRef(arg7) : null;
        var _result = _m.OnFileDialog(_a0, _a1, _a2, _a3, _a4, _a5, _a6, _a7);

        return _result;
    }
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using RawCef.Native;

namespace RawCef;

/// <summary>
/// Abstract base class for client-side implementations of <c>_cef_dialog_handler_t</c>.
/// Subclass this to implement a custom CefDialogHandler.
/// </summary>
public unsafe abstract partial class CefDialogHandler : CefBaseRefCounted, ICefDialogHandler
{
    private _cef_dialog_handler_t* _typedPtr;

    protected CefDialogHandler() : this((nuint)sizeof(_cef_dialog_handler_t))
    {
    }

    protected CefDialogHandler(nuint structSize) : base(structSize)
    {
        _typedPtr = (_cef_dialog_handler_t*)NativePtr;
        InitializeNativeStruct();
    }

    _cef_dialog_handler_t* ICefDialogHandler.NativePtr => _typedPtr;

    /// <inheritdoc />
    protected override void InitializeNativeStruct()
    {
        base.InitializeNativeStruct();

        _typedPtr->on_file_dialog = &Bridge_OnFileDialog;
    }


    /// <summary>
    /// Implement the <c>on_file_dialog</c> callback.
    /// </summary>
    public abstract int OnFileDialog(ICefBrowser? arg0, cef_file_dialog_mode_t arg1, string? arg2, string? arg3, ICefStringList? arg4, ICefStringList? arg5, ICefStringList? arg6, ICefFileDialogCallback? arg7);

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_OnFileDialog(_cef_dialog_handler_t* self, _cef_browser_t* arg0, cef_file_dialog_mode_t arg1, _cef_string_utf16_t* arg2, _cef_string_utf16_t* arg3, _cef_string_list_t* arg4, _cef_string_list_t* arg5, _cef_string_list_t* arg6, _cef_file_dialog_callback_t* arg7)
    {
        var _m = GetManaged<CefDialogHandler>(self);

        var _a0 = arg0 != null ? new CefBrowserRef(arg0) : null;
        var _a1 = arg1;
        var _a2 = arg2;
        var _a3 = arg3;
        var _a4 = arg4 != null ? new CefStringListRef(arg4) : null;
        var _a5 = arg5 != null ? new CefStringListRef(arg5) : null;
        var _a6 = arg6 != null ? new CefStringListRef(arg6) : null;
        var _a7 = arg7 != null ? new CefFileDialogCallbackRef(arg7) : null;
        var _result = _m.OnFileDialog(_a0, _a1, _a2, _a3, _a4, _a5, _a6, _a7);

        return _result;
    }
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using RawCef.Native;

namespace RawCef;

/// <summary>
/// Abstract base class for client-side implementations of <c>_cef_dialog_handler_t</c>.
/// Subclass this to implement a custom CefDialogHandler.
/// </summary>
public unsafe abstract partial class CefDialogHandler : CefBaseRefCounted, ICefDialogHandler
{
    private _cef_dialog_handler_t* _typedPtr;

    protected CefDialogHandler() : this((nuint)sizeof(_cef_dialog_handler_t))
    {
    }

    protected CefDialogHandler(nuint structSize) : base(structSize)
    {
        _typedPtr = (_cef_dialog_handler_t*)NativePtr;
        InitializeNativeStruct();
    }

    _cef_dialog_handler_t* ICefDialogHandler.NativePtr => _typedPtr;

    /// <inheritdoc />
    protected override void InitializeNativeStruct()
    {
        base.InitializeNativeStruct();

        _typedPtr->on_file_dialog = &Bridge_OnFileDialog;
    }


    /// <summary>
    /// Implement the <c>on_file_dialog</c> callback.
    /// </summary>
    public abstract int OnFileDialog(ICefBrowser? arg0, cef_file_dialog_mode_t arg1, string? arg2, string? arg3, ICefStringList? arg4, ICefStringList? arg5, ICefStringList? arg6, ICefFileDialogCallback? arg7);

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_OnFileDialog(_cef_dialog_handler_t* self, _cef_browser_t* arg0, cef_file_dialog_mode_t arg1, _cef_string_utf16_t* arg2, _cef_string_utf16_t* arg3, _cef_string_list_t* arg4, _cef_string_list_t* arg5, _cef_string_list_t* arg6, _cef_file_dialog_callback_t* arg7)
    {
        var _m = GetManaged<CefDialogHandler>(self);

        var _a0 = arg0 != null ? new CefBrowserRef(arg0) : null;
        var _a1 = arg1;
        var _a2 = arg2;
        var _a3 = arg3;
        var _a4 = arg4 != null ? new CefStringListRef(arg4) : null;
        var _a5 = arg5 != null ? new CefStringListRef(arg5) : null;
        var _a6 = arg6 != null ? new CefStringListRef(arg6) : null;
        var _a7 = arg7 != null ? new CefFileDialogCallbackRef(arg7) : null;
        var _result = _m.OnFileDialog(_a0, _a1, _a2, _a3, _a4, _a5, _a6, _a7);

        return _result;
    }
}
#endif