// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Wraps a library-owned instance of <c>_cef_frame_t</c>.
/// Calls <c>add_ref</c> on construction and <c>release</c> on dispose
/// (for ref-counted types) or <c>del</c> on dispose (for scoped types).
/// </summary>
public unsafe partial class CefFrameRef : CefBaseRefCountedRef, ICefFrame
{
    private readonly _cef_frame_t* _ptr;

    public CefFrameRef(_cef_frame_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    _cef_frame_t* ICefFrame.NativePtr => _ptr;


    public int IsValid()
    {
        var _result = _ptr->is_valid(_ptr);

        return _result;
    }

    public void Undo()
    {
        _ptr->undo(_ptr);
    }

    public void Redo()
    {
        _ptr->redo(_ptr);
    }

    public void Cut()
    {
        _ptr->cut(_ptr);
    }

    public void Copy()
    {
        _ptr->copy(_ptr);
    }

    public void Paste()
    {
        _ptr->paste(_ptr);
    }

    public void PasteAndMatchStyle()
    {
        _ptr->paste_and_match_style(_ptr);
    }

    public void Del()
    {
        _ptr->del(_ptr);
    }

    public void SelectAll()
    {
        _ptr->select_all(_ptr);
    }

    public void ViewSource()
    {
        _ptr->view_source(_ptr);
    }

    public void GetSource(ICefStringVisitor? arg0)
    {
        _ptr->get_source(_ptr, arg0 is null ? null : arg0.NativePtr);
    }

    public void GetText(ICefStringVisitor? arg0)
    {
        _ptr->get_text(_ptr, arg0 is null ? null : arg0.NativePtr);
    }

    public void LoadRequest(ICefRequest? arg0)
    {
        _ptr->load_request(_ptr, arg0 is null ? null : arg0.NativePtr);
    }

    public void LoadUrl(string? arg0)
    {
        fixed (char* _p0 = arg0)
        {
            _cef_string_utf16_t _s0;
            CefStringRef.FillFromPinned(&_s0, _p0, arg0?.Length ?? 0);
            _ptr->load_url(_ptr, &_s0);
        }
    }

    public void ExecuteJavaScript(string? arg0, string? arg1, int arg2)
    {
        fixed (char* _p0 = arg0)
        fixed (char* _p1 = arg1)
        {
            _cef_string_utf16_t _s0;
            CefStringRef.FillFromPinned(&_s0, _p0, arg0?.Length ?? 0);
            _cef_string_utf16_t _s1;
            CefStringRef.FillFromPinned(&_s1, _p1, arg1?.Length ?? 0);
            _ptr->execute_java_script(_ptr, &_s0, &_s1, arg2);
        }
    }

    public int IsMain()
    {
        var _result = _ptr->is_main(_ptr);

        return _result;
    }

    public int IsFocused()
    {
        var _result = _ptr->is_focused(_ptr);

        return _result;
    }

    public cef_string_userfree_utf16_t GetName()
    {
        var _result = _ptr->get_name(_ptr);

        return _result;
    }

    public cef_string_userfree_utf16_t GetIdentifier()
    {
        var _result = _ptr->get_identifier(_ptr);

        return _result;
    }

    public ICefFrame? GetParent()
    {
        var _result = _ptr->get_parent(_ptr);

        return _result != null ? new CefFrameRef(_result) : null;
    }

    public cef_string_userfree_utf16_t GetUrl()
    {
        var _result = _ptr->get_url(_ptr);

        return _result;
    }

    public ICefBrowser? GetBrowser()
    {
        var _result = _ptr->get_browser(_ptr);

        return _result != null ? new CefBrowserRef(_result) : null;
    }

    public ICefV8Context? GetV8Context()
    {
        var _result = _ptr->get_v8_context(_ptr);

        return _result != null ? new CefV8ContextRef(_result) : null;
    }

    public void VisitDom(ICefDomvisitor? arg0)
    {
        _ptr->visit_dom(_ptr, arg0 is null ? null : arg0.NativePtr);
    }

    public ICefUrlrequest? CreateUrlrequest(ICefRequest? arg0, ICefUrlrequestClient? arg1)
    {
        var _result = _ptr->create_urlrequest(_ptr, arg0 is null ? null : arg0.NativePtr, arg1 is null ? null : arg1.NativePtr);

        return _result != null ? new CefUrlrequestRef(_result) : null;
    }

    public void SendProcessMessage(cef_process_id_t arg0, ICefProcessMessage? arg1)
    {
        _ptr->send_process_message(_ptr, arg0, arg1 is null ? null : arg1.NativePtr);
    }

    public _cef_base_ref_counted_t @base
    {
        get => _ptr->@base;
        set => _ptr->@base = value;
    }
}
