#if OS_WIN
// <auto-generated/>
#nullable enable

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using RawCef.Native;

namespace RawCef;

/// <summary>
/// Abstract base class for client-side implementations of <c>_cef_frame_t</c>.
/// Subclass this to implement a custom CefFrame.
/// </summary>
public unsafe abstract partial class CefFrame : CefBaseRefCounted, ICefFrame
{
    private _cef_frame_t* _typedPtr;

    protected CefFrame() : this((nuint)sizeof(_cef_frame_t))
    {
    }

    protected CefFrame(nuint structSize) : base(structSize)
    {
        _typedPtr = (_cef_frame_t*)NativePtr;
        InitializeNativeStruct();
    }

    _cef_frame_t* ICefFrame.NativePtr => _typedPtr;

    /// <inheritdoc />
    protected override void InitializeNativeStruct()
    {
        base.InitializeNativeStruct();

        _typedPtr->is_valid = &Bridge_IsValid;
        _typedPtr->undo = &Bridge_Undo;
        _typedPtr->redo = &Bridge_Redo;
        _typedPtr->cut = &Bridge_Cut;
        _typedPtr->copy = &Bridge_Copy;
        _typedPtr->paste = &Bridge_Paste;
        _typedPtr->paste_and_match_style = &Bridge_PasteAndMatchStyle;
        _typedPtr->select_all = &Bridge_SelectAll;
        _typedPtr->view_source = &Bridge_ViewSource;
        _typedPtr->get_source = &Bridge_GetSource;
        _typedPtr->get_text = &Bridge_GetText;
        _typedPtr->load_request = &Bridge_LoadRequest;
        _typedPtr->load_url = &Bridge_LoadUrl;
        _typedPtr->execute_java_script = &Bridge_ExecuteJavaScript;
        _typedPtr->is_main = &Bridge_IsMain;
        _typedPtr->is_focused = &Bridge_IsFocused;
        _typedPtr->get_name = &Bridge_GetName;
        _typedPtr->get_identifier = &Bridge_GetIdentifier;
        _typedPtr->get_parent = &Bridge_GetParent;
        _typedPtr->get_url = &Bridge_GetUrl;
        _typedPtr->get_browser = &Bridge_GetBrowser;
        _typedPtr->get_v8_context = &Bridge_GetV8Context;
        _typedPtr->visit_dom = &Bridge_VisitDom;
        _typedPtr->create_urlrequest = &Bridge_CreateUrlrequest;
        _typedPtr->send_process_message = &Bridge_SendProcessMessage;
    }


    /// <summary>
    /// Implement the <c>is_valid</c> callback.
    /// </summary>
    public abstract int IsValid();

    /// <summary>
    /// Implement the <c>undo</c> callback.
    /// </summary>
    public abstract void Undo();

    /// <summary>
    /// Implement the <c>redo</c> callback.
    /// </summary>
    public abstract void Redo();

    /// <summary>
    /// Implement the <c>cut</c> callback.
    /// </summary>
    public abstract void Cut();

    /// <summary>
    /// Implement the <c>copy</c> callback.
    /// </summary>
    public abstract void Copy();

    /// <summary>
    /// Implement the <c>paste</c> callback.
    /// </summary>
    public abstract void Paste();

    /// <summary>
    /// Implement the <c>paste_and_match_style</c> callback.
    /// </summary>
    public abstract void PasteAndMatchStyle();

    /// <summary>
    /// Implement the <c>select_all</c> callback.
    /// </summary>
    public abstract void SelectAll();

    /// <summary>
    /// Implement the <c>view_source</c> callback.
    /// </summary>
    public abstract void ViewSource();

    /// <summary>
    /// Implement the <c>get_source</c> callback.
    /// </summary>
    public abstract void GetSource(ICefStringVisitor? arg0);

    /// <summary>
    /// Implement the <c>get_text</c> callback.
    /// </summary>
    public abstract void GetText(ICefStringVisitor? arg0);

    /// <summary>
    /// Implement the <c>load_request</c> callback.
    /// </summary>
    public abstract void LoadRequest(ICefRequest? arg0);

    /// <summary>
    /// Implement the <c>load_url</c> callback.
    /// </summary>
    public abstract void LoadUrl(string? arg0);

    /// <summary>
    /// Implement the <c>execute_java_script</c> callback.
    /// </summary>
    public abstract void ExecuteJavaScript(string? arg0, string? arg1, int arg2);

    /// <summary>
    /// Implement the <c>is_main</c> callback.
    /// </summary>
    public abstract int IsMain();

    /// <summary>
    /// Implement the <c>is_focused</c> callback.
    /// </summary>
    public abstract int IsFocused();

    /// <summary>
    /// Implement the <c>get_name</c> callback.
    /// </summary>
    public abstract string? GetName();

    /// <summary>
    /// Implement the <c>get_identifier</c> callback.
    /// </summary>
    public abstract string? GetIdentifier();

    /// <summary>
    /// Implement the <c>get_parent</c> callback.
    /// </summary>
    public abstract ICefFrame? GetParent();

    /// <summary>
    /// Implement the <c>get_url</c> callback.
    /// </summary>
    public abstract string? GetUrl();

    /// <summary>
    /// Implement the <c>get_browser</c> callback.
    /// </summary>
    public abstract ICefBrowser? GetBrowser();

    /// <summary>
    /// Implement the <c>get_v8_context</c> callback.
    /// </summary>
    public abstract ICefV8Context? GetV8Context();

    /// <summary>
    /// Implement the <c>visit_dom</c> callback.
    /// </summary>
    public abstract void VisitDom(ICefDomvisitor? arg0);

    /// <summary>
    /// Implement the <c>create_urlrequest</c> callback.
    /// </summary>
    public abstract ICefUrlrequest? CreateUrlrequest(ICefRequest? arg0, ICefUrlrequestClient? arg1);

    /// <summary>
    /// Implement the <c>send_process_message</c> callback.
    /// </summary>
    public abstract void SendProcessMessage(cef_process_id_t arg0, ICefProcessMessage? arg1);

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_IsValid(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _result = _m.IsValid();

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_Undo(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            _m.Undo();
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_Redo(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            _m.Redo();
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_Cut(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            _m.Cut();
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_Copy(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            _m.Copy();
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_Paste(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            _m.Paste();
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_PasteAndMatchStyle(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            _m.PasteAndMatchStyle();
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_SelectAll(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            _m.SelectAll();
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_ViewSource(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            _m.ViewSource();
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_GetSource(_cef_frame_t* self, _cef_string_visitor_t* arg0)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _a0 = arg0 != null ? new CefStringVisitorRef(arg0) : null;
            _m.GetSource(_a0);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_GetText(_cef_frame_t* self, _cef_string_visitor_t* arg0)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _a0 = arg0 != null ? new CefStringVisitorRef(arg0) : null;
            _m.GetText(_a0);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_LoadRequest(_cef_frame_t* self, _cef_request_t* arg0)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _a0 = arg0 != null ? new CefRequestRef(arg0) : null;
            _m.LoadRequest(_a0);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_LoadUrl(_cef_frame_t* self, _cef_string_utf16_t* arg0)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _a0 = CefStringRef.ToString(arg0);
            _m.LoadUrl(_a0);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_ExecuteJavaScript(_cef_frame_t* self, _cef_string_utf16_t* arg0, _cef_string_utf16_t* arg1, int arg2)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _a0 = CefStringRef.ToString(arg0);
            var _a1 = CefStringRef.ToString(arg1);
            var _a2 = arg2;
            _m.ExecuteJavaScript(_a0, _a1, _a2);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_IsMain(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _result = _m.IsMain();

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_IsFocused(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _result = _m.IsFocused();

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static cef_string_userfree_utf16_t Bridge_GetName(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _result = _m.GetName();

            return CefStringRef.AllocUserfree(_result);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static cef_string_userfree_utf16_t Bridge_GetIdentifier(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _result = _m.GetIdentifier();

            return CefStringRef.AllocUserfree(_result);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_frame_t* Bridge_GetParent(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _result = _m.GetParent();

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static cef_string_userfree_utf16_t Bridge_GetUrl(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _result = _m.GetUrl();

            return CefStringRef.AllocUserfree(_result);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_browser_t* Bridge_GetBrowser(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _result = _m.GetBrowser();

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_v8_context_t* Bridge_GetV8Context(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _result = _m.GetV8Context();

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_VisitDom(_cef_frame_t* self, _cef_domvisitor_t* arg0)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _a0 = arg0 != null ? new CefDomvisitorRef(arg0) : null;
            _m.VisitDom(_a0);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_urlrequest_t* Bridge_CreateUrlrequest(_cef_frame_t* self, _cef_request_t* arg0, _cef_urlrequest_client_t* arg1)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _a0 = arg0 != null ? new CefRequestRef(arg0) : null;
            var _a1 = arg1 != null ? new CefUrlrequestClientRef(arg1) : null;
            var _result = _m.CreateUrlrequest(_a0, _a1);

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_SendProcessMessage(_cef_frame_t* self, cef_process_id_t arg0, _cef_process_message_t* arg1)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _a0 = arg0;
            var _a1 = arg1 != null ? new CefProcessMessageRef(arg1) : null;
            _m.SendProcessMessage(_a0, _a1);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using RawCef.Native;

namespace RawCef;

/// <summary>
/// Abstract base class for client-side implementations of <c>_cef_frame_t</c>.
/// Subclass this to implement a custom CefFrame.
/// </summary>
public unsafe abstract partial class CefFrame : CefBaseRefCounted, ICefFrame
{
    private _cef_frame_t* _typedPtr;

    protected CefFrame() : this((nuint)sizeof(_cef_frame_t))
    {
    }

    protected CefFrame(nuint structSize) : base(structSize)
    {
        _typedPtr = (_cef_frame_t*)NativePtr;
        InitializeNativeStruct();
    }

    _cef_frame_t* ICefFrame.NativePtr => _typedPtr;

    /// <inheritdoc />
    protected override void InitializeNativeStruct()
    {
        base.InitializeNativeStruct();

        _typedPtr->is_valid = &Bridge_IsValid;
        _typedPtr->undo = &Bridge_Undo;
        _typedPtr->redo = &Bridge_Redo;
        _typedPtr->cut = &Bridge_Cut;
        _typedPtr->copy = &Bridge_Copy;
        _typedPtr->paste = &Bridge_Paste;
        _typedPtr->paste_and_match_style = &Bridge_PasteAndMatchStyle;
        _typedPtr->select_all = &Bridge_SelectAll;
        _typedPtr->view_source = &Bridge_ViewSource;
        _typedPtr->get_source = &Bridge_GetSource;
        _typedPtr->get_text = &Bridge_GetText;
        _typedPtr->load_request = &Bridge_LoadRequest;
        _typedPtr->load_url = &Bridge_LoadUrl;
        _typedPtr->execute_java_script = &Bridge_ExecuteJavaScript;
        _typedPtr->is_main = &Bridge_IsMain;
        _typedPtr->is_focused = &Bridge_IsFocused;
        _typedPtr->get_name = &Bridge_GetName;
        _typedPtr->get_identifier = &Bridge_GetIdentifier;
        _typedPtr->get_parent = &Bridge_GetParent;
        _typedPtr->get_url = &Bridge_GetUrl;
        _typedPtr->get_browser = &Bridge_GetBrowser;
        _typedPtr->get_v8_context = &Bridge_GetV8Context;
        _typedPtr->visit_dom = &Bridge_VisitDom;
        _typedPtr->create_urlrequest = &Bridge_CreateUrlrequest;
        _typedPtr->send_process_message = &Bridge_SendProcessMessage;
    }


    /// <summary>
    /// Implement the <c>is_valid</c> callback.
    /// </summary>
    public abstract int IsValid();

    /// <summary>
    /// Implement the <c>undo</c> callback.
    /// </summary>
    public abstract void Undo();

    /// <summary>
    /// Implement the <c>redo</c> callback.
    /// </summary>
    public abstract void Redo();

    /// <summary>
    /// Implement the <c>cut</c> callback.
    /// </summary>
    public abstract void Cut();

    /// <summary>
    /// Implement the <c>copy</c> callback.
    /// </summary>
    public abstract void Copy();

    /// <summary>
    /// Implement the <c>paste</c> callback.
    /// </summary>
    public abstract void Paste();

    /// <summary>
    /// Implement the <c>paste_and_match_style</c> callback.
    /// </summary>
    public abstract void PasteAndMatchStyle();

    /// <summary>
    /// Implement the <c>select_all</c> callback.
    /// </summary>
    public abstract void SelectAll();

    /// <summary>
    /// Implement the <c>view_source</c> callback.
    /// </summary>
    public abstract void ViewSource();

    /// <summary>
    /// Implement the <c>get_source</c> callback.
    /// </summary>
    public abstract void GetSource(ICefStringVisitor? arg0);

    /// <summary>
    /// Implement the <c>get_text</c> callback.
    /// </summary>
    public abstract void GetText(ICefStringVisitor? arg0);

    /// <summary>
    /// Implement the <c>load_request</c> callback.
    /// </summary>
    public abstract void LoadRequest(ICefRequest? arg0);

    /// <summary>
    /// Implement the <c>load_url</c> callback.
    /// </summary>
    public abstract void LoadUrl(string? arg0);

    /// <summary>
    /// Implement the <c>execute_java_script</c> callback.
    /// </summary>
    public abstract void ExecuteJavaScript(string? arg0, string? arg1, int arg2);

    /// <summary>
    /// Implement the <c>is_main</c> callback.
    /// </summary>
    public abstract int IsMain();

    /// <summary>
    /// Implement the <c>is_focused</c> callback.
    /// </summary>
    public abstract int IsFocused();

    /// <summary>
    /// Implement the <c>get_name</c> callback.
    /// </summary>
    public abstract string? GetName();

    /// <summary>
    /// Implement the <c>get_identifier</c> callback.
    /// </summary>
    public abstract string? GetIdentifier();

    /// <summary>
    /// Implement the <c>get_parent</c> callback.
    /// </summary>
    public abstract ICefFrame? GetParent();

    /// <summary>
    /// Implement the <c>get_url</c> callback.
    /// </summary>
    public abstract string? GetUrl();

    /// <summary>
    /// Implement the <c>get_browser</c> callback.
    /// </summary>
    public abstract ICefBrowser? GetBrowser();

    /// <summary>
    /// Implement the <c>get_v8_context</c> callback.
    /// </summary>
    public abstract ICefV8Context? GetV8Context();

    /// <summary>
    /// Implement the <c>visit_dom</c> callback.
    /// </summary>
    public abstract void VisitDom(ICefDomvisitor? arg0);

    /// <summary>
    /// Implement the <c>create_urlrequest</c> callback.
    /// </summary>
    public abstract ICefUrlrequest? CreateUrlrequest(ICefRequest? arg0, ICefUrlrequestClient? arg1);

    /// <summary>
    /// Implement the <c>send_process_message</c> callback.
    /// </summary>
    public abstract void SendProcessMessage(cef_process_id_t arg0, ICefProcessMessage? arg1);

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_IsValid(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _result = _m.IsValid();

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_Undo(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            _m.Undo();
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_Redo(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            _m.Redo();
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_Cut(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            _m.Cut();
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_Copy(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            _m.Copy();
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_Paste(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            _m.Paste();
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_PasteAndMatchStyle(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            _m.PasteAndMatchStyle();
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_SelectAll(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            _m.SelectAll();
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_ViewSource(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            _m.ViewSource();
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_GetSource(_cef_frame_t* self, _cef_string_visitor_t* arg0)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _a0 = arg0 != null ? new CefStringVisitorRef(arg0) : null;
            _m.GetSource(_a0);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_GetText(_cef_frame_t* self, _cef_string_visitor_t* arg0)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _a0 = arg0 != null ? new CefStringVisitorRef(arg0) : null;
            _m.GetText(_a0);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_LoadRequest(_cef_frame_t* self, _cef_request_t* arg0)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _a0 = arg0 != null ? new CefRequestRef(arg0) : null;
            _m.LoadRequest(_a0);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_LoadUrl(_cef_frame_t* self, _cef_string_utf16_t* arg0)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _a0 = CefStringRef.ToString(arg0);
            _m.LoadUrl(_a0);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_ExecuteJavaScript(_cef_frame_t* self, _cef_string_utf16_t* arg0, _cef_string_utf16_t* arg1, int arg2)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _a0 = CefStringRef.ToString(arg0);
            var _a1 = CefStringRef.ToString(arg1);
            var _a2 = arg2;
            _m.ExecuteJavaScript(_a0, _a1, _a2);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_IsMain(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _result = _m.IsMain();

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_IsFocused(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _result = _m.IsFocused();

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static cef_string_userfree_utf16_t Bridge_GetName(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _result = _m.GetName();

            return CefStringRef.AllocUserfree(_result);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static cef_string_userfree_utf16_t Bridge_GetIdentifier(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _result = _m.GetIdentifier();

            return CefStringRef.AllocUserfree(_result);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_frame_t* Bridge_GetParent(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _result = _m.GetParent();

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static cef_string_userfree_utf16_t Bridge_GetUrl(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _result = _m.GetUrl();

            return CefStringRef.AllocUserfree(_result);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_browser_t* Bridge_GetBrowser(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _result = _m.GetBrowser();

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_v8_context_t* Bridge_GetV8Context(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _result = _m.GetV8Context();

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_VisitDom(_cef_frame_t* self, _cef_domvisitor_t* arg0)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _a0 = arg0 != null ? new CefDomvisitorRef(arg0) : null;
            _m.VisitDom(_a0);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_urlrequest_t* Bridge_CreateUrlrequest(_cef_frame_t* self, _cef_request_t* arg0, _cef_urlrequest_client_t* arg1)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _a0 = arg0 != null ? new CefRequestRef(arg0) : null;
            var _a1 = arg1 != null ? new CefUrlrequestClientRef(arg1) : null;
            var _result = _m.CreateUrlrequest(_a0, _a1);

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_SendProcessMessage(_cef_frame_t* self, cef_process_id_t arg0, _cef_process_message_t* arg1)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _a0 = arg0;
            var _a1 = arg1 != null ? new CefProcessMessageRef(arg1) : null;
            _m.SendProcessMessage(_a0, _a1);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using RawCef.Native;

namespace RawCef;

/// <summary>
/// Abstract base class for client-side implementations of <c>_cef_frame_t</c>.
/// Subclass this to implement a custom CefFrame.
/// </summary>
public unsafe abstract partial class CefFrame : CefBaseRefCounted, ICefFrame
{
    private _cef_frame_t* _typedPtr;

    protected CefFrame() : this((nuint)sizeof(_cef_frame_t))
    {
    }

    protected CefFrame(nuint structSize) : base(structSize)
    {
        _typedPtr = (_cef_frame_t*)NativePtr;
        InitializeNativeStruct();
    }

    _cef_frame_t* ICefFrame.NativePtr => _typedPtr;

    /// <inheritdoc />
    protected override void InitializeNativeStruct()
    {
        base.InitializeNativeStruct();

        _typedPtr->is_valid = &Bridge_IsValid;
        _typedPtr->undo = &Bridge_Undo;
        _typedPtr->redo = &Bridge_Redo;
        _typedPtr->cut = &Bridge_Cut;
        _typedPtr->copy = &Bridge_Copy;
        _typedPtr->paste = &Bridge_Paste;
        _typedPtr->paste_and_match_style = &Bridge_PasteAndMatchStyle;
        _typedPtr->select_all = &Bridge_SelectAll;
        _typedPtr->view_source = &Bridge_ViewSource;
        _typedPtr->get_source = &Bridge_GetSource;
        _typedPtr->get_text = &Bridge_GetText;
        _typedPtr->load_request = &Bridge_LoadRequest;
        _typedPtr->load_url = &Bridge_LoadUrl;
        _typedPtr->execute_java_script = &Bridge_ExecuteJavaScript;
        _typedPtr->is_main = &Bridge_IsMain;
        _typedPtr->is_focused = &Bridge_IsFocused;
        _typedPtr->get_name = &Bridge_GetName;
        _typedPtr->get_identifier = &Bridge_GetIdentifier;
        _typedPtr->get_parent = &Bridge_GetParent;
        _typedPtr->get_url = &Bridge_GetUrl;
        _typedPtr->get_browser = &Bridge_GetBrowser;
        _typedPtr->get_v8_context = &Bridge_GetV8Context;
        _typedPtr->visit_dom = &Bridge_VisitDom;
        _typedPtr->create_urlrequest = &Bridge_CreateUrlrequest;
        _typedPtr->send_process_message = &Bridge_SendProcessMessage;
    }


    /// <summary>
    /// Implement the <c>is_valid</c> callback.
    /// </summary>
    public abstract int IsValid();

    /// <summary>
    /// Implement the <c>undo</c> callback.
    /// </summary>
    public abstract void Undo();

    /// <summary>
    /// Implement the <c>redo</c> callback.
    /// </summary>
    public abstract void Redo();

    /// <summary>
    /// Implement the <c>cut</c> callback.
    /// </summary>
    public abstract void Cut();

    /// <summary>
    /// Implement the <c>copy</c> callback.
    /// </summary>
    public abstract void Copy();

    /// <summary>
    /// Implement the <c>paste</c> callback.
    /// </summary>
    public abstract void Paste();

    /// <summary>
    /// Implement the <c>paste_and_match_style</c> callback.
    /// </summary>
    public abstract void PasteAndMatchStyle();

    /// <summary>
    /// Implement the <c>select_all</c> callback.
    /// </summary>
    public abstract void SelectAll();

    /// <summary>
    /// Implement the <c>view_source</c> callback.
    /// </summary>
    public abstract void ViewSource();

    /// <summary>
    /// Implement the <c>get_source</c> callback.
    /// </summary>
    public abstract void GetSource(ICefStringVisitor? arg0);

    /// <summary>
    /// Implement the <c>get_text</c> callback.
    /// </summary>
    public abstract void GetText(ICefStringVisitor? arg0);

    /// <summary>
    /// Implement the <c>load_request</c> callback.
    /// </summary>
    public abstract void LoadRequest(ICefRequest? arg0);

    /// <summary>
    /// Implement the <c>load_url</c> callback.
    /// </summary>
    public abstract void LoadUrl(string? arg0);

    /// <summary>
    /// Implement the <c>execute_java_script</c> callback.
    /// </summary>
    public abstract void ExecuteJavaScript(string? arg0, string? arg1, int arg2);

    /// <summary>
    /// Implement the <c>is_main</c> callback.
    /// </summary>
    public abstract int IsMain();

    /// <summary>
    /// Implement the <c>is_focused</c> callback.
    /// </summary>
    public abstract int IsFocused();

    /// <summary>
    /// Implement the <c>get_name</c> callback.
    /// </summary>
    public abstract string? GetName();

    /// <summary>
    /// Implement the <c>get_identifier</c> callback.
    /// </summary>
    public abstract string? GetIdentifier();

    /// <summary>
    /// Implement the <c>get_parent</c> callback.
    /// </summary>
    public abstract ICefFrame? GetParent();

    /// <summary>
    /// Implement the <c>get_url</c> callback.
    /// </summary>
    public abstract string? GetUrl();

    /// <summary>
    /// Implement the <c>get_browser</c> callback.
    /// </summary>
    public abstract ICefBrowser? GetBrowser();

    /// <summary>
    /// Implement the <c>get_v8_context</c> callback.
    /// </summary>
    public abstract ICefV8Context? GetV8Context();

    /// <summary>
    /// Implement the <c>visit_dom</c> callback.
    /// </summary>
    public abstract void VisitDom(ICefDomvisitor? arg0);

    /// <summary>
    /// Implement the <c>create_urlrequest</c> callback.
    /// </summary>
    public abstract ICefUrlrequest? CreateUrlrequest(ICefRequest? arg0, ICefUrlrequestClient? arg1);

    /// <summary>
    /// Implement the <c>send_process_message</c> callback.
    /// </summary>
    public abstract void SendProcessMessage(cef_process_id_t arg0, ICefProcessMessage? arg1);

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_IsValid(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _result = _m.IsValid();

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_Undo(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            _m.Undo();
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_Redo(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            _m.Redo();
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_Cut(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            _m.Cut();
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_Copy(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            _m.Copy();
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_Paste(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            _m.Paste();
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_PasteAndMatchStyle(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            _m.PasteAndMatchStyle();
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_SelectAll(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            _m.SelectAll();
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_ViewSource(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            _m.ViewSource();
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_GetSource(_cef_frame_t* self, _cef_string_visitor_t* arg0)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _a0 = arg0 != null ? new CefStringVisitorRef(arg0) : null;
            _m.GetSource(_a0);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_GetText(_cef_frame_t* self, _cef_string_visitor_t* arg0)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _a0 = arg0 != null ? new CefStringVisitorRef(arg0) : null;
            _m.GetText(_a0);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_LoadRequest(_cef_frame_t* self, _cef_request_t* arg0)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _a0 = arg0 != null ? new CefRequestRef(arg0) : null;
            _m.LoadRequest(_a0);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_LoadUrl(_cef_frame_t* self, _cef_string_utf16_t* arg0)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _a0 = CefStringRef.ToString(arg0);
            _m.LoadUrl(_a0);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_ExecuteJavaScript(_cef_frame_t* self, _cef_string_utf16_t* arg0, _cef_string_utf16_t* arg1, int arg2)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _a0 = CefStringRef.ToString(arg0);
            var _a1 = CefStringRef.ToString(arg1);
            var _a2 = arg2;
            _m.ExecuteJavaScript(_a0, _a1, _a2);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_IsMain(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _result = _m.IsMain();

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_IsFocused(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _result = _m.IsFocused();

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static cef_string_userfree_utf16_t Bridge_GetName(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _result = _m.GetName();

            return CefStringRef.AllocUserfree(_result);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static cef_string_userfree_utf16_t Bridge_GetIdentifier(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _result = _m.GetIdentifier();

            return CefStringRef.AllocUserfree(_result);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_frame_t* Bridge_GetParent(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _result = _m.GetParent();

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static cef_string_userfree_utf16_t Bridge_GetUrl(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _result = _m.GetUrl();

            return CefStringRef.AllocUserfree(_result);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_browser_t* Bridge_GetBrowser(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _result = _m.GetBrowser();

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_v8_context_t* Bridge_GetV8Context(_cef_frame_t* self)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _result = _m.GetV8Context();

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_VisitDom(_cef_frame_t* self, _cef_domvisitor_t* arg0)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _a0 = arg0 != null ? new CefDomvisitorRef(arg0) : null;
            _m.VisitDom(_a0);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_urlrequest_t* Bridge_CreateUrlrequest(_cef_frame_t* self, _cef_request_t* arg0, _cef_urlrequest_client_t* arg1)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _a0 = arg0 != null ? new CefRequestRef(arg0) : null;
            var _a1 = arg1 != null ? new CefUrlrequestClientRef(arg1) : null;
            var _result = _m.CreateUrlrequest(_a0, _a1);

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_SendProcessMessage(_cef_frame_t* self, cef_process_id_t arg0, _cef_process_message_t* arg1)
    {
        try
        {
            var _m = GetManaged<CefFrame>(self);

            var _a0 = arg0;
            var _a1 = arg1 != null ? new CefProcessMessageRef(arg1) : null;
            _m.SendProcessMessage(_a0, _a1);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }
}
#endif