#if OS_WIN
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Wraps a library-owned instance of <c>_cef_list_value_t</c>.
/// Calls <c>add_ref</c> on construction and <c>release</c> on dispose
/// (for ref-counted types) or <c>del</c> on dispose (for scoped types).
/// </summary>
public unsafe partial class CefListValueRef : CefBaseRefCountedRef, ICefListValue
{
    private readonly _cef_list_value_t* _ptr;

    public CefListValueRef(_cef_list_value_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    _cef_list_value_t* ICefListValue.NativePtr => _ptr;


    public int IsValid()
    {
        var _result = _ptr->is_valid(_ptr);

        return _result;
    }

    public int IsOwned()
    {
        var _result = _ptr->is_owned(_ptr);

        return _result;
    }

    public int IsReadOnly()
    {
        var _result = _ptr->is_read_only(_ptr);

        return _result;
    }

    public int IsSame(ICefListValue? arg0)
    {
        var _result = _ptr->is_same(_ptr, arg0 is null ? null : arg0.NativePtr);

        return _result;
    }

    public int IsEqual(ICefListValue? arg0)
    {
        var _result = _ptr->is_equal(_ptr, arg0 is null ? null : arg0.NativePtr);

        return _result;
    }

    public ICefListValue? Copy()
    {
        var _result = _ptr->copy(_ptr);

        return _result != null ? new CefListValueRef(_result) : null;
    }

    public int SetSize(nuint arg0)
    {
        var _result = _ptr->set_size(_ptr, arg0);

        return _result;
    }

    public nuint GetSize()
    {
        var _result = _ptr->get_size(_ptr);

        return _result;
    }

    public int Clear()
    {
        var _result = _ptr->clear(_ptr);

        return _result;
    }

    public int Remove(nuint arg0)
    {
        var _result = _ptr->remove(_ptr, arg0);

        return _result;
    }

    public cef_value_type_t GetType(nuint arg0)
    {
        var _result = _ptr->get_type(_ptr, arg0);

        return _result;
    }

    public ICefValue? GetValue(nuint arg0)
    {
        var _result = _ptr->get_value(_ptr, arg0);

        return _result != null ? new CefValueRef(_result) : null;
    }

    public int GetBool(nuint arg0)
    {
        var _result = _ptr->get_bool(_ptr, arg0);

        return _result;
    }

    public int GetInt(nuint arg0)
    {
        var _result = _ptr->get_int(_ptr, arg0);

        return _result;
    }

    public double GetDouble(nuint arg0)
    {
        var _result = _ptr->get_double(_ptr, arg0);

        return _result;
    }

    public cef_string_userfree_utf16_t GetString(nuint arg0)
    {
        var _result = _ptr->get_string(_ptr, arg0);

        return _result;
    }

    public ICefBinaryValue? GetBinary(nuint arg0)
    {
        var _result = _ptr->get_binary(_ptr, arg0);

        return _result != null ? new CefBinaryValueRef(_result) : null;
    }

    public ICefDictionaryValue? GetDictionary(nuint arg0)
    {
        var _result = _ptr->get_dictionary(_ptr, arg0);

        return _result != null ? new CefDictionaryValueRef(_result) : null;
    }

    public ICefListValue? GetList(nuint arg0)
    {
        var _result = _ptr->get_list(_ptr, arg0);

        return _result != null ? new CefListValueRef(_result) : null;
    }

    public int SetValue(nuint arg0, ICefValue? arg1)
    {
        var _result = _ptr->set_value(_ptr, arg0, arg1 is null ? null : arg1.NativePtr);

        return _result;
    }

    public int SetNull(nuint arg0)
    {
        var _result = _ptr->set_null(_ptr, arg0);

        return _result;
    }

    public int SetBool(nuint arg0, int arg1)
    {
        var _result = _ptr->set_bool(_ptr, arg0, arg1);

        return _result;
    }

    public int SetInt(nuint arg0, int arg1)
    {
        var _result = _ptr->set_int(_ptr, arg0, arg1);

        return _result;
    }

    public int SetDouble(nuint arg0, double arg1)
    {
        var _result = _ptr->set_double(_ptr, arg0, arg1);

        return _result;
    }

    public int SetString(nuint arg0, string? arg1)
    {
        fixed (char* _p1 = arg1)
        {
            _cef_string_utf16_t _s1;
            CefStringRef.FillFromPinned(&_s1, _p1, arg1?.Length ?? 0);
            var _result = _ptr->set_string(_ptr, arg0, &_s1);

            return _result;
        }
    }

    public int SetBinary(nuint arg0, ICefBinaryValue? arg1)
    {
        var _result = _ptr->set_binary(_ptr, arg0, arg1 is null ? null : arg1.NativePtr);

        return _result;
    }

    public int SetDictionary(nuint arg0, ICefDictionaryValue? arg1)
    {
        var _result = _ptr->set_dictionary(_ptr, arg0, arg1 is null ? null : arg1.NativePtr);

        return _result;
    }

    public int SetList(nuint arg0, ICefListValue? arg1)
    {
        var _result = _ptr->set_list(_ptr, arg0, arg1 is null ? null : arg1.NativePtr);

        return _result;
    }

    public _cef_base_ref_counted_t @base
    {
        get => _ptr->@base;
        set => _ptr->@base = value;
    }
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Wraps a library-owned instance of <c>_cef_list_value_t</c>.
/// Calls <c>add_ref</c> on construction and <c>release</c> on dispose
/// (for ref-counted types) or <c>del</c> on dispose (for scoped types).
/// </summary>
public unsafe partial class CefListValueRef : CefBaseRefCountedRef, ICefListValue
{
    private readonly _cef_list_value_t* _ptr;

    public CefListValueRef(_cef_list_value_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    _cef_list_value_t* ICefListValue.NativePtr => _ptr;


    public int IsValid()
    {
        var _result = _ptr->is_valid(_ptr);

        return _result;
    }

    public int IsOwned()
    {
        var _result = _ptr->is_owned(_ptr);

        return _result;
    }

    public int IsReadOnly()
    {
        var _result = _ptr->is_read_only(_ptr);

        return _result;
    }

    public int IsSame(ICefListValue? arg0)
    {
        var _result = _ptr->is_same(_ptr, arg0 is null ? null : arg0.NativePtr);

        return _result;
    }

    public int IsEqual(ICefListValue? arg0)
    {
        var _result = _ptr->is_equal(_ptr, arg0 is null ? null : arg0.NativePtr);

        return _result;
    }

    public ICefListValue? Copy()
    {
        var _result = _ptr->copy(_ptr);

        return _result != null ? new CefListValueRef(_result) : null;
    }

    public int SetSize(nuint arg0)
    {
        var _result = _ptr->set_size(_ptr, arg0);

        return _result;
    }

    public nuint GetSize()
    {
        var _result = _ptr->get_size(_ptr);

        return _result;
    }

    public int Clear()
    {
        var _result = _ptr->clear(_ptr);

        return _result;
    }

    public int Remove(nuint arg0)
    {
        var _result = _ptr->remove(_ptr, arg0);

        return _result;
    }

    public cef_value_type_t GetType(nuint arg0)
    {
        var _result = _ptr->get_type(_ptr, arg0);

        return _result;
    }

    public ICefValue? GetValue(nuint arg0)
    {
        var _result = _ptr->get_value(_ptr, arg0);

        return _result != null ? new CefValueRef(_result) : null;
    }

    public int GetBool(nuint arg0)
    {
        var _result = _ptr->get_bool(_ptr, arg0);

        return _result;
    }

    public int GetInt(nuint arg0)
    {
        var _result = _ptr->get_int(_ptr, arg0);

        return _result;
    }

    public double GetDouble(nuint arg0)
    {
        var _result = _ptr->get_double(_ptr, arg0);

        return _result;
    }

    public cef_string_userfree_utf16_t GetString(nuint arg0)
    {
        var _result = _ptr->get_string(_ptr, arg0);

        return _result;
    }

    public ICefBinaryValue? GetBinary(nuint arg0)
    {
        var _result = _ptr->get_binary(_ptr, arg0);

        return _result != null ? new CefBinaryValueRef(_result) : null;
    }

    public ICefDictionaryValue? GetDictionary(nuint arg0)
    {
        var _result = _ptr->get_dictionary(_ptr, arg0);

        return _result != null ? new CefDictionaryValueRef(_result) : null;
    }

    public ICefListValue? GetList(nuint arg0)
    {
        var _result = _ptr->get_list(_ptr, arg0);

        return _result != null ? new CefListValueRef(_result) : null;
    }

    public int SetValue(nuint arg0, ICefValue? arg1)
    {
        var _result = _ptr->set_value(_ptr, arg0, arg1 is null ? null : arg1.NativePtr);

        return _result;
    }

    public int SetNull(nuint arg0)
    {
        var _result = _ptr->set_null(_ptr, arg0);

        return _result;
    }

    public int SetBool(nuint arg0, int arg1)
    {
        var _result = _ptr->set_bool(_ptr, arg0, arg1);

        return _result;
    }

    public int SetInt(nuint arg0, int arg1)
    {
        var _result = _ptr->set_int(_ptr, arg0, arg1);

        return _result;
    }

    public int SetDouble(nuint arg0, double arg1)
    {
        var _result = _ptr->set_double(_ptr, arg0, arg1);

        return _result;
    }

    public int SetString(nuint arg0, string? arg1)
    {
        var _result = _ptr->set_string(_ptr, arg0, arg1);

        return _result;
    }

    public int SetBinary(nuint arg0, ICefBinaryValue? arg1)
    {
        var _result = _ptr->set_binary(_ptr, arg0, arg1 is null ? null : arg1.NativePtr);

        return _result;
    }

    public int SetDictionary(nuint arg0, ICefDictionaryValue? arg1)
    {
        var _result = _ptr->set_dictionary(_ptr, arg0, arg1 is null ? null : arg1.NativePtr);

        return _result;
    }

    public int SetList(nuint arg0, ICefListValue? arg1)
    {
        var _result = _ptr->set_list(_ptr, arg0, arg1 is null ? null : arg1.NativePtr);

        return _result;
    }

    public _cef_base_ref_counted_t @base
    {
        get => _ptr->@base;
        set => _ptr->@base = value;
    }
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Wraps a library-owned instance of <c>_cef_list_value_t</c>.
/// Calls <c>add_ref</c> on construction and <c>release</c> on dispose
/// (for ref-counted types) or <c>del</c> on dispose (for scoped types).
/// </summary>
public unsafe partial class CefListValueRef : CefBaseRefCountedRef, ICefListValue
{
    private readonly _cef_list_value_t* _ptr;

    public CefListValueRef(_cef_list_value_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    _cef_list_value_t* ICefListValue.NativePtr => _ptr;


    public int IsValid()
    {
        var _result = _ptr->is_valid(_ptr);

        return _result;
    }

    public int IsOwned()
    {
        var _result = _ptr->is_owned(_ptr);

        return _result;
    }

    public int IsReadOnly()
    {
        var _result = _ptr->is_read_only(_ptr);

        return _result;
    }

    public int IsSame(ICefListValue? arg0)
    {
        var _result = _ptr->is_same(_ptr, arg0 is null ? null : arg0.NativePtr);

        return _result;
    }

    public int IsEqual(ICefListValue? arg0)
    {
        var _result = _ptr->is_equal(_ptr, arg0 is null ? null : arg0.NativePtr);

        return _result;
    }

    public ICefListValue? Copy()
    {
        var _result = _ptr->copy(_ptr);

        return _result != null ? new CefListValueRef(_result) : null;
    }

    public int SetSize(nuint arg0)
    {
        var _result = _ptr->set_size(_ptr, arg0);

        return _result;
    }

    public nuint GetSize()
    {
        var _result = _ptr->get_size(_ptr);

        return _result;
    }

    public int Clear()
    {
        var _result = _ptr->clear(_ptr);

        return _result;
    }

    public int Remove(nuint arg0)
    {
        var _result = _ptr->remove(_ptr, arg0);

        return _result;
    }

    public cef_value_type_t GetType(nuint arg0)
    {
        var _result = _ptr->get_type(_ptr, arg0);

        return _result;
    }

    public ICefValue? GetValue(nuint arg0)
    {
        var _result = _ptr->get_value(_ptr, arg0);

        return _result != null ? new CefValueRef(_result) : null;
    }

    public int GetBool(nuint arg0)
    {
        var _result = _ptr->get_bool(_ptr, arg0);

        return _result;
    }

    public int GetInt(nuint arg0)
    {
        var _result = _ptr->get_int(_ptr, arg0);

        return _result;
    }

    public double GetDouble(nuint arg0)
    {
        var _result = _ptr->get_double(_ptr, arg0);

        return _result;
    }

    public cef_string_userfree_utf16_t GetString(nuint arg0)
    {
        var _result = _ptr->get_string(_ptr, arg0);

        return _result;
    }

    public ICefBinaryValue? GetBinary(nuint arg0)
    {
        var _result = _ptr->get_binary(_ptr, arg0);

        return _result != null ? new CefBinaryValueRef(_result) : null;
    }

    public ICefDictionaryValue? GetDictionary(nuint arg0)
    {
        var _result = _ptr->get_dictionary(_ptr, arg0);

        return _result != null ? new CefDictionaryValueRef(_result) : null;
    }

    public ICefListValue? GetList(nuint arg0)
    {
        var _result = _ptr->get_list(_ptr, arg0);

        return _result != null ? new CefListValueRef(_result) : null;
    }

    public int SetValue(nuint arg0, ICefValue? arg1)
    {
        var _result = _ptr->set_value(_ptr, arg0, arg1 is null ? null : arg1.NativePtr);

        return _result;
    }

    public int SetNull(nuint arg0)
    {
        var _result = _ptr->set_null(_ptr, arg0);

        return _result;
    }

    public int SetBool(nuint arg0, int arg1)
    {
        var _result = _ptr->set_bool(_ptr, arg0, arg1);

        return _result;
    }

    public int SetInt(nuint arg0, int arg1)
    {
        var _result = _ptr->set_int(_ptr, arg0, arg1);

        return _result;
    }

    public int SetDouble(nuint arg0, double arg1)
    {
        var _result = _ptr->set_double(_ptr, arg0, arg1);

        return _result;
    }

    public int SetString(nuint arg0, string? arg1)
    {
        var _result = _ptr->set_string(_ptr, arg0, arg1);

        return _result;
    }

    public int SetBinary(nuint arg0, ICefBinaryValue? arg1)
    {
        var _result = _ptr->set_binary(_ptr, arg0, arg1 is null ? null : arg1.NativePtr);

        return _result;
    }

    public int SetDictionary(nuint arg0, ICefDictionaryValue? arg1)
    {
        var _result = _ptr->set_dictionary(_ptr, arg0, arg1 is null ? null : arg1.NativePtr);

        return _result;
    }

    public int SetList(nuint arg0, ICefListValue? arg1)
    {
        var _result = _ptr->set_list(_ptr, arg0, arg1 is null ? null : arg1.NativePtr);

        return _result;
    }

    public _cef_base_ref_counted_t @base
    {
        get => _ptr->@base;
        set => _ptr->@base = value;
    }
}
#endif