// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Wraps a library-owned instance of <c>_cef_media_sink_t</c>.
/// Calls <c>add_ref</c> on construction and <c>release</c> on dispose
/// (for ref-counted types) or <c>del</c> on dispose (for scoped types).
/// </summary>
public unsafe partial class CefMediaSinkRef : CefBaseRefCountedRef, ICefMediaSink
{
    private readonly _cef_media_sink_t* _ptr;

    public CefMediaSinkRef(_cef_media_sink_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    _cef_media_sink_t* ICefMediaSink.NativePtr => _ptr;


    public cef_string_userfree_utf16_t GetId()
    {
        var _result = _ptr->get_id(_ptr);

        return _result;
    }

    public cef_string_userfree_utf16_t GetName()
    {
        var _result = _ptr->get_name(_ptr);

        return _result;
    }

    public cef_media_sink_icon_type_t GetIconType()
    {
        var _result = _ptr->get_icon_type(_ptr);

        return _result;
    }

    public void GetDeviceInfo(ICefMediaSinkDeviceInfoCallback? arg0)
    {
        _ptr->get_device_info(_ptr, arg0 is null ? null : arg0.NativePtr);
    }

    public int IsCastSink()
    {
        var _result = _ptr->is_cast_sink(_ptr);

        return _result;
    }

    public int IsDialSink()
    {
        var _result = _ptr->is_dial_sink(_ptr);

        return _result;
    }

    public int IsCompatibleWith(ICefMediaSource? arg0)
    {
        var _result = _ptr->is_compatible_with(_ptr, arg0 is null ? null : arg0.NativePtr);

        return _result;
    }

    public _cef_base_ref_counted_t @base
    {
        get => _ptr->@base;
        set => _ptr->@base = value;
    }
}
