// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Wraps a library-owned instance of <c>_cef_media_observer_t</c>.
/// Calls <c>add_ref</c> on construction and <c>release</c> on dispose
/// (for ref-counted types) or <c>del</c> on dispose (for scoped types).
/// </summary>
public unsafe partial class CefMediaObserverRef : CefBaseRefCountedRef, ICefMediaObserver
{
    private readonly _cef_media_observer_t* _ptr;

    public CefMediaObserverRef(_cef_media_observer_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    _cef_media_observer_t* ICefMediaObserver.NativePtr => _ptr;


    public void OnSinks(nuint arg0, _cef_media_sink_t** arg1)
    {
        _ptr->on_sinks(_ptr, arg0, arg1);
    }

    public void OnRoutes(nuint arg0, _cef_media_route_t** arg1)
    {
        _ptr->on_routes(_ptr, arg0, arg1);
    }

    public void OnRouteStateChanged(ICefMediaRoute? arg0, cef_media_route_connection_state_t arg1)
    {
        _ptr->on_route_state_changed(_ptr, arg0 is null ? null : arg0.NativePtr, arg1);
    }

    public void OnRouteMessageReceived(ICefMediaRoute? arg0, void* arg1, nuint arg2)
    {
        _ptr->on_route_message_received(_ptr, arg0 is null ? null : arg0.NativePtr, arg1, arg2);
    }

    public _cef_base_ref_counted_t @base
    {
        get => _ptr->@base;
        set => _ptr->@base = value;
    }
}
