// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

public unsafe partial class CefPreferenceRegistrar : CefBaseScoped
{
    private readonly _cef_preference_registrar_t* _ptr;

    public CefPreferenceRegistrar(_cef_preference_registrar_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    internal _cef_preference_registrar_t* NativePtr => _ptr;

    public int AddPreference(string? arg0, CefValue? arg1)
    {
        fixed (char* _p0 = arg0)
        {
            _cef_string_utf16_t _s0;
            CefStringRef.FillFromPinned(&_s0, _p0, arg0?.Length ?? 0);
            var _result = _ptr->add_preference(_ptr, &_s0, arg1 is null ? null : arg1.NativePtr);

            return _result;
        }
    }

        public _cef_base_scoped_t @base
        {
            get => _ptr->@base;
            set => _ptr->@base = value;
        }
}
