#if OS_WIN
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Wraps a library-owned instance of <c>_cef_preference_manager_t</c>.
/// Calls <c>add_ref</c> on construction and <c>release</c> on dispose
/// (for ref-counted types) or <c>del</c> on dispose (for scoped types).
/// </summary>
public unsafe partial class CefPreferenceManagerRef : CefBaseRefCountedRef, ICefPreferenceManager
{
    private readonly _cef_preference_manager_t* _ptr;

    public CefPreferenceManagerRef(_cef_preference_manager_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    _cef_preference_manager_t* ICefPreferenceManager.NativePtr => _ptr;


    public int HasPreference(string? arg0)
    {
        fixed (char* _p0 = arg0)
        {
            _cef_string_utf16_t _s0;
            CefStringRef.FillFromPinned(&_s0, _p0, arg0?.Length ?? 0);
            var _result = _ptr->has_preference(_ptr, &_s0);

            return _result;
        }
    }

    public ICefValue? GetPreference(string? arg0)
    {
        fixed (char* _p0 = arg0)
        {
            _cef_string_utf16_t _s0;
            CefStringRef.FillFromPinned(&_s0, _p0, arg0?.Length ?? 0);
            var _result = _ptr->get_preference(_ptr, &_s0);

            return _result != null ? new CefValueRef(_result) : null;
        }
    }

    public ICefDictionaryValue? GetAllPreferences(int arg0)
    {
        var _result = _ptr->get_all_preferences(_ptr, arg0);

        return _result != null ? new CefDictionaryValueRef(_result) : null;
    }

    public int CanSetPreference(string? arg0)
    {
        fixed (char* _p0 = arg0)
        {
            _cef_string_utf16_t _s0;
            CefStringRef.FillFromPinned(&_s0, _p0, arg0?.Length ?? 0);
            var _result = _ptr->can_set_preference(_ptr, &_s0);

            return _result;
        }
    }

    public int SetPreference(string? arg0, ICefValue? arg1, out string? arg2)
    {
        _cef_string_utf16_t _out2 = default;
        fixed (char* _p0 = arg0)
        {
            _cef_string_utf16_t _s0;
            CefStringRef.FillFromPinned(&_s0, _p0, arg0?.Length ?? 0);
            var _result = _ptr->set_preference(_ptr, &_s0, arg1 is null ? null : arg1.NativePtr, &_out2);

            arg2 = CefStringRef.ToStringAndFree(&_out2);
            return _result;
        }
    }

    public ICefRegistration? AddPreferenceObserver(string? arg0, ICefPreferenceObserver? arg1)
    {
        fixed (char* _p0 = arg0)
        {
            _cef_string_utf16_t _s0;
            CefStringRef.FillFromPinned(&_s0, _p0, arg0?.Length ?? 0);
            var _result = _ptr->add_preference_observer(_ptr, &_s0, arg1 is null ? null : arg1.NativePtr);

            return _result != null ? new CefRegistrationRef(_result) : null;
        }
    }

    public _cef_base_ref_counted_t @base
    {
        get => _ptr->@base;
        set => _ptr->@base = value;
    }
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Wraps a library-owned instance of <c>_cef_preference_manager_t</c>.
/// Calls <c>add_ref</c> on construction and <c>release</c> on dispose
/// (for ref-counted types) or <c>del</c> on dispose (for scoped types).
/// </summary>
public unsafe partial class CefPreferenceManagerRef : CefBaseRefCountedRef, ICefPreferenceManager
{
    private readonly _cef_preference_manager_t* _ptr;

    public CefPreferenceManagerRef(_cef_preference_manager_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    _cef_preference_manager_t* ICefPreferenceManager.NativePtr => _ptr;


    public int HasPreference(string? arg0)
    {
        var _result = _ptr->has_preference(_ptr, arg0);

        return _result;
    }

    public ICefValue? GetPreference(string? arg0)
    {
        var _result = _ptr->get_preference(_ptr, arg0);

        return _result != null ? new CefValueRef(_result) : null;
    }

    public ICefDictionaryValue? GetAllPreferences(int arg0)
    {
        var _result = _ptr->get_all_preferences(_ptr, arg0);

        return _result != null ? new CefDictionaryValueRef(_result) : null;
    }

    public int CanSetPreference(string? arg0)
    {
        var _result = _ptr->can_set_preference(_ptr, arg0);

        return _result;
    }

    public int SetPreference(string? arg0, ICefValue? arg1, string? arg2)
    {
        var _result = _ptr->set_preference(_ptr, arg0, arg1 is null ? null : arg1.NativePtr, arg2);

        return _result;
    }

    public ICefRegistration? AddPreferenceObserver(string? arg0, ICefPreferenceObserver? arg1)
    {
        var _result = _ptr->add_preference_observer(_ptr, arg0, arg1 is null ? null : arg1.NativePtr);

        return _result != null ? new CefRegistrationRef(_result) : null;
    }

    public _cef_base_ref_counted_t @base
    {
        get => _ptr->@base;
        set => _ptr->@base = value;
    }
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Wraps a library-owned instance of <c>_cef_preference_manager_t</c>.
/// Calls <c>add_ref</c> on construction and <c>release</c> on dispose
/// (for ref-counted types) or <c>del</c> on dispose (for scoped types).
/// </summary>
public unsafe partial class CefPreferenceManagerRef : CefBaseRefCountedRef, ICefPreferenceManager
{
    private readonly _cef_preference_manager_t* _ptr;

    public CefPreferenceManagerRef(_cef_preference_manager_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    _cef_preference_manager_t* ICefPreferenceManager.NativePtr => _ptr;


    public int HasPreference(string? arg0)
    {
        var _result = _ptr->has_preference(_ptr, arg0);

        return _result;
    }

    public ICefValue? GetPreference(string? arg0)
    {
        var _result = _ptr->get_preference(_ptr, arg0);

        return _result != null ? new CefValueRef(_result) : null;
    }

    public ICefDictionaryValue? GetAllPreferences(int arg0)
    {
        var _result = _ptr->get_all_preferences(_ptr, arg0);

        return _result != null ? new CefDictionaryValueRef(_result) : null;
    }

    public int CanSetPreference(string? arg0)
    {
        var _result = _ptr->can_set_preference(_ptr, arg0);

        return _result;
    }

    public int SetPreference(string? arg0, ICefValue? arg1, string? arg2)
    {
        var _result = _ptr->set_preference(_ptr, arg0, arg1 is null ? null : arg1.NativePtr, arg2);

        return _result;
    }

    public ICefRegistration? AddPreferenceObserver(string? arg0, ICefPreferenceObserver? arg1)
    {
        var _result = _ptr->add_preference_observer(_ptr, arg0, arg1 is null ? null : arg1.NativePtr);

        return _result != null ? new CefRegistrationRef(_result) : null;
    }

    public _cef_base_ref_counted_t @base
    {
        get => _ptr->@base;
        set => _ptr->@base = value;
    }
}
#endif