// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

public unsafe partial class CefRunFileDialogCallback : CefBaseRefCounted
{
    private readonly _cef_run_file_dialog_callback_t* _ptr;

    public CefRunFileDialogCallback(_cef_run_file_dialog_callback_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    internal _cef_run_file_dialog_callback_t* NativePtr => _ptr;

    public void OnFileDialogDismissed(_cef_string_list_t* arg0)
    {
        _ptr->on_file_dialog_dismissed(_ptr, arg0);
    }

        public _cef_base_ref_counted_t @base
        {
            get => _ptr->@base;
            set => _ptr->@base = value;
        }
}
