// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

public unsafe partial class CefRequestContext
{
    private readonly _cef_request_context_t* _ptr;

    public CefRequestContext(_cef_request_context_t* ptr)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    internal _cef_request_context_t* NativePtr => _ptr;

    public int IsSame(CefRequestContext? arg0)
    {
        var _result = _ptr->is_same(_ptr, arg0 is null ? null : arg0.NativePtr);

        return _result;
    }

    public int IsSharingWith(CefRequestContext? arg0)
    {
        var _result = _ptr->is_sharing_with(_ptr, arg0 is null ? null : arg0.NativePtr);

        return _result;
    }

    public int IsGlobal()
    {
        var _result = _ptr->is_global(_ptr);

        return _result;
    }

    public CefRequestContextHandler GetHandler()
    {
        var _result = _ptr->get_handler(_ptr);

        return _result != null ? new CefRequestContextHandler(_result) : null;
    }

    public string? GetCachePath()
    {
        var _result = _ptr->get_cache_path(_ptr);

        return CefStringRef.ToStringAndFree(_result);
    }

    public CefCookieManager GetCookieManager(CefCompletionCallback? arg0)
    {
        var _result = _ptr->get_cookie_manager(_ptr, arg0 is null ? null : arg0.NativePtr);

        return _result != null ? new CefCookieManager(_result) : null;
    }

    public int RegisterSchemeHandlerFactory(string? arg0, string? arg1, CefSchemeHandlerFactory? arg2)
    {
        fixed (char* _p0 = arg0)
        fixed (char* _p1 = arg1)
        {
            _cef_string_utf16_t _s0;
            CefStringRef.FillFromPinned(&_s0, _p0, arg0?.Length ?? 0);
            _cef_string_utf16_t _s1;
            CefStringRef.FillFromPinned(&_s1, _p1, arg1?.Length ?? 0);
            var _result = _ptr->register_scheme_handler_factory(_ptr, &_s0, &_s1, arg2 is null ? null : arg2.NativePtr);

            return _result;
        }
    }

    public int ClearSchemeHandlerFactories()
    {
        var _result = _ptr->clear_scheme_handler_factories(_ptr);

        return _result;
    }

    public void ClearCertificateExceptions(CefCompletionCallback? arg0)
    {
        _ptr->clear_certificate_exceptions(_ptr, arg0 is null ? null : arg0.NativePtr);
    }

    public void ClearHttpAuthCredentials(CefCompletionCallback? arg0)
    {
        _ptr->clear_http_auth_credentials(_ptr, arg0 is null ? null : arg0.NativePtr);
    }

    public void CloseAllConnections(CefCompletionCallback? arg0)
    {
        _ptr->close_all_connections(_ptr, arg0 is null ? null : arg0.NativePtr);
    }

    public void ResolveHost(string? arg0, CefResolveCallback? arg1)
    {
        fixed (char* _p0 = arg0)
        {
            _cef_string_utf16_t _s0;
            CefStringRef.FillFromPinned(&_s0, _p0, arg0?.Length ?? 0);
            _ptr->resolve_host(_ptr, &_s0, arg1 is null ? null : arg1.NativePtr);
        }
    }

    public CefMediaRouter GetMediaRouter(CefCompletionCallback? arg0)
    {
        var _result = _ptr->get_media_router(_ptr, arg0 is null ? null : arg0.NativePtr);

        return _result != null ? new CefMediaRouter(_result) : null;
    }

    public CefValue GetWebsiteSetting(string? arg0, string? arg1, cef_content_setting_types_t arg2)
    {
        fixed (char* _p0 = arg0)
        fixed (char* _p1 = arg1)
        {
            _cef_string_utf16_t _s0;
            CefStringRef.FillFromPinned(&_s0, _p0, arg0?.Length ?? 0);
            _cef_string_utf16_t _s1;
            CefStringRef.FillFromPinned(&_s1, _p1, arg1?.Length ?? 0);
            var _result = _ptr->get_website_setting(_ptr, &_s0, &_s1, arg2);

            return _result != null ? new CefValue(_result) : null;
        }
    }

    public void SetWebsiteSetting(string? arg0, string? arg1, cef_content_setting_types_t arg2, CefValue? arg3)
    {
        fixed (char* _p0 = arg0)
        fixed (char* _p1 = arg1)
        {
            _cef_string_utf16_t _s0;
            CefStringRef.FillFromPinned(&_s0, _p0, arg0?.Length ?? 0);
            _cef_string_utf16_t _s1;
            CefStringRef.FillFromPinned(&_s1, _p1, arg1?.Length ?? 0);
            _ptr->set_website_setting(_ptr, &_s0, &_s1, arg2, arg3 is null ? null : arg3.NativePtr);
        }
    }

    public cef_content_setting_values_t GetContentSetting(string? arg0, string? arg1, cef_content_setting_types_t arg2)
    {
        fixed (char* _p0 = arg0)
        fixed (char* _p1 = arg1)
        {
            _cef_string_utf16_t _s0;
            CefStringRef.FillFromPinned(&_s0, _p0, arg0?.Length ?? 0);
            _cef_string_utf16_t _s1;
            CefStringRef.FillFromPinned(&_s1, _p1, arg1?.Length ?? 0);
            var _result = _ptr->get_content_setting(_ptr, &_s0, &_s1, arg2);

            return _result;
        }
    }

    public void SetContentSetting(string? arg0, string? arg1, cef_content_setting_types_t arg2, cef_content_setting_values_t arg3)
    {
        fixed (char* _p0 = arg0)
        fixed (char* _p1 = arg1)
        {
            _cef_string_utf16_t _s0;
            CefStringRef.FillFromPinned(&_s0, _p0, arg0?.Length ?? 0);
            _cef_string_utf16_t _s1;
            CefStringRef.FillFromPinned(&_s1, _p1, arg1?.Length ?? 0);
            _ptr->set_content_setting(_ptr, &_s0, &_s1, arg2, arg3);
        }
    }

    public void SetChromeColorScheme(cef_color_variant_t arg0, uint arg1)
    {
        _ptr->set_chrome_color_scheme(_ptr, arg0, arg1);
    }

    public cef_color_variant_t GetChromeColorSchemeMode()
    {
        var _result = _ptr->get_chrome_color_scheme_mode(_ptr);

        return _result;
    }

    public uint GetChromeColorSchemeColor()
    {
        var _result = _ptr->get_chrome_color_scheme_color(_ptr);

        return _result;
    }

    public cef_color_variant_t GetChromeColorSchemeVariant()
    {
        var _result = _ptr->get_chrome_color_scheme_variant(_ptr);

        return _result;
    }

    public CefRegistration AddSettingObserver(CefSettingObserver? arg0)
    {
        var _result = _ptr->add_setting_observer(_ptr, arg0 is null ? null : arg0.NativePtr);

        return _result != null ? new CefRegistration(_result) : null;
    }

    public void ClearHttpCache(CefCompletionCallback? arg0)
    {
        _ptr->clear_http_cache(_ptr, arg0 is null ? null : arg0.NativePtr);
    }

        public _cef_preference_manager_t @base
        {
            get => _ptr->@base;
            set => _ptr->@base = value;
        }
}
