#if OS_WIN
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Wraps a library-owned instance of <c>_cef_render_handler_t</c>.
/// Calls <c>add_ref</c> on construction and <c>release</c> on dispose
/// (for ref-counted types) or <c>del</c> on dispose (for scoped types).
/// </summary>
public unsafe partial class CefRenderHandlerRef : CefBaseRefCountedRef, ICefRenderHandler
{
    private readonly _cef_render_handler_t* _ptr;

    public CefRenderHandlerRef(_cef_render_handler_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    _cef_render_handler_t* ICefRenderHandler.NativePtr => _ptr;


    public ICefAccessibilityHandler? GetAccessibilityHandler()
    {
        var _result = _ptr->get_accessibility_handler(_ptr);

        return _result != null ? new CefAccessibilityHandlerRef(_result) : null;
    }

    public int GetRootScreenRect(ICefBrowser? arg0, ICefRect? arg1)
    {
        var _result = _ptr->get_root_screen_rect(_ptr, arg0 is null ? null : arg0.NativePtr, arg1 is null ? null : arg1.NativePtr);

        return _result;
    }

    public void GetViewRect(ICefBrowser? arg0, ICefRect? arg1)
    {
        _ptr->get_view_rect(_ptr, arg0 is null ? null : arg0.NativePtr, arg1 is null ? null : arg1.NativePtr);
    }

    public int GetScreenPoint(ICefBrowser? arg0, int arg1, int arg2, int* arg3, int* arg4)
    {
        var _result = _ptr->get_screen_point(_ptr, arg0 is null ? null : arg0.NativePtr, arg1, arg2, arg3, arg4);

        return _result;
    }

    public int GetScreenInfo(ICefBrowser? arg0, ICefScreenInfo? arg1)
    {
        var _result = _ptr->get_screen_info(_ptr, arg0 is null ? null : arg0.NativePtr, arg1 is null ? null : arg1.NativePtr);

        return _result;
    }

    public void OnPopupShow(ICefBrowser? arg0, int arg1)
    {
        _ptr->on_popup_show(_ptr, arg0 is null ? null : arg0.NativePtr, arg1);
    }

    public void OnPopupSize(ICefBrowser? arg0, ICefRect? arg1)
    {
        _ptr->on_popup_size(_ptr, arg0 is null ? null : arg0.NativePtr, arg1 is null ? null : arg1.NativePtr);
    }

    public void OnPaint(ICefBrowser? arg0, cef_paint_element_type_t arg1, nuint arg2, ICefRect? arg3, void* arg4, int arg5, int arg6)
    {
        _ptr->on_paint(_ptr, arg0 is null ? null : arg0.NativePtr, arg1, arg2, arg3 is null ? null : arg3.NativePtr, arg4, arg5, arg6);
    }

    public void OnAcceleratedPaint(ICefBrowser? arg0, cef_paint_element_type_t arg1, nuint arg2, ICefRect? arg3, ICefAcceleratedPaintInfo? arg4)
    {
        _ptr->on_accelerated_paint(_ptr, arg0 is null ? null : arg0.NativePtr, arg1, arg2, arg3 is null ? null : arg3.NativePtr, arg4 is null ? null : arg4.NativePtr);
    }

    public void GetTouchHandleSize(ICefBrowser? arg0, cef_horizontal_alignment_t arg1, ICefSize? arg2)
    {
        _ptr->get_touch_handle_size(_ptr, arg0 is null ? null : arg0.NativePtr, arg1, arg2 is null ? null : arg2.NativePtr);
    }

    public void OnTouchHandleStateChanged(ICefBrowser? arg0, ICefTouchHandleState? arg1)
    {
        _ptr->on_touch_handle_state_changed(_ptr, arg0 is null ? null : arg0.NativePtr, arg1 is null ? null : arg1.NativePtr);
    }

    public int StartDragging(ICefBrowser? arg0, ICefDragData? arg1, cef_drag_operations_mask_t arg2, int arg3, int arg4)
    {
        var _result = _ptr->start_dragging(_ptr, arg0 is null ? null : arg0.NativePtr, arg1 is null ? null : arg1.NativePtr, arg2, arg3, arg4);

        return _result;
    }

    public void UpdateDragCursor(ICefBrowser? arg0, cef_drag_operations_mask_t arg1)
    {
        _ptr->update_drag_cursor(_ptr, arg0 is null ? null : arg0.NativePtr, arg1);
    }

    public void OnScrollOffsetChanged(ICefBrowser? arg0, double arg1, double arg2)
    {
        _ptr->on_scroll_offset_changed(_ptr, arg0 is null ? null : arg0.NativePtr, arg1, arg2);
    }

    public void OnImeCompositionRangeChanged(ICefBrowser? arg0, ICefRange? arg1, nuint arg2, ICefRect? arg3)
    {
        _ptr->on_ime_composition_range_changed(_ptr, arg0 is null ? null : arg0.NativePtr, arg1 is null ? null : arg1.NativePtr, arg2, arg3 is null ? null : arg3.NativePtr);
    }

    public void OnTextSelectionChanged(ICefBrowser? arg0, string? arg1, ICefRange? arg2)
    {
        fixed (char* _p1 = arg1)
        {
            _cef_string_utf16_t _s1;
            CefStringRef.FillFromPinned(&_s1, _p1, arg1?.Length ?? 0);
            _ptr->on_text_selection_changed(_ptr, arg0 is null ? null : arg0.NativePtr, &_s1, arg2 is null ? null : arg2.NativePtr);
        }
    }

    public void OnVirtualKeyboardRequested(ICefBrowser? arg0, cef_text_input_mode_t arg1)
    {
        _ptr->on_virtual_keyboard_requested(_ptr, arg0 is null ? null : arg0.NativePtr, arg1);
    }

    public _cef_base_ref_counted_t @base
    {
        get => _ptr->@base;
        set => _ptr->@base = value;
    }
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Wraps a library-owned instance of <c>_cef_render_handler_t</c>.
/// Calls <c>add_ref</c> on construction and <c>release</c> on dispose
/// (for ref-counted types) or <c>del</c> on dispose (for scoped types).
/// </summary>
public unsafe partial class CefRenderHandlerRef : CefBaseRefCountedRef, ICefRenderHandler
{
    private readonly _cef_render_handler_t* _ptr;

    public CefRenderHandlerRef(_cef_render_handler_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    _cef_render_handler_t* ICefRenderHandler.NativePtr => _ptr;


    public ICefAccessibilityHandler? GetAccessibilityHandler()
    {
        var _result = _ptr->get_accessibility_handler(_ptr);

        return _result != null ? new CefAccessibilityHandlerRef(_result) : null;
    }

    public int GetRootScreenRect(ICefBrowser? arg0, ICefRect? arg1)
    {
        var _result = _ptr->get_root_screen_rect(_ptr, arg0 is null ? null : arg0.NativePtr, arg1 is null ? null : arg1.NativePtr);

        return _result;
    }

    public void GetViewRect(ICefBrowser? arg0, ICefRect? arg1)
    {
        _ptr->get_view_rect(_ptr, arg0 is null ? null : arg0.NativePtr, arg1 is null ? null : arg1.NativePtr);
    }

    public int GetScreenPoint(ICefBrowser? arg0, int arg1, int arg2, int* arg3, int* arg4)
    {
        var _result = _ptr->get_screen_point(_ptr, arg0 is null ? null : arg0.NativePtr, arg1, arg2, arg3, arg4);

        return _result;
    }

    public int GetScreenInfo(ICefBrowser? arg0, ICefScreenInfo? arg1)
    {
        var _result = _ptr->get_screen_info(_ptr, arg0 is null ? null : arg0.NativePtr, arg1 is null ? null : arg1.NativePtr);

        return _result;
    }

    public void OnPopupShow(ICefBrowser? arg0, int arg1)
    {
        _ptr->on_popup_show(_ptr, arg0 is null ? null : arg0.NativePtr, arg1);
    }

    public void OnPopupSize(ICefBrowser? arg0, ICefRect? arg1)
    {
        _ptr->on_popup_size(_ptr, arg0 is null ? null : arg0.NativePtr, arg1 is null ? null : arg1.NativePtr);
    }

    public void OnPaint(ICefBrowser? arg0, cef_paint_element_type_t arg1, nuint arg2, ICefRect? arg3, void* arg4, int arg5, int arg6)
    {
        _ptr->on_paint(_ptr, arg0 is null ? null : arg0.NativePtr, arg1, arg2, arg3 is null ? null : arg3.NativePtr, arg4, arg5, arg6);
    }

    public void OnAcceleratedPaint(ICefBrowser? arg0, cef_paint_element_type_t arg1, nuint arg2, ICefRect? arg3, ICefAcceleratedPaintInfo? arg4)
    {
        _ptr->on_accelerated_paint(_ptr, arg0 is null ? null : arg0.NativePtr, arg1, arg2, arg3 is null ? null : arg3.NativePtr, arg4 is null ? null : arg4.NativePtr);
    }

    public void GetTouchHandleSize(ICefBrowser? arg0, cef_horizontal_alignment_t arg1, ICefSize? arg2)
    {
        _ptr->get_touch_handle_size(_ptr, arg0 is null ? null : arg0.NativePtr, arg1, arg2 is null ? null : arg2.NativePtr);
    }

    public void OnTouchHandleStateChanged(ICefBrowser? arg0, ICefTouchHandleState? arg1)
    {
        _ptr->on_touch_handle_state_changed(_ptr, arg0 is null ? null : arg0.NativePtr, arg1 is null ? null : arg1.NativePtr);
    }

    public int StartDragging(ICefBrowser? arg0, ICefDragData? arg1, cef_drag_operations_mask_t arg2, int arg3, int arg4)
    {
        var _result = _ptr->start_dragging(_ptr, arg0 is null ? null : arg0.NativePtr, arg1 is null ? null : arg1.NativePtr, arg2, arg3, arg4);

        return _result;
    }

    public void UpdateDragCursor(ICefBrowser? arg0, cef_drag_operations_mask_t arg1)
    {
        _ptr->update_drag_cursor(_ptr, arg0 is null ? null : arg0.NativePtr, arg1);
    }

    public void OnScrollOffsetChanged(ICefBrowser? arg0, double arg1, double arg2)
    {
        _ptr->on_scroll_offset_changed(_ptr, arg0 is null ? null : arg0.NativePtr, arg1, arg2);
    }

    public void OnImeCompositionRangeChanged(ICefBrowser? arg0, ICefRange? arg1, nuint arg2, ICefRect? arg3)
    {
        _ptr->on_ime_composition_range_changed(_ptr, arg0 is null ? null : arg0.NativePtr, arg1 is null ? null : arg1.NativePtr, arg2, arg3 is null ? null : arg3.NativePtr);
    }

    public void OnTextSelectionChanged(ICefBrowser? arg0, string? arg1, ICefRange? arg2)
    {
        _ptr->on_text_selection_changed(_ptr, arg0 is null ? null : arg0.NativePtr, arg1, arg2 is null ? null : arg2.NativePtr);
    }

    public void OnVirtualKeyboardRequested(ICefBrowser? arg0, cef_text_input_mode_t arg1)
    {
        _ptr->on_virtual_keyboard_requested(_ptr, arg0 is null ? null : arg0.NativePtr, arg1);
    }

    public _cef_base_ref_counted_t @base
    {
        get => _ptr->@base;
        set => _ptr->@base = value;
    }
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Wraps a library-owned instance of <c>_cef_render_handler_t</c>.
/// Calls <c>add_ref</c> on construction and <c>release</c> on dispose
/// (for ref-counted types) or <c>del</c> on dispose (for scoped types).
/// </summary>
public unsafe partial class CefRenderHandlerRef : CefBaseRefCountedRef, ICefRenderHandler
{
    private readonly _cef_render_handler_t* _ptr;

    public CefRenderHandlerRef(_cef_render_handler_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    _cef_render_handler_t* ICefRenderHandler.NativePtr => _ptr;


    public ICefAccessibilityHandler? GetAccessibilityHandler()
    {
        var _result = _ptr->get_accessibility_handler(_ptr);

        return _result != null ? new CefAccessibilityHandlerRef(_result) : null;
    }

    public int GetRootScreenRect(ICefBrowser? arg0, ICefRect? arg1)
    {
        var _result = _ptr->get_root_screen_rect(_ptr, arg0 is null ? null : arg0.NativePtr, arg1 is null ? null : arg1.NativePtr);

        return _result;
    }

    public void GetViewRect(ICefBrowser? arg0, ICefRect? arg1)
    {
        _ptr->get_view_rect(_ptr, arg0 is null ? null : arg0.NativePtr, arg1 is null ? null : arg1.NativePtr);
    }

    public int GetScreenPoint(ICefBrowser? arg0, int arg1, int arg2, int* arg3, int* arg4)
    {
        var _result = _ptr->get_screen_point(_ptr, arg0 is null ? null : arg0.NativePtr, arg1, arg2, arg3, arg4);

        return _result;
    }

    public int GetScreenInfo(ICefBrowser? arg0, ICefScreenInfo? arg1)
    {
        var _result = _ptr->get_screen_info(_ptr, arg0 is null ? null : arg0.NativePtr, arg1 is null ? null : arg1.NativePtr);

        return _result;
    }

    public void OnPopupShow(ICefBrowser? arg0, int arg1)
    {
        _ptr->on_popup_show(_ptr, arg0 is null ? null : arg0.NativePtr, arg1);
    }

    public void OnPopupSize(ICefBrowser? arg0, ICefRect? arg1)
    {
        _ptr->on_popup_size(_ptr, arg0 is null ? null : arg0.NativePtr, arg1 is null ? null : arg1.NativePtr);
    }

    public void OnPaint(ICefBrowser? arg0, cef_paint_element_type_t arg1, nuint arg2, ICefRect? arg3, void* arg4, int arg5, int arg6)
    {
        _ptr->on_paint(_ptr, arg0 is null ? null : arg0.NativePtr, arg1, arg2, arg3 is null ? null : arg3.NativePtr, arg4, arg5, arg6);
    }

    public void OnAcceleratedPaint(ICefBrowser? arg0, cef_paint_element_type_t arg1, nuint arg2, ICefRect? arg3, ICefAcceleratedPaintInfo? arg4)
    {
        _ptr->on_accelerated_paint(_ptr, arg0 is null ? null : arg0.NativePtr, arg1, arg2, arg3 is null ? null : arg3.NativePtr, arg4 is null ? null : arg4.NativePtr);
    }

    public void GetTouchHandleSize(ICefBrowser? arg0, cef_horizontal_alignment_t arg1, ICefSize? arg2)
    {
        _ptr->get_touch_handle_size(_ptr, arg0 is null ? null : arg0.NativePtr, arg1, arg2 is null ? null : arg2.NativePtr);
    }

    public void OnTouchHandleStateChanged(ICefBrowser? arg0, ICefTouchHandleState? arg1)
    {
        _ptr->on_touch_handle_state_changed(_ptr, arg0 is null ? null : arg0.NativePtr, arg1 is null ? null : arg1.NativePtr);
    }

    public int StartDragging(ICefBrowser? arg0, ICefDragData? arg1, cef_drag_operations_mask_t arg2, int arg3, int arg4)
    {
        var _result = _ptr->start_dragging(_ptr, arg0 is null ? null : arg0.NativePtr, arg1 is null ? null : arg1.NativePtr, arg2, arg3, arg4);

        return _result;
    }

    public void UpdateDragCursor(ICefBrowser? arg0, cef_drag_operations_mask_t arg1)
    {
        _ptr->update_drag_cursor(_ptr, arg0 is null ? null : arg0.NativePtr, arg1);
    }

    public void OnScrollOffsetChanged(ICefBrowser? arg0, double arg1, double arg2)
    {
        _ptr->on_scroll_offset_changed(_ptr, arg0 is null ? null : arg0.NativePtr, arg1, arg2);
    }

    public void OnImeCompositionRangeChanged(ICefBrowser? arg0, ICefRange? arg1, nuint arg2, ICefRect? arg3)
    {
        _ptr->on_ime_composition_range_changed(_ptr, arg0 is null ? null : arg0.NativePtr, arg1 is null ? null : arg1.NativePtr, arg2, arg3 is null ? null : arg3.NativePtr);
    }

    public void OnTextSelectionChanged(ICefBrowser? arg0, string? arg1, ICefRange? arg2)
    {
        _ptr->on_text_selection_changed(_ptr, arg0 is null ? null : arg0.NativePtr, arg1, arg2 is null ? null : arg2.NativePtr);
    }

    public void OnVirtualKeyboardRequested(ICefBrowser? arg0, cef_text_input_mode_t arg1)
    {
        _ptr->on_virtual_keyboard_requested(_ptr, arg0 is null ? null : arg0.NativePtr, arg1);
    }

    public _cef_base_ref_counted_t @base
    {
        get => _ptr->@base;
        set => _ptr->@base = value;
    }
}
#endif