#if OS_WIN
// <auto-generated/>
#nullable enable

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using RawCef.Native;

namespace RawCef;

/// <summary>
/// Abstract base class for client-side implementations of <c>_cef_resource_request_handler_t</c>.
/// Subclass this to implement a custom CefResourceRequestHandler.
/// </summary>
public unsafe abstract partial class CefResourceRequestHandler : CefBaseRefCounted, ICefResourceRequestHandler
{
    private _cef_resource_request_handler_t* _typedPtr;

    protected CefResourceRequestHandler() : this((nuint)sizeof(_cef_resource_request_handler_t))
    {
    }

    protected CefResourceRequestHandler(nuint structSize) : base(structSize)
    {
        _typedPtr = (_cef_resource_request_handler_t*)NativePtr;
        InitializeNativeStruct();
    }

    _cef_resource_request_handler_t* ICefResourceRequestHandler.NativePtr => _typedPtr;

    /// <inheritdoc />
    protected override void InitializeNativeStruct()
    {
        base.InitializeNativeStruct();

        _typedPtr->get_cookie_access_filter = &Bridge_GetCookieAccessFilter;
        _typedPtr->on_before_resource_load = &Bridge_OnBeforeResourceLoad;
        _typedPtr->get_resource_handler = &Bridge_GetResourceHandler;
        _typedPtr->on_resource_redirect = &Bridge_OnResourceRedirect;
        _typedPtr->on_resource_response = &Bridge_OnResourceResponse;
        _typedPtr->get_resource_response_filter = &Bridge_GetResourceResponseFilter;
        _typedPtr->on_resource_load_complete = &Bridge_OnResourceLoadComplete;
        _typedPtr->on_protocol_execution = &Bridge_OnProtocolExecution;
    }


    /// <summary>
    /// Implement the <c>get_cookie_access_filter</c> callback.
    /// </summary>
    public abstract ICefCookieAccessFilter? GetCookieAccessFilter(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2);

    /// <summary>
    /// Implement the <c>on_before_resource_load</c> callback.
    /// </summary>
    public abstract cef_return_value_t OnBeforeResourceLoad(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefCallback? arg3);

    /// <summary>
    /// Implement the <c>get_resource_handler</c> callback.
    /// </summary>
    public abstract ICefResourceHandler? GetResourceHandler(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2);

    /// <summary>
    /// Implement the <c>on_resource_redirect</c> callback.
    /// </summary>
    public abstract void OnResourceRedirect(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefResponse? arg3, out string? arg4);

    /// <summary>
    /// Implement the <c>on_resource_response</c> callback.
    /// </summary>
    public abstract int OnResourceResponse(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefResponse? arg3);

    /// <summary>
    /// Implement the <c>get_resource_response_filter</c> callback.
    /// </summary>
    public abstract ICefResponseFilter? GetResourceResponseFilter(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefResponse? arg3);

    /// <summary>
    /// Implement the <c>on_resource_load_complete</c> callback.
    /// </summary>
    public abstract void OnResourceLoadComplete(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefResponse? arg3, cef_urlrequest_status_t arg4, long arg5);

    /// <summary>
    /// Implement the <c>on_protocol_execution</c> callback.
    /// </summary>
    public abstract void OnProtocolExecution(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, int* arg3);

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_cookie_access_filter_t* Bridge_GetCookieAccessFilter(_cef_resource_request_handler_t* self, _cef_browser_t* arg0, _cef_frame_t* arg1, _cef_request_t* arg2)
    {
        try
        {
            var _m = GetManaged<CefResourceRequestHandler>(self);

            var _a0 = arg0 != null ? new CefBrowserRef(arg0) : null;
            var _a1 = arg1 != null ? new CefFrameRef(arg1) : null;
            var _a2 = arg2 != null ? new CefRequestRef(arg2) : null;
            var _result = _m.GetCookieAccessFilter(_a0, _a1, _a2);

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static cef_return_value_t Bridge_OnBeforeResourceLoad(_cef_resource_request_handler_t* self, _cef_browser_t* arg0, _cef_frame_t* arg1, _cef_request_t* arg2, _cef_callback_t* arg3)
    {
        try
        {
            var _m = GetManaged<CefResourceRequestHandler>(self);

            var _a0 = arg0 != null ? new CefBrowserRef(arg0) : null;
            var _a1 = arg1 != null ? new CefFrameRef(arg1) : null;
            var _a2 = arg2 != null ? new CefRequestRef(arg2) : null;
            var _a3 = arg3 != null ? new CefCallbackRef(arg3) : null;
            var _result = _m.OnBeforeResourceLoad(_a0, _a1, _a2, _a3);

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_resource_handler_t* Bridge_GetResourceHandler(_cef_resource_request_handler_t* self, _cef_browser_t* arg0, _cef_frame_t* arg1, _cef_request_t* arg2)
    {
        try
        {
            var _m = GetManaged<CefResourceRequestHandler>(self);

            var _a0 = arg0 != null ? new CefBrowserRef(arg0) : null;
            var _a1 = arg1 != null ? new CefFrameRef(arg1) : null;
            var _a2 = arg2 != null ? new CefRequestRef(arg2) : null;
            var _result = _m.GetResourceHandler(_a0, _a1, _a2);

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_OnResourceRedirect(_cef_resource_request_handler_t* self, _cef_browser_t* arg0, _cef_frame_t* arg1, _cef_request_t* arg2, _cef_response_t* arg3, _cef_string_utf16_t* arg4)
    {
        try
        {
            var _m = GetManaged<CefResourceRequestHandler>(self);

            var _a0 = arg0 != null ? new CefBrowserRef(arg0) : null;
            var _a1 = arg1 != null ? new CefFrameRef(arg1) : null;
            var _a2 = arg2 != null ? new CefRequestRef(arg2) : null;
            var _a3 = arg3 != null ? new CefResponseRef(arg3) : null;
            string? _out4 = null;
            if (arg4 != null) _out4 = CefStringRef.ToStringAndFree(arg4);
            _m.OnResourceRedirect(_a0, _a1, _a2, _a3, out _out4);
            if (arg4 != null)
            {
                fixed (char* _p4 = _out4)
                    CefUnsafe.StringUtf16Set((ushort*)_p4, (nuint)(_out4?.Length ?? 0), arg4, copy: 1);
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_OnResourceResponse(_cef_resource_request_handler_t* self, _cef_browser_t* arg0, _cef_frame_t* arg1, _cef_request_t* arg2, _cef_response_t* arg3)
    {
        try
        {
            var _m = GetManaged<CefResourceRequestHandler>(self);

            var _a0 = arg0 != null ? new CefBrowserRef(arg0) : null;
            var _a1 = arg1 != null ? new CefFrameRef(arg1) : null;
            var _a2 = arg2 != null ? new CefRequestRef(arg2) : null;
            var _a3 = arg3 != null ? new CefResponseRef(arg3) : null;
            var _result = _m.OnResourceResponse(_a0, _a1, _a2, _a3);

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_response_filter_t* Bridge_GetResourceResponseFilter(_cef_resource_request_handler_t* self, _cef_browser_t* arg0, _cef_frame_t* arg1, _cef_request_t* arg2, _cef_response_t* arg3)
    {
        try
        {
            var _m = GetManaged<CefResourceRequestHandler>(self);

            var _a0 = arg0 != null ? new CefBrowserRef(arg0) : null;
            var _a1 = arg1 != null ? new CefFrameRef(arg1) : null;
            var _a2 = arg2 != null ? new CefRequestRef(arg2) : null;
            var _a3 = arg3 != null ? new CefResponseRef(arg3) : null;
            var _result = _m.GetResourceResponseFilter(_a0, _a1, _a2, _a3);

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_OnResourceLoadComplete(_cef_resource_request_handler_t* self, _cef_browser_t* arg0, _cef_frame_t* arg1, _cef_request_t* arg2, _cef_response_t* arg3, cef_urlrequest_status_t arg4, long arg5)
    {
        try
        {
            var _m = GetManaged<CefResourceRequestHandler>(self);

            var _a0 = arg0 != null ? new CefBrowserRef(arg0) : null;
            var _a1 = arg1 != null ? new CefFrameRef(arg1) : null;
            var _a2 = arg2 != null ? new CefRequestRef(arg2) : null;
            var _a3 = arg3 != null ? new CefResponseRef(arg3) : null;
            var _a4 = arg4;
            var _a5 = arg5;
            _m.OnResourceLoadComplete(_a0, _a1, _a2, _a3, _a4, _a5);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_OnProtocolExecution(_cef_resource_request_handler_t* self, _cef_browser_t* arg0, _cef_frame_t* arg1, _cef_request_t* arg2, int* arg3)
    {
        try
        {
            var _m = GetManaged<CefResourceRequestHandler>(self);

            var _a0 = arg0 != null ? new CefBrowserRef(arg0) : null;
            var _a1 = arg1 != null ? new CefFrameRef(arg1) : null;
            var _a2 = arg2 != null ? new CefRequestRef(arg2) : null;
            var _a3 = arg3;
            _m.OnProtocolExecution(_a0, _a1, _a2, _a3);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using RawCef.Native;

namespace RawCef;

/// <summary>
/// Abstract base class for client-side implementations of <c>_cef_resource_request_handler_t</c>.
/// Subclass this to implement a custom CefResourceRequestHandler.
/// </summary>
public unsafe abstract partial class CefResourceRequestHandler : CefBaseRefCounted, ICefResourceRequestHandler
{
    private _cef_resource_request_handler_t* _typedPtr;

    protected CefResourceRequestHandler() : this((nuint)sizeof(_cef_resource_request_handler_t))
    {
    }

    protected CefResourceRequestHandler(nuint structSize) : base(structSize)
    {
        _typedPtr = (_cef_resource_request_handler_t*)NativePtr;
        InitializeNativeStruct();
    }

    _cef_resource_request_handler_t* ICefResourceRequestHandler.NativePtr => _typedPtr;

    /// <inheritdoc />
    protected override void InitializeNativeStruct()
    {
        base.InitializeNativeStruct();

        _typedPtr->get_cookie_access_filter = &Bridge_GetCookieAccessFilter;
        _typedPtr->on_before_resource_load = &Bridge_OnBeforeResourceLoad;
        _typedPtr->get_resource_handler = &Bridge_GetResourceHandler;
        _typedPtr->on_resource_redirect = &Bridge_OnResourceRedirect;
        _typedPtr->on_resource_response = &Bridge_OnResourceResponse;
        _typedPtr->get_resource_response_filter = &Bridge_GetResourceResponseFilter;
        _typedPtr->on_resource_load_complete = &Bridge_OnResourceLoadComplete;
        _typedPtr->on_protocol_execution = &Bridge_OnProtocolExecution;
    }


    /// <summary>
    /// Implement the <c>get_cookie_access_filter</c> callback.
    /// </summary>
    public abstract ICefCookieAccessFilter? GetCookieAccessFilter(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2);

    /// <summary>
    /// Implement the <c>on_before_resource_load</c> callback.
    /// </summary>
    public abstract cef_return_value_t OnBeforeResourceLoad(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefCallback? arg3);

    /// <summary>
    /// Implement the <c>get_resource_handler</c> callback.
    /// </summary>
    public abstract ICefResourceHandler? GetResourceHandler(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2);

    /// <summary>
    /// Implement the <c>on_resource_redirect</c> callback.
    /// </summary>
    public abstract void OnResourceRedirect(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefResponse? arg3, out string? arg4);

    /// <summary>
    /// Implement the <c>on_resource_response</c> callback.
    /// </summary>
    public abstract int OnResourceResponse(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefResponse? arg3);

    /// <summary>
    /// Implement the <c>get_resource_response_filter</c> callback.
    /// </summary>
    public abstract ICefResponseFilter? GetResourceResponseFilter(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefResponse? arg3);

    /// <summary>
    /// Implement the <c>on_resource_load_complete</c> callback.
    /// </summary>
    public abstract void OnResourceLoadComplete(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefResponse? arg3, cef_urlrequest_status_t arg4, long arg5);

    /// <summary>
    /// Implement the <c>on_protocol_execution</c> callback.
    /// </summary>
    public abstract void OnProtocolExecution(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, int* arg3);

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_cookie_access_filter_t* Bridge_GetCookieAccessFilter(_cef_resource_request_handler_t* self, _cef_browser_t* arg0, _cef_frame_t* arg1, _cef_request_t* arg2)
    {
        try
        {
            var _m = GetManaged<CefResourceRequestHandler>(self);

            var _a0 = arg0 != null ? new CefBrowserRef(arg0) : null;
            var _a1 = arg1 != null ? new CefFrameRef(arg1) : null;
            var _a2 = arg2 != null ? new CefRequestRef(arg2) : null;
            var _result = _m.GetCookieAccessFilter(_a0, _a1, _a2);

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static cef_return_value_t Bridge_OnBeforeResourceLoad(_cef_resource_request_handler_t* self, _cef_browser_t* arg0, _cef_frame_t* arg1, _cef_request_t* arg2, _cef_callback_t* arg3)
    {
        try
        {
            var _m = GetManaged<CefResourceRequestHandler>(self);

            var _a0 = arg0 != null ? new CefBrowserRef(arg0) : null;
            var _a1 = arg1 != null ? new CefFrameRef(arg1) : null;
            var _a2 = arg2 != null ? new CefRequestRef(arg2) : null;
            var _a3 = arg3 != null ? new CefCallbackRef(arg3) : null;
            var _result = _m.OnBeforeResourceLoad(_a0, _a1, _a2, _a3);

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_resource_handler_t* Bridge_GetResourceHandler(_cef_resource_request_handler_t* self, _cef_browser_t* arg0, _cef_frame_t* arg1, _cef_request_t* arg2)
    {
        try
        {
            var _m = GetManaged<CefResourceRequestHandler>(self);

            var _a0 = arg0 != null ? new CefBrowserRef(arg0) : null;
            var _a1 = arg1 != null ? new CefFrameRef(arg1) : null;
            var _a2 = arg2 != null ? new CefRequestRef(arg2) : null;
            var _result = _m.GetResourceHandler(_a0, _a1, _a2);

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_OnResourceRedirect(_cef_resource_request_handler_t* self, _cef_browser_t* arg0, _cef_frame_t* arg1, _cef_request_t* arg2, _cef_response_t* arg3, _cef_string_utf16_t* arg4)
    {
        try
        {
            var _m = GetManaged<CefResourceRequestHandler>(self);

            var _a0 = arg0 != null ? new CefBrowserRef(arg0) : null;
            var _a1 = arg1 != null ? new CefFrameRef(arg1) : null;
            var _a2 = arg2 != null ? new CefRequestRef(arg2) : null;
            var _a3 = arg3 != null ? new CefResponseRef(arg3) : null;
            string? _out4 = null;
            if (arg4 != null) _out4 = CefStringRef.ToStringAndFree(arg4);
            _m.OnResourceRedirect(_a0, _a1, _a2, _a3, out _out4);
            if (arg4 != null)
            {
                fixed (char* _p4 = _out4)
                    CefUnsafe.StringUtf16Set((ushort*)_p4, (nuint)(_out4?.Length ?? 0), arg4, copy: 1);
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_OnResourceResponse(_cef_resource_request_handler_t* self, _cef_browser_t* arg0, _cef_frame_t* arg1, _cef_request_t* arg2, _cef_response_t* arg3)
    {
        try
        {
            var _m = GetManaged<CefResourceRequestHandler>(self);

            var _a0 = arg0 != null ? new CefBrowserRef(arg0) : null;
            var _a1 = arg1 != null ? new CefFrameRef(arg1) : null;
            var _a2 = arg2 != null ? new CefRequestRef(arg2) : null;
            var _a3 = arg3 != null ? new CefResponseRef(arg3) : null;
            var _result = _m.OnResourceResponse(_a0, _a1, _a2, _a3);

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_response_filter_t* Bridge_GetResourceResponseFilter(_cef_resource_request_handler_t* self, _cef_browser_t* arg0, _cef_frame_t* arg1, _cef_request_t* arg2, _cef_response_t* arg3)
    {
        try
        {
            var _m = GetManaged<CefResourceRequestHandler>(self);

            var _a0 = arg0 != null ? new CefBrowserRef(arg0) : null;
            var _a1 = arg1 != null ? new CefFrameRef(arg1) : null;
            var _a2 = arg2 != null ? new CefRequestRef(arg2) : null;
            var _a3 = arg3 != null ? new CefResponseRef(arg3) : null;
            var _result = _m.GetResourceResponseFilter(_a0, _a1, _a2, _a3);

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_OnResourceLoadComplete(_cef_resource_request_handler_t* self, _cef_browser_t* arg0, _cef_frame_t* arg1, _cef_request_t* arg2, _cef_response_t* arg3, cef_urlrequest_status_t arg4, long arg5)
    {
        try
        {
            var _m = GetManaged<CefResourceRequestHandler>(self);

            var _a0 = arg0 != null ? new CefBrowserRef(arg0) : null;
            var _a1 = arg1 != null ? new CefFrameRef(arg1) : null;
            var _a2 = arg2 != null ? new CefRequestRef(arg2) : null;
            var _a3 = arg3 != null ? new CefResponseRef(arg3) : null;
            var _a4 = arg4;
            var _a5 = arg5;
            _m.OnResourceLoadComplete(_a0, _a1, _a2, _a3, _a4, _a5);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_OnProtocolExecution(_cef_resource_request_handler_t* self, _cef_browser_t* arg0, _cef_frame_t* arg1, _cef_request_t* arg2, int* arg3)
    {
        try
        {
            var _m = GetManaged<CefResourceRequestHandler>(self);

            var _a0 = arg0 != null ? new CefBrowserRef(arg0) : null;
            var _a1 = arg1 != null ? new CefFrameRef(arg1) : null;
            var _a2 = arg2 != null ? new CefRequestRef(arg2) : null;
            var _a3 = arg3;
            _m.OnProtocolExecution(_a0, _a1, _a2, _a3);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using RawCef.Native;

namespace RawCef;

/// <summary>
/// Abstract base class for client-side implementations of <c>_cef_resource_request_handler_t</c>.
/// Subclass this to implement a custom CefResourceRequestHandler.
/// </summary>
public unsafe abstract partial class CefResourceRequestHandler : CefBaseRefCounted, ICefResourceRequestHandler
{
    private _cef_resource_request_handler_t* _typedPtr;

    protected CefResourceRequestHandler() : this((nuint)sizeof(_cef_resource_request_handler_t))
    {
    }

    protected CefResourceRequestHandler(nuint structSize) : base(structSize)
    {
        _typedPtr = (_cef_resource_request_handler_t*)NativePtr;
        InitializeNativeStruct();
    }

    _cef_resource_request_handler_t* ICefResourceRequestHandler.NativePtr => _typedPtr;

    /// <inheritdoc />
    protected override void InitializeNativeStruct()
    {
        base.InitializeNativeStruct();

        _typedPtr->get_cookie_access_filter = &Bridge_GetCookieAccessFilter;
        _typedPtr->on_before_resource_load = &Bridge_OnBeforeResourceLoad;
        _typedPtr->get_resource_handler = &Bridge_GetResourceHandler;
        _typedPtr->on_resource_redirect = &Bridge_OnResourceRedirect;
        _typedPtr->on_resource_response = &Bridge_OnResourceResponse;
        _typedPtr->get_resource_response_filter = &Bridge_GetResourceResponseFilter;
        _typedPtr->on_resource_load_complete = &Bridge_OnResourceLoadComplete;
        _typedPtr->on_protocol_execution = &Bridge_OnProtocolExecution;
    }


    /// <summary>
    /// Implement the <c>get_cookie_access_filter</c> callback.
    /// </summary>
    public abstract ICefCookieAccessFilter? GetCookieAccessFilter(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2);

    /// <summary>
    /// Implement the <c>on_before_resource_load</c> callback.
    /// </summary>
    public abstract cef_return_value_t OnBeforeResourceLoad(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefCallback? arg3);

    /// <summary>
    /// Implement the <c>get_resource_handler</c> callback.
    /// </summary>
    public abstract ICefResourceHandler? GetResourceHandler(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2);

    /// <summary>
    /// Implement the <c>on_resource_redirect</c> callback.
    /// </summary>
    public abstract void OnResourceRedirect(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefResponse? arg3, out string? arg4);

    /// <summary>
    /// Implement the <c>on_resource_response</c> callback.
    /// </summary>
    public abstract int OnResourceResponse(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefResponse? arg3);

    /// <summary>
    /// Implement the <c>get_resource_response_filter</c> callback.
    /// </summary>
    public abstract ICefResponseFilter? GetResourceResponseFilter(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefResponse? arg3);

    /// <summary>
    /// Implement the <c>on_resource_load_complete</c> callback.
    /// </summary>
    public abstract void OnResourceLoadComplete(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefResponse? arg3, cef_urlrequest_status_t arg4, long arg5);

    /// <summary>
    /// Implement the <c>on_protocol_execution</c> callback.
    /// </summary>
    public abstract void OnProtocolExecution(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, int* arg3);

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_cookie_access_filter_t* Bridge_GetCookieAccessFilter(_cef_resource_request_handler_t* self, _cef_browser_t* arg0, _cef_frame_t* arg1, _cef_request_t* arg2)
    {
        try
        {
            var _m = GetManaged<CefResourceRequestHandler>(self);

            var _a0 = arg0 != null ? new CefBrowserRef(arg0) : null;
            var _a1 = arg1 != null ? new CefFrameRef(arg1) : null;
            var _a2 = arg2 != null ? new CefRequestRef(arg2) : null;
            var _result = _m.GetCookieAccessFilter(_a0, _a1, _a2);

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static cef_return_value_t Bridge_OnBeforeResourceLoad(_cef_resource_request_handler_t* self, _cef_browser_t* arg0, _cef_frame_t* arg1, _cef_request_t* arg2, _cef_callback_t* arg3)
    {
        try
        {
            var _m = GetManaged<CefResourceRequestHandler>(self);

            var _a0 = arg0 != null ? new CefBrowserRef(arg0) : null;
            var _a1 = arg1 != null ? new CefFrameRef(arg1) : null;
            var _a2 = arg2 != null ? new CefRequestRef(arg2) : null;
            var _a3 = arg3 != null ? new CefCallbackRef(arg3) : null;
            var _result = _m.OnBeforeResourceLoad(_a0, _a1, _a2, _a3);

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_resource_handler_t* Bridge_GetResourceHandler(_cef_resource_request_handler_t* self, _cef_browser_t* arg0, _cef_frame_t* arg1, _cef_request_t* arg2)
    {
        try
        {
            var _m = GetManaged<CefResourceRequestHandler>(self);

            var _a0 = arg0 != null ? new CefBrowserRef(arg0) : null;
            var _a1 = arg1 != null ? new CefFrameRef(arg1) : null;
            var _a2 = arg2 != null ? new CefRequestRef(arg2) : null;
            var _result = _m.GetResourceHandler(_a0, _a1, _a2);

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_OnResourceRedirect(_cef_resource_request_handler_t* self, _cef_browser_t* arg0, _cef_frame_t* arg1, _cef_request_t* arg2, _cef_response_t* arg3, _cef_string_utf16_t* arg4)
    {
        try
        {
            var _m = GetManaged<CefResourceRequestHandler>(self);

            var _a0 = arg0 != null ? new CefBrowserRef(arg0) : null;
            var _a1 = arg1 != null ? new CefFrameRef(arg1) : null;
            var _a2 = arg2 != null ? new CefRequestRef(arg2) : null;
            var _a3 = arg3 != null ? new CefResponseRef(arg3) : null;
            string? _out4 = null;
            if (arg4 != null) _out4 = CefStringRef.ToStringAndFree(arg4);
            _m.OnResourceRedirect(_a0, _a1, _a2, _a3, out _out4);
            if (arg4 != null)
            {
                fixed (char* _p4 = _out4)
                    CefUnsafe.StringUtf16Set((ushort*)_p4, (nuint)(_out4?.Length ?? 0), arg4, copy: 1);
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_OnResourceResponse(_cef_resource_request_handler_t* self, _cef_browser_t* arg0, _cef_frame_t* arg1, _cef_request_t* arg2, _cef_response_t* arg3)
    {
        try
        {
            var _m = GetManaged<CefResourceRequestHandler>(self);

            var _a0 = arg0 != null ? new CefBrowserRef(arg0) : null;
            var _a1 = arg1 != null ? new CefFrameRef(arg1) : null;
            var _a2 = arg2 != null ? new CefRequestRef(arg2) : null;
            var _a3 = arg3 != null ? new CefResponseRef(arg3) : null;
            var _result = _m.OnResourceResponse(_a0, _a1, _a2, _a3);

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_response_filter_t* Bridge_GetResourceResponseFilter(_cef_resource_request_handler_t* self, _cef_browser_t* arg0, _cef_frame_t* arg1, _cef_request_t* arg2, _cef_response_t* arg3)
    {
        try
        {
            var _m = GetManaged<CefResourceRequestHandler>(self);

            var _a0 = arg0 != null ? new CefBrowserRef(arg0) : null;
            var _a1 = arg1 != null ? new CefFrameRef(arg1) : null;
            var _a2 = arg2 != null ? new CefRequestRef(arg2) : null;
            var _a3 = arg3 != null ? new CefResponseRef(arg3) : null;
            var _result = _m.GetResourceResponseFilter(_a0, _a1, _a2, _a3);

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_OnResourceLoadComplete(_cef_resource_request_handler_t* self, _cef_browser_t* arg0, _cef_frame_t* arg1, _cef_request_t* arg2, _cef_response_t* arg3, cef_urlrequest_status_t arg4, long arg5)
    {
        try
        {
            var _m = GetManaged<CefResourceRequestHandler>(self);

            var _a0 = arg0 != null ? new CefBrowserRef(arg0) : null;
            var _a1 = arg1 != null ? new CefFrameRef(arg1) : null;
            var _a2 = arg2 != null ? new CefRequestRef(arg2) : null;
            var _a3 = arg3 != null ? new CefResponseRef(arg3) : null;
            var _a4 = arg4;
            var _a5 = arg5;
            _m.OnResourceLoadComplete(_a0, _a1, _a2, _a3, _a4, _a5);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static void Bridge_OnProtocolExecution(_cef_resource_request_handler_t* self, _cef_browser_t* arg0, _cef_frame_t* arg1, _cef_request_t* arg2, int* arg3)
    {
        try
        {
            var _m = GetManaged<CefResourceRequestHandler>(self);

            var _a0 = arg0 != null ? new CefBrowserRef(arg0) : null;
            var _a1 = arg1 != null ? new CefFrameRef(arg1) : null;
            var _a2 = arg2 != null ? new CefRequestRef(arg2) : null;
            var _a3 = arg3;
            _m.OnProtocolExecution(_a0, _a1, _a2, _a3);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }
}
#endif