// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Wraps a library-owned instance of <c>_cef_request_handler_t</c>.
/// Calls <c>add_ref</c> on construction and <c>release</c> on dispose
/// (for ref-counted types) or <c>del</c> on dispose (for scoped types).
/// </summary>
public unsafe partial class CefRequestHandlerRef : CefBaseRefCountedRef, ICefRequestHandler
{
    private readonly _cef_request_handler_t* _ptr;

    public CefRequestHandlerRef(_cef_request_handler_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    _cef_request_handler_t* ICefRequestHandler.NativePtr => _ptr;


    public int OnBeforeBrowse(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, int arg3, int arg4)
    {
        var _result = _ptr->on_before_browse(_ptr, arg0 is null ? null : arg0.NativePtr, arg1 is null ? null : arg1.NativePtr, arg2 is null ? null : arg2.NativePtr, arg3, arg4);

        return _result;
    }

    public int OnOpenUrlfromTab(ICefBrowser? arg0, ICefFrame? arg1, string? arg2, cef_window_open_disposition_t arg3, int arg4)
    {
        fixed (char* _p2 = arg2)
        {
            _cef_string_utf16_t _s2;
            CefStringRef.FillFromPinned(&_s2, _p2, arg2?.Length ?? 0);
            var _result = _ptr->on_open_urlfrom_tab(_ptr, arg0 is null ? null : arg0.NativePtr, arg1 is null ? null : arg1.NativePtr, &_s2, arg3, arg4);

            return _result;
        }
    }

    public ICefResourceRequestHandler? GetResourceRequestHandler(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, int arg3, int arg4, string? arg5, int* arg6)
    {
        fixed (char* _p5 = arg5)
        {
            _cef_string_utf16_t _s5;
            CefStringRef.FillFromPinned(&_s5, _p5, arg5?.Length ?? 0);
            var _result = _ptr->get_resource_request_handler(_ptr, arg0 is null ? null : arg0.NativePtr, arg1 is null ? null : arg1.NativePtr, arg2 is null ? null : arg2.NativePtr, arg3, arg4, &_s5, arg6);

            return _result != null ? new CefResourceRequestHandlerRef(_result) : null;
        }
    }

    public int GetAuthCredentials(ICefBrowser? arg0, string? arg1, int arg2, string? arg3, int arg4, string? arg5, string? arg6, ICefAuthCallback? arg7)
    {
        fixed (char* _p1 = arg1)
        fixed (char* _p3 = arg3)
        fixed (char* _p5 = arg5)
        fixed (char* _p6 = arg6)
        {
            _cef_string_utf16_t _s1;
            CefStringRef.FillFromPinned(&_s1, _p1, arg1?.Length ?? 0);
            _cef_string_utf16_t _s3;
            CefStringRef.FillFromPinned(&_s3, _p3, arg3?.Length ?? 0);
            _cef_string_utf16_t _s5;
            CefStringRef.FillFromPinned(&_s5, _p5, arg5?.Length ?? 0);
            _cef_string_utf16_t _s6;
            CefStringRef.FillFromPinned(&_s6, _p6, arg6?.Length ?? 0);
            var _result = _ptr->get_auth_credentials(_ptr, arg0 is null ? null : arg0.NativePtr, &_s1, arg2, &_s3, arg4, &_s5, &_s6, arg7 is null ? null : arg7.NativePtr);

            return _result;
        }
    }

    public int OnCertificateError(ICefBrowser? arg0, cef_errorcode_t arg1, string? arg2, ICefSslinfo? arg3, ICefCallback? arg4)
    {
        fixed (char* _p2 = arg2)
        {
            _cef_string_utf16_t _s2;
            CefStringRef.FillFromPinned(&_s2, _p2, arg2?.Length ?? 0);
            var _result = _ptr->on_certificate_error(_ptr, arg0 is null ? null : arg0.NativePtr, arg1, &_s2, arg3 is null ? null : arg3.NativePtr, arg4 is null ? null : arg4.NativePtr);

            return _result;
        }
    }

    public int OnSelectClientCertificate(ICefBrowser? arg0, int arg1, string? arg2, int arg3, nuint arg4, _cef_x509_certificate_t** arg5, ICefSelectClientCertificateCallback? arg6)
    {
        fixed (char* _p2 = arg2)
        {
            _cef_string_utf16_t _s2;
            CefStringRef.FillFromPinned(&_s2, _p2, arg2?.Length ?? 0);
            var _result = _ptr->on_select_client_certificate(_ptr, arg0 is null ? null : arg0.NativePtr, arg1, &_s2, arg3, arg4, arg5, arg6 is null ? null : arg6.NativePtr);

            return _result;
        }
    }

    public void OnRenderViewReady(ICefBrowser? arg0)
    {
        _ptr->on_render_view_ready(_ptr, arg0 is null ? null : arg0.NativePtr);
    }

    public int OnRenderProcessUnresponsive(ICefBrowser? arg0, ICefUnresponsiveProcessCallback? arg1)
    {
        var _result = _ptr->on_render_process_unresponsive(_ptr, arg0 is null ? null : arg0.NativePtr, arg1 is null ? null : arg1.NativePtr);

        return _result;
    }

    public void OnRenderProcessResponsive(ICefBrowser? arg0)
    {
        _ptr->on_render_process_responsive(_ptr, arg0 is null ? null : arg0.NativePtr);
    }

    public void OnRenderProcessTerminated(ICefBrowser? arg0, cef_termination_status_t arg1, int arg2, string? arg3)
    {
        fixed (char* _p3 = arg3)
        {
            _cef_string_utf16_t _s3;
            CefStringRef.FillFromPinned(&_s3, _p3, arg3?.Length ?? 0);
            _ptr->on_render_process_terminated(_ptr, arg0 is null ? null : arg0.NativePtr, arg1, arg2, &_s3);
        }
    }

    public void OnDocumentAvailableInMainFrame(ICefBrowser? arg0)
    {
        _ptr->on_document_available_in_main_frame(_ptr, arg0 is null ? null : arg0.NativePtr);
    }

    public _cef_base_ref_counted_t @base
    {
        get => _ptr->@base;
        set => _ptr->@base = value;
    }
}
