// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

public unsafe partial class CefResponseFilter : CefBaseRefCounted
{
    private readonly _cef_response_filter_t* _ptr;

    public CefResponseFilter(_cef_response_filter_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    internal _cef_response_filter_t* NativePtr => _ptr;

    public int InitFilter()
    {
        var _result = _ptr->init_filter(_ptr);

        return _result;
    }

    public cef_response_filter_status_t Filter(void* arg0, nuint arg1, nuint* arg2, void* arg3, nuint arg4, nuint* arg5)
    {
        var _result = _ptr->filter(_ptr, arg0, arg1, arg2, arg3, arg4, arg5);

        return _result;
    }

        public _cef_base_ref_counted_t @base
        {
            get => _ptr->@base;
            set => _ptr->@base = value;
        }
}
