// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_string_multimap_t</code> type.
/// </summary>
public unsafe partial interface ICefStringMultimap
{
    public _cef_string_multimap_t* NativePtr { get; }
}

public unsafe partial class CefStringMultimap
{
    private readonly _cef_string_multimap_t* _ptr;

    public CefStringMultimap(_cef_string_multimap_t* ptr)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    public _cef_string_multimap_t* NativePtr => _ptr;
}
