// <auto-generated/>
#nullable enable

using System.Runtime.CompilerServices;
using RawCef.Native;

namespace RawCef;

/// <summary>
/// Wraps a library-owned instance of <c>_cef_string_list_t</c>.
/// </summary>
public unsafe partial class CefStringListRef : ICefStringList
{
    private readonly _cef_string_list_t* _ptr;

    public CefStringListRef(_cef_string_list_t* ptr)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    _cef_string_list_t* ICefStringList.NativePtr => _ptr;

}
