// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_string_map_t</code> type.
/// </summary>
public unsafe partial interface ICefStringMap
{
    public _cef_string_map_t* NativePtr { get; }
}

public unsafe partial class CefStringMap
{
    private readonly _cef_string_map_t* _ptr;

    public CefStringMap(_cef_string_map_t* ptr)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    public _cef_string_map_t* NativePtr => _ptr;
}
