#if OS_WIN
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Wraps a library-owned instance of <c>_cef_set_cookie_callback_t</c>.
/// Calls <c>add_ref</c> on construction and <c>release</c> on dispose
/// (for ref-counted types) or <c>del</c> on dispose (for scoped types).
/// </summary>
public unsafe partial class CefSetCookieCallbackRef : CefBaseRefCountedRef, ICefSetCookieCallback
{
    private readonly _cef_set_cookie_callback_t* _ptr;

    public CefSetCookieCallbackRef(_cef_set_cookie_callback_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    _cef_set_cookie_callback_t* ICefSetCookieCallback.NativePtr => _ptr;


    public void OnComplete(int arg0)
    {
        _ptr->on_complete(_ptr, arg0);
    }

    public _cef_base_ref_counted_t @base
    {
        get => _ptr->@base;
        set => _ptr->@base = value;
    }
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Wraps a library-owned instance of <c>_cef_set_cookie_callback_t</c>.
/// Calls <c>add_ref</c> on construction and <c>release</c> on dispose
/// (for ref-counted types) or <c>del</c> on dispose (for scoped types).
/// </summary>
public unsafe partial class CefSetCookieCallbackRef : CefBaseRefCountedRef, ICefSetCookieCallback
{
    private readonly _cef_set_cookie_callback_t* _ptr;

    public CefSetCookieCallbackRef(_cef_set_cookie_callback_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    _cef_set_cookie_callback_t* ICefSetCookieCallback.NativePtr => _ptr;


    public void OnComplete(int arg0)
    {
        _ptr->on_complete(_ptr, arg0);
    }

    public _cef_base_ref_counted_t @base
    {
        get => _ptr->@base;
        set => _ptr->@base = value;
    }
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Wraps a library-owned instance of <c>_cef_set_cookie_callback_t</c>.
/// Calls <c>add_ref</c> on construction and <c>release</c> on dispose
/// (for ref-counted types) or <c>del</c> on dispose (for scoped types).
/// </summary>
public unsafe partial class CefSetCookieCallbackRef : CefBaseRefCountedRef, ICefSetCookieCallback
{
    private readonly _cef_set_cookie_callback_t* _ptr;

    public CefSetCookieCallbackRef(_cef_set_cookie_callback_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    _cef_set_cookie_callback_t* ICefSetCookieCallback.NativePtr => _ptr;


    public void OnComplete(int arg0)
    {
        _ptr->on_complete(_ptr, arg0);
    }

    public _cef_base_ref_counted_t @base
    {
        get => _ptr->@base;
        set => _ptr->@base = value;
    }
}
#endif