#if OS_WIN
// <auto-generated/>
#nullable enable

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using RawCef.Native;

namespace RawCef;

/// <summary>
/// Abstract base class for client-side implementations of <c>_cef_task_runner_t</c>.
/// Subclass this to implement a custom CefTaskRunner.
/// </summary>
public unsafe abstract partial class CefTaskRunner : CefBaseRefCounted, ICefTaskRunner
{
    private _cef_task_runner_t* _typedPtr;

    protected CefTaskRunner() : this((nuint)sizeof(_cef_task_runner_t))
    {
    }

    protected CefTaskRunner(nuint structSize) : base(structSize)
    {
        _typedPtr = (_cef_task_runner_t*)NativePtr;
        InitializeNativeStruct();
    }

    _cef_task_runner_t* ICefTaskRunner.NativePtr => _typedPtr;

    /// <inheritdoc />
    protected override void InitializeNativeStruct()
    {
        base.InitializeNativeStruct();

        _typedPtr->is_same = &Bridge_IsSame;
        _typedPtr->belongs_to_current_thread = &Bridge_BelongsToCurrentThread;
        _typedPtr->belongs_to_thread = &Bridge_BelongsToThread;
        _typedPtr->post_task = &Bridge_PostTask;
        _typedPtr->post_delayed_task = &Bridge_PostDelayedTask;
    }


    /// <summary>
    /// Implement the <c>is_same</c> callback.
    /// </summary>
    public abstract int IsSame(ICefTaskRunner? arg0);

    /// <summary>
    /// Implement the <c>belongs_to_current_thread</c> callback.
    /// </summary>
    public abstract int BelongsToCurrentThread();

    /// <summary>
    /// Implement the <c>belongs_to_thread</c> callback.
    /// </summary>
    public abstract int BelongsToThread(cef_thread_id_t arg0);

    /// <summary>
    /// Implement the <c>post_task</c> callback.
    /// </summary>
    public abstract int PostTask(ICefTask? arg0);

    /// <summary>
    /// Implement the <c>post_delayed_task</c> callback.
    /// </summary>
    public abstract int PostDelayedTask(ICefTask? arg0, long arg1);

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_IsSame(_cef_task_runner_t* self, _cef_task_runner_t* arg0)
    {
        var _m = GetManaged<CefTaskRunner>(self);

        var _a0 = arg0 != null ? new CefTaskRunnerRef(arg0) : null;
        var _result = _m.IsSame(_a0);

        return _result;
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_BelongsToCurrentThread(_cef_task_runner_t* self)
    {
        var _m = GetManaged<CefTaskRunner>(self);

        var _result = _m.BelongsToCurrentThread();

        return _result;
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_BelongsToThread(_cef_task_runner_t* self, cef_thread_id_t arg0)
    {
        var _m = GetManaged<CefTaskRunner>(self);

        var _a0 = arg0;
        var _result = _m.BelongsToThread(_a0);

        return _result;
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_PostTask(_cef_task_runner_t* self, _cef_task_t* arg0)
    {
        var _m = GetManaged<CefTaskRunner>(self);

        var _a0 = arg0 != null ? new CefTaskRef(arg0) : null;
        var _result = _m.PostTask(_a0);

        return _result;
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_PostDelayedTask(_cef_task_runner_t* self, _cef_task_t* arg0, long arg1)
    {
        var _m = GetManaged<CefTaskRunner>(self);

        var _a0 = arg0 != null ? new CefTaskRef(arg0) : null;
        var _a1 = arg1;
        var _result = _m.PostDelayedTask(_a0, _a1);

        return _result;
    }
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using RawCef.Native;

namespace RawCef;

/// <summary>
/// Abstract base class for client-side implementations of <c>_cef_task_runner_t</c>.
/// Subclass this to implement a custom CefTaskRunner.
/// </summary>
public unsafe abstract partial class CefTaskRunner : CefBaseRefCounted, ICefTaskRunner
{
    private _cef_task_runner_t* _typedPtr;

    protected CefTaskRunner() : this((nuint)sizeof(_cef_task_runner_t))
    {
    }

    protected CefTaskRunner(nuint structSize) : base(structSize)
    {
        _typedPtr = (_cef_task_runner_t*)NativePtr;
        InitializeNativeStruct();
    }

    _cef_task_runner_t* ICefTaskRunner.NativePtr => _typedPtr;

    /// <inheritdoc />
    protected override void InitializeNativeStruct()
    {
        base.InitializeNativeStruct();

        _typedPtr->is_same = &Bridge_IsSame;
        _typedPtr->belongs_to_current_thread = &Bridge_BelongsToCurrentThread;
        _typedPtr->belongs_to_thread = &Bridge_BelongsToThread;
        _typedPtr->post_task = &Bridge_PostTask;
        _typedPtr->post_delayed_task = &Bridge_PostDelayedTask;
    }


    /// <summary>
    /// Implement the <c>is_same</c> callback.
    /// </summary>
    public abstract int IsSame(ICefTaskRunner? arg0);

    /// <summary>
    /// Implement the <c>belongs_to_current_thread</c> callback.
    /// </summary>
    public abstract int BelongsToCurrentThread();

    /// <summary>
    /// Implement the <c>belongs_to_thread</c> callback.
    /// </summary>
    public abstract int BelongsToThread(cef_thread_id_t arg0);

    /// <summary>
    /// Implement the <c>post_task</c> callback.
    /// </summary>
    public abstract int PostTask(ICefTask? arg0);

    /// <summary>
    /// Implement the <c>post_delayed_task</c> callback.
    /// </summary>
    public abstract int PostDelayedTask(ICefTask? arg0, long arg1);

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_IsSame(_cef_task_runner_t* self, _cef_task_runner_t* arg0)
    {
        var _m = GetManaged<CefTaskRunner>(self);

        var _a0 = arg0 != null ? new CefTaskRunnerRef(arg0) : null;
        var _result = _m.IsSame(_a0);

        return _result;
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_BelongsToCurrentThread(_cef_task_runner_t* self)
    {
        var _m = GetManaged<CefTaskRunner>(self);

        var _result = _m.BelongsToCurrentThread();

        return _result;
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_BelongsToThread(_cef_task_runner_t* self, cef_thread_id_t arg0)
    {
        var _m = GetManaged<CefTaskRunner>(self);

        var _a0 = arg0;
        var _result = _m.BelongsToThread(_a0);

        return _result;
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_PostTask(_cef_task_runner_t* self, _cef_task_t* arg0)
    {
        var _m = GetManaged<CefTaskRunner>(self);

        var _a0 = arg0 != null ? new CefTaskRef(arg0) : null;
        var _result = _m.PostTask(_a0);

        return _result;
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_PostDelayedTask(_cef_task_runner_t* self, _cef_task_t* arg0, long arg1)
    {
        var _m = GetManaged<CefTaskRunner>(self);

        var _a0 = arg0 != null ? new CefTaskRef(arg0) : null;
        var _a1 = arg1;
        var _result = _m.PostDelayedTask(_a0, _a1);

        return _result;
    }
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using RawCef.Native;

namespace RawCef;

/// <summary>
/// Abstract base class for client-side implementations of <c>_cef_task_runner_t</c>.
/// Subclass this to implement a custom CefTaskRunner.
/// </summary>
public unsafe abstract partial class CefTaskRunner : CefBaseRefCounted, ICefTaskRunner
{
    private _cef_task_runner_t* _typedPtr;

    protected CefTaskRunner() : this((nuint)sizeof(_cef_task_runner_t))
    {
    }

    protected CefTaskRunner(nuint structSize) : base(structSize)
    {
        _typedPtr = (_cef_task_runner_t*)NativePtr;
        InitializeNativeStruct();
    }

    _cef_task_runner_t* ICefTaskRunner.NativePtr => _typedPtr;

    /// <inheritdoc />
    protected override void InitializeNativeStruct()
    {
        base.InitializeNativeStruct();

        _typedPtr->is_same = &Bridge_IsSame;
        _typedPtr->belongs_to_current_thread = &Bridge_BelongsToCurrentThread;
        _typedPtr->belongs_to_thread = &Bridge_BelongsToThread;
        _typedPtr->post_task = &Bridge_PostTask;
        _typedPtr->post_delayed_task = &Bridge_PostDelayedTask;
    }


    /// <summary>
    /// Implement the <c>is_same</c> callback.
    /// </summary>
    public abstract int IsSame(ICefTaskRunner? arg0);

    /// <summary>
    /// Implement the <c>belongs_to_current_thread</c> callback.
    /// </summary>
    public abstract int BelongsToCurrentThread();

    /// <summary>
    /// Implement the <c>belongs_to_thread</c> callback.
    /// </summary>
    public abstract int BelongsToThread(cef_thread_id_t arg0);

    /// <summary>
    /// Implement the <c>post_task</c> callback.
    /// </summary>
    public abstract int PostTask(ICefTask? arg0);

    /// <summary>
    /// Implement the <c>post_delayed_task</c> callback.
    /// </summary>
    public abstract int PostDelayedTask(ICefTask? arg0, long arg1);

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_IsSame(_cef_task_runner_t* self, _cef_task_runner_t* arg0)
    {
        var _m = GetManaged<CefTaskRunner>(self);

        var _a0 = arg0 != null ? new CefTaskRunnerRef(arg0) : null;
        var _result = _m.IsSame(_a0);

        return _result;
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_BelongsToCurrentThread(_cef_task_runner_t* self)
    {
        var _m = GetManaged<CefTaskRunner>(self);

        var _result = _m.BelongsToCurrentThread();

        return _result;
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_BelongsToThread(_cef_task_runner_t* self, cef_thread_id_t arg0)
    {
        var _m = GetManaged<CefTaskRunner>(self);

        var _a0 = arg0;
        var _result = _m.BelongsToThread(_a0);

        return _result;
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_PostTask(_cef_task_runner_t* self, _cef_task_t* arg0)
    {
        var _m = GetManaged<CefTaskRunner>(self);

        var _a0 = arg0 != null ? new CefTaskRef(arg0) : null;
        var _result = _m.PostTask(_a0);

        return _result;
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_PostDelayedTask(_cef_task_runner_t* self, _cef_task_t* arg0, long arg1)
    {
        var _m = GetManaged<CefTaskRunner>(self);

        var _a0 = arg0 != null ? new CefTaskRef(arg0) : null;
        var _a1 = arg1;
        var _result = _m.PostDelayedTask(_a0, _a1);

        return _result;
    }
}
#endif