#if OS_WIN
// <auto-generated/>
#nullable enable

using System.Runtime.CompilerServices;
using RawCef.Native;

namespace RawCef;

/// <summary>
/// Wraps a library-owned instance of <c>_cef_v8_accessor_t</c>.
/// Calls <c>add_ref</c> on construction and <c>release</c> on dispose
/// (for ref-counted types) or <c>del</c> on dispose (for scoped types).
/// </summary>
public unsafe partial class CefV8AccessorRef : CefBaseRefCountedRef, ICefV8Accessor
{
    private readonly _cef_v8_accessor_t* _ptr;

    public CefV8AccessorRef(_cef_v8_accessor_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    _cef_v8_accessor_t* ICefV8Accessor.NativePtr => _ptr;


    public int Get(string? arg0, ICefV8Value? arg1, out ICefV8Value? arg2, out string? arg3)
    {
        _cef_v8_value_t* _out2 = null;
        _cef_string_utf16_t _out3 = default;
        fixed (char* _p0 = arg0)
        {
            _cef_string_utf16_t _s0;
            CefStringRef.FillFromPinned(&_s0, _p0, arg0?.Length ?? 0);
            var _result = _ptr->get(_ptr, &_s0, arg1 is null ? null : arg1.NativePtr, &_out2, &_out3);

            arg2 = _out2 != null ? new CefV8ValueRef(_out2) : null;
            arg3 = CefStringRef.ToStringAndFree(&_out3);
            return _result;
        }
    }

    public int Set(string? arg0, ICefV8Value? arg1, ICefV8Value? arg2, out string? arg3)
    {
        _cef_string_utf16_t _out3 = default;
        fixed (char* _p0 = arg0)
        {
            _cef_string_utf16_t _s0;
            CefStringRef.FillFromPinned(&_s0, _p0, arg0?.Length ?? 0);
            var _result = _ptr->set(_ptr, &_s0, arg1 is null ? null : arg1.NativePtr, arg2 is null ? null : arg2.NativePtr, &_out3);

            arg3 = CefStringRef.ToStringAndFree(&_out3);
            return _result;
        }
    }

    public _cef_base_ref_counted_t @base
    {
        get => _ptr->@base;
        set => _ptr->@base = value;
    }
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

using System.Runtime.CompilerServices;
using RawCef.Native;

namespace RawCef;

/// <summary>
/// Wraps a library-owned instance of <c>_cef_v8_accessor_t</c>.
/// Calls <c>add_ref</c> on construction and <c>release</c> on dispose
/// (for ref-counted types) or <c>del</c> on dispose (for scoped types).
/// </summary>
public unsafe partial class CefV8AccessorRef : CefBaseRefCountedRef, ICefV8Accessor
{
    private readonly _cef_v8_accessor_t* _ptr;

    public CefV8AccessorRef(_cef_v8_accessor_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    _cef_v8_accessor_t* ICefV8Accessor.NativePtr => _ptr;


    public int Get(string? arg0, ICefV8Value? arg1, out ICefV8Value? arg2, out string? arg3)
    {
        _cef_v8_value_t* _out2 = null;
        _cef_string_utf16_t _out3 = default;
        fixed (char* _p0 = arg0)
        {
            _cef_string_utf16_t _s0;
            CefStringRef.FillFromPinned(&_s0, _p0, arg0?.Length ?? 0);
            var _result = _ptr->get(_ptr, &_s0, arg1 is null ? null : arg1.NativePtr, &_out2, &_out3);

            arg2 = _out2 != null ? new CefV8ValueRef(_out2) : null;
            arg3 = CefStringRef.ToStringAndFree(&_out3);
            return _result;
        }
    }

    public int Set(string? arg0, ICefV8Value? arg1, ICefV8Value? arg2, out string? arg3)
    {
        _cef_string_utf16_t _out3 = default;
        fixed (char* _p0 = arg0)
        {
            _cef_string_utf16_t _s0;
            CefStringRef.FillFromPinned(&_s0, _p0, arg0?.Length ?? 0);
            var _result = _ptr->set(_ptr, &_s0, arg1 is null ? null : arg1.NativePtr, arg2 is null ? null : arg2.NativePtr, &_out3);

            arg3 = CefStringRef.ToStringAndFree(&_out3);
            return _result;
        }
    }

    public _cef_base_ref_counted_t @base
    {
        get => _ptr->@base;
        set => _ptr->@base = value;
    }
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

using System.Runtime.CompilerServices;
using RawCef.Native;

namespace RawCef;

/// <summary>
/// Wraps a library-owned instance of <c>_cef_v8_accessor_t</c>.
/// Calls <c>add_ref</c> on construction and <c>release</c> on dispose
/// (for ref-counted types) or <c>del</c> on dispose (for scoped types).
/// </summary>
public unsafe partial class CefV8AccessorRef : CefBaseRefCountedRef, ICefV8Accessor
{
    private readonly _cef_v8_accessor_t* _ptr;

    public CefV8AccessorRef(_cef_v8_accessor_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    _cef_v8_accessor_t* ICefV8Accessor.NativePtr => _ptr;


    public int Get(string? arg0, ICefV8Value? arg1, out ICefV8Value? arg2, out string? arg3)
    {
        _cef_v8_value_t* _out2 = null;
        _cef_string_utf16_t _out3 = default;
        fixed (char* _p0 = arg0)
        {
            _cef_string_utf16_t _s0;
            CefStringRef.FillFromPinned(&_s0, _p0, arg0?.Length ?? 0);
            var _result = _ptr->get(_ptr, &_s0, arg1 is null ? null : arg1.NativePtr, &_out2, &_out3);

            arg2 = _out2 != null ? new CefV8ValueRef(_out2) : null;
            arg3 = CefStringRef.ToStringAndFree(&_out3);
            return _result;
        }
    }

    public int Set(string? arg0, ICefV8Value? arg1, ICefV8Value? arg2, out string? arg3)
    {
        _cef_string_utf16_t _out3 = default;
        fixed (char* _p0 = arg0)
        {
            _cef_string_utf16_t _s0;
            CefStringRef.FillFromPinned(&_s0, _p0, arg0?.Length ?? 0);
            var _result = _ptr->set(_ptr, &_s0, arg1 is null ? null : arg1.NativePtr, arg2 is null ? null : arg2.NativePtr, &_out3);

            arg3 = CefStringRef.ToStringAndFree(&_out3);
            return _result;
        }
    }

    public _cef_base_ref_counted_t @base
    {
        get => _ptr->@base;
        set => _ptr->@base = value;
    }
}
#endif