#if OS_WIN
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Wraps a library-owned instance of <c>_cef_v8_stack_trace_t</c>.
/// Calls <c>add_ref</c> on construction and <c>release</c> on dispose
/// (for ref-counted types) or <c>del</c> on dispose (for scoped types).
/// </summary>
public unsafe partial class CefV8StackTraceRef : CefBaseRefCountedRef, ICefV8StackTrace
{
    private readonly _cef_v8_stack_trace_t* _ptr;

    public CefV8StackTraceRef(_cef_v8_stack_trace_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    _cef_v8_stack_trace_t* ICefV8StackTrace.NativePtr => _ptr;


    public int IsValid()
    {
        var _result = _ptr->is_valid(_ptr);

        return _result;
    }

    public int GetFrameCount()
    {
        var _result = _ptr->get_frame_count(_ptr);

        return _result;
    }

    public ICefV8StackFrame? GetFrame(int arg0)
    {
        var _result = _ptr->get_frame(_ptr, arg0);

        return _result != null ? new CefV8StackFrameRef(_result) : null;
    }

    public _cef_base_ref_counted_t @base
    {
        get => _ptr->@base;
        set => _ptr->@base = value;
    }
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Wraps a library-owned instance of <c>_cef_v8_stack_trace_t</c>.
/// Calls <c>add_ref</c> on construction and <c>release</c> on dispose
/// (for ref-counted types) or <c>del</c> on dispose (for scoped types).
/// </summary>
public unsafe partial class CefV8StackTraceRef : CefBaseRefCountedRef, ICefV8StackTrace
{
    private readonly _cef_v8_stack_trace_t* _ptr;

    public CefV8StackTraceRef(_cef_v8_stack_trace_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    _cef_v8_stack_trace_t* ICefV8StackTrace.NativePtr => _ptr;


    public int IsValid()
    {
        var _result = _ptr->is_valid(_ptr);

        return _result;
    }

    public int GetFrameCount()
    {
        var _result = _ptr->get_frame_count(_ptr);

        return _result;
    }

    public ICefV8StackFrame? GetFrame(int arg0)
    {
        var _result = _ptr->get_frame(_ptr, arg0);

        return _result != null ? new CefV8StackFrameRef(_result) : null;
    }

    public _cef_base_ref_counted_t @base
    {
        get => _ptr->@base;
        set => _ptr->@base = value;
    }
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Wraps a library-owned instance of <c>_cef_v8_stack_trace_t</c>.
/// Calls <c>add_ref</c> on construction and <c>release</c> on dispose
/// (for ref-counted types) or <c>del</c> on dispose (for scoped types).
/// </summary>
public unsafe partial class CefV8StackTraceRef : CefBaseRefCountedRef, ICefV8StackTrace
{
    private readonly _cef_v8_stack_trace_t* _ptr;

    public CefV8StackTraceRef(_cef_v8_stack_trace_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    _cef_v8_stack_trace_t* ICefV8StackTrace.NativePtr => _ptr;


    public int IsValid()
    {
        var _result = _ptr->is_valid(_ptr);

        return _result;
    }

    public int GetFrameCount()
    {
        var _result = _ptr->get_frame_count(_ptr);

        return _result;
    }

    public ICefV8StackFrame? GetFrame(int arg0)
    {
        var _result = _ptr->get_frame(_ptr, arg0);

        return _result != null ? new CefV8StackFrameRef(_result) : null;
    }

    public _cef_base_ref_counted_t @base
    {
        get => _ptr->@base;
        set => _ptr->@base = value;
    }
}
#endif