// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

public unsafe partial class CefV8ArrayBufferReleaseCallback : CefBaseRefCounted
{
    private readonly _cef_v8_array_buffer_release_callback_t* _ptr;

    public CefV8ArrayBufferReleaseCallback(_cef_v8_array_buffer_release_callback_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    internal _cef_v8_array_buffer_release_callback_t* NativePtr => _ptr;

    public void ReleaseBuffer(void* arg0)
    {
        _ptr->release_buffer(_ptr, arg0);
    }

        public _cef_base_ref_counted_t @base
        {
            get => _ptr->@base;
            set => _ptr->@base = value;
        }
}
