#if OS_WIN
// <auto-generated/>
#nullable enable

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using RawCef.Native;

namespace RawCef;

/// <summary>
/// Abstract base class for client-side implementations of <c>_cef_v8_context_t</c>.
/// Subclass this to implement a custom CefV8Context.
/// </summary>
public unsafe abstract partial class CefV8Context : CefBaseRefCounted, ICefV8Context
{
    private _cef_v8_context_t* _typedPtr;

    protected CefV8Context() : this((nuint)sizeof(_cef_v8_context_t))
    {
    }

    protected CefV8Context(nuint structSize) : base(structSize)
    {
        _typedPtr = (_cef_v8_context_t*)NativePtr;
        InitializeNativeStruct();
    }

    _cef_v8_context_t* ICefV8Context.NativePtr => _typedPtr;

    /// <inheritdoc />
    protected override void InitializeNativeStruct()
    {
        base.InitializeNativeStruct();

        _typedPtr->get_task_runner = &Bridge_GetTaskRunner;
        _typedPtr->is_valid = &Bridge_IsValid;
        _typedPtr->get_browser = &Bridge_GetBrowser;
        _typedPtr->get_frame = &Bridge_GetFrame;
        _typedPtr->get_global = &Bridge_GetGlobal;
        _typedPtr->enter = &Bridge_Enter;
        _typedPtr->exit = &Bridge_Exit;
        _typedPtr->is_same = &Bridge_IsSame;
        _typedPtr->eval = &Bridge_Eval;
    }


    /// <summary>
    /// Implement the <c>get_task_runner</c> callback.
    /// </summary>
    public abstract ICefTaskRunner? GetTaskRunner();

    /// <summary>
    /// Implement the <c>is_valid</c> callback.
    /// </summary>
    public abstract int IsValid();

    /// <summary>
    /// Implement the <c>get_browser</c> callback.
    /// </summary>
    public abstract ICefBrowser? GetBrowser();

    /// <summary>
    /// Implement the <c>get_frame</c> callback.
    /// </summary>
    public abstract ICefFrame? GetFrame();

    /// <summary>
    /// Implement the <c>get_global</c> callback.
    /// </summary>
    public abstract ICefV8Value? GetGlobal();

    /// <summary>
    /// Implement the <c>enter</c> callback.
    /// </summary>
    public abstract int Enter();

    /// <summary>
    /// Implement the <c>exit</c> callback.
    /// </summary>
    public abstract int Exit();

    /// <summary>
    /// Implement the <c>is_same</c> callback.
    /// </summary>
    public abstract int IsSame(ICefV8Context? arg0);

    /// <summary>
    /// Implement the <c>eval</c> callback.
    /// </summary>
    public abstract int Eval(string? arg0, string? arg1, int arg2, out ICefV8Value? arg3, out ICefV8Exception? arg4);

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_task_runner_t* Bridge_GetTaskRunner(_cef_v8_context_t* self)
    {
        try
        {
            var _m = GetManaged<CefV8Context>(self);

            var _result = _m.GetTaskRunner();

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_IsValid(_cef_v8_context_t* self)
    {
        try
        {
            var _m = GetManaged<CefV8Context>(self);

            var _result = _m.IsValid();

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_browser_t* Bridge_GetBrowser(_cef_v8_context_t* self)
    {
        try
        {
            var _m = GetManaged<CefV8Context>(self);

            var _result = _m.GetBrowser();

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_frame_t* Bridge_GetFrame(_cef_v8_context_t* self)
    {
        try
        {
            var _m = GetManaged<CefV8Context>(self);

            var _result = _m.GetFrame();

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_v8_value_t* Bridge_GetGlobal(_cef_v8_context_t* self)
    {
        try
        {
            var _m = GetManaged<CefV8Context>(self);

            var _result = _m.GetGlobal();

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_Enter(_cef_v8_context_t* self)
    {
        try
        {
            var _m = GetManaged<CefV8Context>(self);

            var _result = _m.Enter();

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_Exit(_cef_v8_context_t* self)
    {
        try
        {
            var _m = GetManaged<CefV8Context>(self);

            var _result = _m.Exit();

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_IsSame(_cef_v8_context_t* self, _cef_v8_context_t* arg0)
    {
        try
        {
            var _m = GetManaged<CefV8Context>(self);

            var _a0 = arg0 != null ? new CefV8ContextRef(arg0) : null;
            var _result = _m.IsSame(_a0);

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_Eval(_cef_v8_context_t* self, _cef_string_utf16_t* arg0, _cef_string_utf16_t* arg1, int arg2, _cef_v8_value_t** arg3, _cef_v8_exception_t** arg4)
    {
        try
        {
            var _m = GetManaged<CefV8Context>(self);

            var _a0 = CefStringRef.ToString(arg0);
            var _a1 = CefStringRef.ToString(arg1);
            var _a2 = arg2;
            ICefV8Value? _out3 = null;
            if (arg3 != null && *arg3 != null) _out3 = new CefV8ValueRef(*arg3);
            ICefV8Exception? _out4 = null;
            if (arg4 != null && *arg4 != null) _out4 = new CefV8ExceptionRef(*arg4);
            var _result = _m.Eval(_a0, _a1, _a2, out _out3, out _out4);

            if (arg3 != null) *arg3 = _out3 != null ? _out3.NativePtr : null;
            if (arg4 != null) *arg4 = _out4 != null ? _out4.NativePtr : null;
            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using RawCef.Native;

namespace RawCef;

/// <summary>
/// Abstract base class for client-side implementations of <c>_cef_v8_context_t</c>.
/// Subclass this to implement a custom CefV8Context.
/// </summary>
public unsafe abstract partial class CefV8Context : CefBaseRefCounted, ICefV8Context
{
    private _cef_v8_context_t* _typedPtr;

    protected CefV8Context() : this((nuint)sizeof(_cef_v8_context_t))
    {
    }

    protected CefV8Context(nuint structSize) : base(structSize)
    {
        _typedPtr = (_cef_v8_context_t*)NativePtr;
        InitializeNativeStruct();
    }

    _cef_v8_context_t* ICefV8Context.NativePtr => _typedPtr;

    /// <inheritdoc />
    protected override void InitializeNativeStruct()
    {
        base.InitializeNativeStruct();

        _typedPtr->get_task_runner = &Bridge_GetTaskRunner;
        _typedPtr->is_valid = &Bridge_IsValid;
        _typedPtr->get_browser = &Bridge_GetBrowser;
        _typedPtr->get_frame = &Bridge_GetFrame;
        _typedPtr->get_global = &Bridge_GetGlobal;
        _typedPtr->enter = &Bridge_Enter;
        _typedPtr->exit = &Bridge_Exit;
        _typedPtr->is_same = &Bridge_IsSame;
        _typedPtr->eval = &Bridge_Eval;
    }


    /// <summary>
    /// Implement the <c>get_task_runner</c> callback.
    /// </summary>
    public abstract ICefTaskRunner? GetTaskRunner();

    /// <summary>
    /// Implement the <c>is_valid</c> callback.
    /// </summary>
    public abstract int IsValid();

    /// <summary>
    /// Implement the <c>get_browser</c> callback.
    /// </summary>
    public abstract ICefBrowser? GetBrowser();

    /// <summary>
    /// Implement the <c>get_frame</c> callback.
    /// </summary>
    public abstract ICefFrame? GetFrame();

    /// <summary>
    /// Implement the <c>get_global</c> callback.
    /// </summary>
    public abstract ICefV8Value? GetGlobal();

    /// <summary>
    /// Implement the <c>enter</c> callback.
    /// </summary>
    public abstract int Enter();

    /// <summary>
    /// Implement the <c>exit</c> callback.
    /// </summary>
    public abstract int Exit();

    /// <summary>
    /// Implement the <c>is_same</c> callback.
    /// </summary>
    public abstract int IsSame(ICefV8Context? arg0);

    /// <summary>
    /// Implement the <c>eval</c> callback.
    /// </summary>
    public abstract int Eval(string? arg0, string? arg1, int arg2, out ICefV8Value? arg3, out ICefV8Exception? arg4);

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_task_runner_t* Bridge_GetTaskRunner(_cef_v8_context_t* self)
    {
        try
        {
            var _m = GetManaged<CefV8Context>(self);

            var _result = _m.GetTaskRunner();

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_IsValid(_cef_v8_context_t* self)
    {
        try
        {
            var _m = GetManaged<CefV8Context>(self);

            var _result = _m.IsValid();

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_browser_t* Bridge_GetBrowser(_cef_v8_context_t* self)
    {
        try
        {
            var _m = GetManaged<CefV8Context>(self);

            var _result = _m.GetBrowser();

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_frame_t* Bridge_GetFrame(_cef_v8_context_t* self)
    {
        try
        {
            var _m = GetManaged<CefV8Context>(self);

            var _result = _m.GetFrame();

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_v8_value_t* Bridge_GetGlobal(_cef_v8_context_t* self)
    {
        try
        {
            var _m = GetManaged<CefV8Context>(self);

            var _result = _m.GetGlobal();

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_Enter(_cef_v8_context_t* self)
    {
        try
        {
            var _m = GetManaged<CefV8Context>(self);

            var _result = _m.Enter();

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_Exit(_cef_v8_context_t* self)
    {
        try
        {
            var _m = GetManaged<CefV8Context>(self);

            var _result = _m.Exit();

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_IsSame(_cef_v8_context_t* self, _cef_v8_context_t* arg0)
    {
        try
        {
            var _m = GetManaged<CefV8Context>(self);

            var _a0 = arg0 != null ? new CefV8ContextRef(arg0) : null;
            var _result = _m.IsSame(_a0);

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_Eval(_cef_v8_context_t* self, _cef_string_utf16_t* arg0, _cef_string_utf16_t* arg1, int arg2, _cef_v8_value_t** arg3, _cef_v8_exception_t** arg4)
    {
        try
        {
            var _m = GetManaged<CefV8Context>(self);

            var _a0 = CefStringRef.ToString(arg0);
            var _a1 = CefStringRef.ToString(arg1);
            var _a2 = arg2;
            ICefV8Value? _out3 = null;
            if (arg3 != null && *arg3 != null) _out3 = new CefV8ValueRef(*arg3);
            ICefV8Exception? _out4 = null;
            if (arg4 != null && *arg4 != null) _out4 = new CefV8ExceptionRef(*arg4);
            var _result = _m.Eval(_a0, _a1, _a2, out _out3, out _out4);

            if (arg3 != null) *arg3 = _out3 != null ? _out3.NativePtr : null;
            if (arg4 != null) *arg4 = _out4 != null ? _out4.NativePtr : null;
            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using RawCef.Native;

namespace RawCef;

/// <summary>
/// Abstract base class for client-side implementations of <c>_cef_v8_context_t</c>.
/// Subclass this to implement a custom CefV8Context.
/// </summary>
public unsafe abstract partial class CefV8Context : CefBaseRefCounted, ICefV8Context
{
    private _cef_v8_context_t* _typedPtr;

    protected CefV8Context() : this((nuint)sizeof(_cef_v8_context_t))
    {
    }

    protected CefV8Context(nuint structSize) : base(structSize)
    {
        _typedPtr = (_cef_v8_context_t*)NativePtr;
        InitializeNativeStruct();
    }

    _cef_v8_context_t* ICefV8Context.NativePtr => _typedPtr;

    /// <inheritdoc />
    protected override void InitializeNativeStruct()
    {
        base.InitializeNativeStruct();

        _typedPtr->get_task_runner = &Bridge_GetTaskRunner;
        _typedPtr->is_valid = &Bridge_IsValid;
        _typedPtr->get_browser = &Bridge_GetBrowser;
        _typedPtr->get_frame = &Bridge_GetFrame;
        _typedPtr->get_global = &Bridge_GetGlobal;
        _typedPtr->enter = &Bridge_Enter;
        _typedPtr->exit = &Bridge_Exit;
        _typedPtr->is_same = &Bridge_IsSame;
        _typedPtr->eval = &Bridge_Eval;
    }


    /// <summary>
    /// Implement the <c>get_task_runner</c> callback.
    /// </summary>
    public abstract ICefTaskRunner? GetTaskRunner();

    /// <summary>
    /// Implement the <c>is_valid</c> callback.
    /// </summary>
    public abstract int IsValid();

    /// <summary>
    /// Implement the <c>get_browser</c> callback.
    /// </summary>
    public abstract ICefBrowser? GetBrowser();

    /// <summary>
    /// Implement the <c>get_frame</c> callback.
    /// </summary>
    public abstract ICefFrame? GetFrame();

    /// <summary>
    /// Implement the <c>get_global</c> callback.
    /// </summary>
    public abstract ICefV8Value? GetGlobal();

    /// <summary>
    /// Implement the <c>enter</c> callback.
    /// </summary>
    public abstract int Enter();

    /// <summary>
    /// Implement the <c>exit</c> callback.
    /// </summary>
    public abstract int Exit();

    /// <summary>
    /// Implement the <c>is_same</c> callback.
    /// </summary>
    public abstract int IsSame(ICefV8Context? arg0);

    /// <summary>
    /// Implement the <c>eval</c> callback.
    /// </summary>
    public abstract int Eval(string? arg0, string? arg1, int arg2, out ICefV8Value? arg3, out ICefV8Exception? arg4);

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_task_runner_t* Bridge_GetTaskRunner(_cef_v8_context_t* self)
    {
        try
        {
            var _m = GetManaged<CefV8Context>(self);

            var _result = _m.GetTaskRunner();

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_IsValid(_cef_v8_context_t* self)
    {
        try
        {
            var _m = GetManaged<CefV8Context>(self);

            var _result = _m.IsValid();

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_browser_t* Bridge_GetBrowser(_cef_v8_context_t* self)
    {
        try
        {
            var _m = GetManaged<CefV8Context>(self);

            var _result = _m.GetBrowser();

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_frame_t* Bridge_GetFrame(_cef_v8_context_t* self)
    {
        try
        {
            var _m = GetManaged<CefV8Context>(self);

            var _result = _m.GetFrame();

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_v8_value_t* Bridge_GetGlobal(_cef_v8_context_t* self)
    {
        try
        {
            var _m = GetManaged<CefV8Context>(self);

            var _result = _m.GetGlobal();

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_Enter(_cef_v8_context_t* self)
    {
        try
        {
            var _m = GetManaged<CefV8Context>(self);

            var _result = _m.Enter();

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_Exit(_cef_v8_context_t* self)
    {
        try
        {
            var _m = GetManaged<CefV8Context>(self);

            var _result = _m.Exit();

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_IsSame(_cef_v8_context_t* self, _cef_v8_context_t* arg0)
    {
        try
        {
            var _m = GetManaged<CefV8Context>(self);

            var _a0 = arg0 != null ? new CefV8ContextRef(arg0) : null;
            var _result = _m.IsSame(_a0);

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_Eval(_cef_v8_context_t* self, _cef_string_utf16_t* arg0, _cef_string_utf16_t* arg1, int arg2, _cef_v8_value_t** arg3, _cef_v8_exception_t** arg4)
    {
        try
        {
            var _m = GetManaged<CefV8Context>(self);

            var _a0 = CefStringRef.ToString(arg0);
            var _a1 = CefStringRef.ToString(arg1);
            var _a2 = arg2;
            ICefV8Value? _out3 = null;
            if (arg3 != null && *arg3 != null) _out3 = new CefV8ValueRef(*arg3);
            ICefV8Exception? _out4 = null;
            if (arg4 != null && *arg4 != null) _out4 = new CefV8ExceptionRef(*arg4);
            var _result = _m.Eval(_a0, _a1, _a2, out _out3, out _out4);

            if (arg3 != null) *arg3 = _out3 != null ? _out3.NativePtr : null;
            if (arg4 != null) *arg4 = _out4 != null ? _out4.NativePtr : null;
            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }
}
#endif