// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Wraps a library-owned instance of <c>_cef_v8_handler_t</c>.
/// Calls <c>add_ref</c> on construction and <c>release</c> on dispose
/// (for ref-counted types) or <c>del</c> on dispose (for scoped types).
/// </summary>
public unsafe partial class CefV8HandlerRef : CefBaseRefCountedRef, ICefV8Handler
{
    private readonly _cef_v8_handler_t* _ptr;

    public CefV8HandlerRef(_cef_v8_handler_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    _cef_v8_handler_t* ICefV8Handler.NativePtr => _ptr;


    public int Execute(string? arg0, ICefV8Value? arg1, nuint arg2, _cef_v8_value_t** arg3, _cef_v8_value_t** arg4, string? arg5)
    {
        fixed (char* _p0 = arg0)
        fixed (char* _p5 = arg5)
        {
            _cef_string_utf16_t _s0;
            CefStringRef.FillFromPinned(&_s0, _p0, arg0?.Length ?? 0);
            _cef_string_utf16_t _s5;
            CefStringRef.FillFromPinned(&_s5, _p5, arg5?.Length ?? 0);
            var _result = _ptr->execute(_ptr, &_s0, arg1 is null ? null : arg1.NativePtr, arg2, arg3, arg4, &_s5);

            return _result;
        }
    }

    public _cef_base_ref_counted_t @base
    {
        get => _ptr->@base;
        set => _ptr->@base = value;
    }
}
