// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

public unsafe partial class CefV8Handler : CefBaseRefCounted
{
    private readonly _cef_v8_handler_t* _ptr;

    public CefV8Handler(_cef_v8_handler_t* ptr) : base(&ptr->@base)
    {
        _ptr = ptr;
        Initialize();
    }

    partial void Initialize();

    internal _cef_v8_handler_t* NativePtr => _ptr;

    public int Execute(string? arg0, CefV8Value? arg1, nuint arg2, CefV8Value? arg3, CefV8Value? arg4, string? arg5)
    {
        fixed (char* _p0 = arg0)
        fixed (char* _p5 = arg5)
        {
            _cef_string_utf16_t _s0;
            CefStringRef.FillFromPinned(&_s0, _p0, arg0?.Length ?? 0);
            _cef_string_utf16_t _s5;
            CefStringRef.FillFromPinned(&_s5, _p5, arg5?.Length ?? 0);
            var _result = _ptr->execute(_ptr, &_s0, arg1 is null ? null : arg1.NativePtr, arg2, arg3 is null ? null : arg3.NativePtr, arg4 is null ? null : arg4.NativePtr, &_s5);

            return _result;
        }
    }

        public _cef_base_ref_counted_t @base
        {
            get => _ptr->@base;
            set => _ptr->@base = value;
        }
}
