#if OS_WIN
// <auto-generated/>
#nullable enable

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using RawCef.Native;

namespace RawCef;

/// <summary>
/// Abstract base class for client-side implementations of <c>_cef_v8_stack_trace_t</c>.
/// Subclass this to implement a custom CefV8StackTrace.
/// </summary>
public unsafe abstract partial class CefV8StackTrace : CefBaseRefCounted, ICefV8StackTrace
{
    private _cef_v8_stack_trace_t* _typedPtr;

    protected CefV8StackTrace() : this((nuint)sizeof(_cef_v8_stack_trace_t))
    {
    }

    protected CefV8StackTrace(nuint structSize) : base(structSize)
    {
        _typedPtr = (_cef_v8_stack_trace_t*)NativePtr;
        InitializeNativeStruct();
    }

    _cef_v8_stack_trace_t* ICefV8StackTrace.NativePtr => _typedPtr;

    /// <inheritdoc />
    protected override void InitializeNativeStruct()
    {
        base.InitializeNativeStruct();

        _typedPtr->is_valid = &Bridge_IsValid;
        _typedPtr->get_frame_count = &Bridge_GetFrameCount;
        _typedPtr->get_frame = &Bridge_GetFrame;
    }


    /// <summary>
    /// Implement the <c>is_valid</c> callback.
    /// </summary>
    public abstract int IsValid();

    /// <summary>
    /// Implement the <c>get_frame_count</c> callback.
    /// </summary>
    public abstract int GetFrameCount();

    /// <summary>
    /// Implement the <c>get_frame</c> callback.
    /// </summary>
    public abstract ICefV8StackFrame? GetFrame(int arg0);

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_IsValid(_cef_v8_stack_trace_t* self)
    {
        try
        {
            var _m = GetManaged<CefV8StackTrace>(self);

            var _result = _m.IsValid();

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_GetFrameCount(_cef_v8_stack_trace_t* self)
    {
        try
        {
            var _m = GetManaged<CefV8StackTrace>(self);

            var _result = _m.GetFrameCount();

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_v8_stack_frame_t* Bridge_GetFrame(_cef_v8_stack_trace_t* self, int arg0)
    {
        try
        {
            var _m = GetManaged<CefV8StackTrace>(self);

            var _a0 = arg0;
            var _result = _m.GetFrame(_a0);

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using RawCef.Native;

namespace RawCef;

/// <summary>
/// Abstract base class for client-side implementations of <c>_cef_v8_stack_trace_t</c>.
/// Subclass this to implement a custom CefV8StackTrace.
/// </summary>
public unsafe abstract partial class CefV8StackTrace : CefBaseRefCounted, ICefV8StackTrace
{
    private _cef_v8_stack_trace_t* _typedPtr;

    protected CefV8StackTrace() : this((nuint)sizeof(_cef_v8_stack_trace_t))
    {
    }

    protected CefV8StackTrace(nuint structSize) : base(structSize)
    {
        _typedPtr = (_cef_v8_stack_trace_t*)NativePtr;
        InitializeNativeStruct();
    }

    _cef_v8_stack_trace_t* ICefV8StackTrace.NativePtr => _typedPtr;

    /// <inheritdoc />
    protected override void InitializeNativeStruct()
    {
        base.InitializeNativeStruct();

        _typedPtr->is_valid = &Bridge_IsValid;
        _typedPtr->get_frame_count = &Bridge_GetFrameCount;
        _typedPtr->get_frame = &Bridge_GetFrame;
    }


    /// <summary>
    /// Implement the <c>is_valid</c> callback.
    /// </summary>
    public abstract int IsValid();

    /// <summary>
    /// Implement the <c>get_frame_count</c> callback.
    /// </summary>
    public abstract int GetFrameCount();

    /// <summary>
    /// Implement the <c>get_frame</c> callback.
    /// </summary>
    public abstract ICefV8StackFrame? GetFrame(int arg0);

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_IsValid(_cef_v8_stack_trace_t* self)
    {
        try
        {
            var _m = GetManaged<CefV8StackTrace>(self);

            var _result = _m.IsValid();

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_GetFrameCount(_cef_v8_stack_trace_t* self)
    {
        try
        {
            var _m = GetManaged<CefV8StackTrace>(self);

            var _result = _m.GetFrameCount();

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_v8_stack_frame_t* Bridge_GetFrame(_cef_v8_stack_trace_t* self, int arg0)
    {
        try
        {
            var _m = GetManaged<CefV8StackTrace>(self);

            var _a0 = arg0;
            var _result = _m.GetFrame(_a0);

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using RawCef.Native;

namespace RawCef;

/// <summary>
/// Abstract base class for client-side implementations of <c>_cef_v8_stack_trace_t</c>.
/// Subclass this to implement a custom CefV8StackTrace.
/// </summary>
public unsafe abstract partial class CefV8StackTrace : CefBaseRefCounted, ICefV8StackTrace
{
    private _cef_v8_stack_trace_t* _typedPtr;

    protected CefV8StackTrace() : this((nuint)sizeof(_cef_v8_stack_trace_t))
    {
    }

    protected CefV8StackTrace(nuint structSize) : base(structSize)
    {
        _typedPtr = (_cef_v8_stack_trace_t*)NativePtr;
        InitializeNativeStruct();
    }

    _cef_v8_stack_trace_t* ICefV8StackTrace.NativePtr => _typedPtr;

    /// <inheritdoc />
    protected override void InitializeNativeStruct()
    {
        base.InitializeNativeStruct();

        _typedPtr->is_valid = &Bridge_IsValid;
        _typedPtr->get_frame_count = &Bridge_GetFrameCount;
        _typedPtr->get_frame = &Bridge_GetFrame;
    }


    /// <summary>
    /// Implement the <c>is_valid</c> callback.
    /// </summary>
    public abstract int IsValid();

    /// <summary>
    /// Implement the <c>get_frame_count</c> callback.
    /// </summary>
    public abstract int GetFrameCount();

    /// <summary>
    /// Implement the <c>get_frame</c> callback.
    /// </summary>
    public abstract ICefV8StackFrame? GetFrame(int arg0);

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_IsValid(_cef_v8_stack_trace_t* self)
    {
        try
        {
            var _m = GetManaged<CefV8StackTrace>(self);

            var _result = _m.IsValid();

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static int Bridge_GetFrameCount(_cef_v8_stack_trace_t* self)
    {
        try
        {
            var _m = GetManaged<CefV8StackTrace>(self);

            var _result = _m.GetFrameCount();

            return _result;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    #else
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    #endif
    private static _cef_v8_stack_frame_t* Bridge_GetFrame(_cef_v8_stack_trace_t* self, int arg0)
    {
        try
        {
            var _m = GetManaged<CefV8StackTrace>(self);

            var _a0 = arg0;
            var _result = _m.GetFrame(_a0);

            if (_result is ICefBaseRefCounted _rc) _rc.AddRef();
            return _result != null ? _result.NativePtr : null;
        }
        catch (Exception ex)
        {
            Console.WriteLine("Managed exception in callback: " + ex.Message);
            throw;
        }
    }
}
#endif