// <auto-generated/>
#nullable enable

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using RawCef.Native;

namespace RawCef;

/// <summary>
/// Abstract base class for client-side implementations of <c>_cef_x509_certificate_t</c>.
/// Subclass this to implement a custom CefX509Certificate.
/// </summary>
public unsafe abstract partial class CefX509Certificate : CefBaseRefCounted, ICefX509Certificate
{
    private _cef_x509_certificate_t* _typedPtr;

    protected CefX509Certificate() : this((nuint)sizeof(_cef_x509_certificate_t))
    {
    }

    protected CefX509Certificate(nuint structSize) : base(structSize)
    {
        _typedPtr = (_cef_x509_certificate_t*)NativePtr;
        InitializeNativeStruct();
    }

    _cef_x509_certificate_t* ICefX509Certificate.NativePtr => _typedPtr;

    /// <inheritdoc />
    protected override void InitializeNativeStruct()
    {
        base.InitializeNativeStruct();

        _typedPtr->get_subject = &Bridge_GetSubject;
        _typedPtr->get_issuer = &Bridge_GetIssuer;
        _typedPtr->get_serial_number = &Bridge_GetSerialNumber;
        _typedPtr->get_valid_start = &Bridge_GetValidStart;
        _typedPtr->get_valid_expiry = &Bridge_GetValidExpiry;
        _typedPtr->get_derencoded = &Bridge_GetDerencoded;
        _typedPtr->get_pemencoded = &Bridge_GetPemencoded;
        _typedPtr->get_issuer_chain_size = &Bridge_GetIssuerChainSize;
        _typedPtr->get_derencoded_issuer_chain = &Bridge_GetDerencodedIssuerChain;
        _typedPtr->get_pemencoded_issuer_chain = &Bridge_GetPemencodedIssuerChain;
    }


    /// <summary>
    /// Implement the <c>get_subject</c> callback.
    /// </summary>
    public abstract ICefX509CertPrincipal? GetSubject();

    /// <summary>
    /// Implement the <c>get_issuer</c> callback.
    /// </summary>
    public abstract ICefX509CertPrincipal? GetIssuer();

    /// <summary>
    /// Implement the <c>get_serial_number</c> callback.
    /// </summary>
    public abstract ICefBinaryValue? GetSerialNumber();

    /// <summary>
    /// Implement the <c>get_valid_start</c> callback.
    /// </summary>
    public abstract _cef_basetime_t GetValidStart();

    /// <summary>
    /// Implement the <c>get_valid_expiry</c> callback.
    /// </summary>
    public abstract _cef_basetime_t GetValidExpiry();

    /// <summary>
    /// Implement the <c>get_derencoded</c> callback.
    /// </summary>
    public abstract ICefBinaryValue? GetDerencoded();

    /// <summary>
    /// Implement the <c>get_pemencoded</c> callback.
    /// </summary>
    public abstract ICefBinaryValue? GetPemencoded();

    /// <summary>
    /// Implement the <c>get_issuer_chain_size</c> callback.
    /// </summary>
    public abstract nuint GetIssuerChainSize();

    /// <summary>
    /// Implement the <c>get_derencoded_issuer_chain</c> callback.
    /// </summary>
    public abstract void GetDerencodedIssuerChain(nuint* arg0, _cef_binary_value_t** arg1);

    /// <summary>
    /// Implement the <c>get_pemencoded_issuer_chain</c> callback.
    /// </summary>
    public abstract void GetPemencodedIssuerChain(nuint* arg0, _cef_binary_value_t** arg1);

    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    private static _cef_x509_cert_principal_t* Bridge_GetSubject(_cef_x509_certificate_t* self)
    {
        var _m = GetManaged<CefX509Certificate>(self);

        var _result = _m.GetSubject();

        return _result?.NativePtr;
    }
    #endif

    #if OS_MAC || OS_LINUX
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    private static _cef_x509_cert_principal_t* Bridge_GetSubject(_cef_x509_certificate_t* self)
    {
        var _m = GetManaged<CefX509Certificate>(self);

        var _result = _m.GetSubject();

        return _result?.NativePtr;
    }
    #endif


    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    private static _cef_x509_cert_principal_t* Bridge_GetIssuer(_cef_x509_certificate_t* self)
    {
        var _m = GetManaged<CefX509Certificate>(self);

        var _result = _m.GetIssuer();

        return _result?.NativePtr;
    }
    #endif

    #if OS_MAC || OS_LINUX
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    private static _cef_x509_cert_principal_t* Bridge_GetIssuer(_cef_x509_certificate_t* self)
    {
        var _m = GetManaged<CefX509Certificate>(self);

        var _result = _m.GetIssuer();

        return _result?.NativePtr;
    }
    #endif


    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    private static _cef_binary_value_t* Bridge_GetSerialNumber(_cef_x509_certificate_t* self)
    {
        var _m = GetManaged<CefX509Certificate>(self);

        var _result = _m.GetSerialNumber();

        return _result?.NativePtr;
    }
    #endif

    #if OS_MAC || OS_LINUX
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    private static _cef_binary_value_t* Bridge_GetSerialNumber(_cef_x509_certificate_t* self)
    {
        var _m = GetManaged<CefX509Certificate>(self);

        var _result = _m.GetSerialNumber();

        return _result?.NativePtr;
    }
    #endif


    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    private static _cef_basetime_t Bridge_GetValidStart(_cef_x509_certificate_t* self)
    {
        var _m = GetManaged<CefX509Certificate>(self);

        var _result = _m.GetValidStart();

        return _result;
    }
    #endif

    #if OS_MAC || OS_LINUX
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    private static _cef_basetime_t Bridge_GetValidStart(_cef_x509_certificate_t* self)
    {
        var _m = GetManaged<CefX509Certificate>(self);

        var _result = _m.GetValidStart();

        return _result;
    }
    #endif


    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    private static _cef_basetime_t Bridge_GetValidExpiry(_cef_x509_certificate_t* self)
    {
        var _m = GetManaged<CefX509Certificate>(self);

        var _result = _m.GetValidExpiry();

        return _result;
    }
    #endif

    #if OS_MAC || OS_LINUX
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    private static _cef_basetime_t Bridge_GetValidExpiry(_cef_x509_certificate_t* self)
    {
        var _m = GetManaged<CefX509Certificate>(self);

        var _result = _m.GetValidExpiry();

        return _result;
    }
    #endif


    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    private static _cef_binary_value_t* Bridge_GetDerencoded(_cef_x509_certificate_t* self)
    {
        var _m = GetManaged<CefX509Certificate>(self);

        var _result = _m.GetDerencoded();

        return _result?.NativePtr;
    }
    #endif

    #if OS_MAC || OS_LINUX
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    private static _cef_binary_value_t* Bridge_GetDerencoded(_cef_x509_certificate_t* self)
    {
        var _m = GetManaged<CefX509Certificate>(self);

        var _result = _m.GetDerencoded();

        return _result?.NativePtr;
    }
    #endif


    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    private static _cef_binary_value_t* Bridge_GetPemencoded(_cef_x509_certificate_t* self)
    {
        var _m = GetManaged<CefX509Certificate>(self);

        var _result = _m.GetPemencoded();

        return _result?.NativePtr;
    }
    #endif

    #if OS_MAC || OS_LINUX
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    private static _cef_binary_value_t* Bridge_GetPemencoded(_cef_x509_certificate_t* self)
    {
        var _m = GetManaged<CefX509Certificate>(self);

        var _result = _m.GetPemencoded();

        return _result?.NativePtr;
    }
    #endif


    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    private static nuint Bridge_GetIssuerChainSize(_cef_x509_certificate_t* self)
    {
        var _m = GetManaged<CefX509Certificate>(self);

        var _result = _m.GetIssuerChainSize();

        return _result;
    }
    #endif

    #if OS_MAC || OS_LINUX
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    private static nuint Bridge_GetIssuerChainSize(_cef_x509_certificate_t* self)
    {
        var _m = GetManaged<CefX509Certificate>(self);

        var _result = _m.GetIssuerChainSize();

        return _result;
    }
    #endif


    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    private static void Bridge_GetDerencodedIssuerChain(_cef_x509_certificate_t* self, nuint* arg0, _cef_binary_value_t** arg1)
    {
        var _m = GetManaged<CefX509Certificate>(self);

        var _a0 = arg0;
        var _a1 = arg1;
        _m.GetDerencodedIssuerChain(_a0, _a1);
    }
    #endif

    #if OS_MAC || OS_LINUX
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    private static void Bridge_GetDerencodedIssuerChain(_cef_x509_certificate_t* self, nuint* arg0, _cef_binary_value_t** arg1)
    {
        var _m = GetManaged<CefX509Certificate>(self);

        var _a0 = arg0;
        var _a1 = arg1;
        _m.GetDerencodedIssuerChain(_a0, _a1);
    }
    #endif


    #if OS_WIN
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
    private static void Bridge_GetPemencodedIssuerChain(_cef_x509_certificate_t* self, nuint* arg0, _cef_binary_value_t** arg1)
    {
        var _m = GetManaged<CefX509Certificate>(self);

        var _a0 = arg0;
        var _a1 = arg1;
        _m.GetPemencodedIssuerChain(_a0, _a1);
    }
    #endif

    #if OS_MAC || OS_LINUX
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    private static void Bridge_GetPemencodedIssuerChain(_cef_x509_certificate_t* self, nuint* arg0, _cef_binary_value_t** arg1)
    {
        var _m = GetManaged<CefX509Certificate>(self);

        var _a0 = arg0;
        var _a1 = arg1;
        _m.GetPemencodedIssuerChain(_a0, _a1);
    }
    #endif

}
