#if OS_WIN
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_resource_request_handler_t</code> type.
/// </summary>
public unsafe partial interface ICefResourceRequestHandler : ICefBaseRefCounted
{
    new _cef_resource_request_handler_t* NativePtr { get; }

    public ICefCookieAccessFilter? GetCookieAccessFilter(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2);

    public cef_return_value_t OnBeforeResourceLoad(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefCallback? arg3);

    public ICefResourceHandler? GetResourceHandler(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2);

    public void OnResourceRedirect(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefResponse? arg3, out string? arg4);

    public int OnResourceResponse(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefResponse? arg3);

    public ICefResponseFilter? GetResourceResponseFilter(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefResponse? arg3);

    public void OnResourceLoadComplete(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefResponse? arg3, cef_urlrequest_status_t arg4, long arg5);

    public void OnProtocolExecution(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, int* arg3);
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_resource_request_handler_t</code> type.
/// </summary>
public unsafe partial interface ICefResourceRequestHandler : ICefBaseRefCounted
{
    new _cef_resource_request_handler_t* NativePtr { get; }

    public ICefCookieAccessFilter? GetCookieAccessFilter(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2);

    public cef_return_value_t OnBeforeResourceLoad(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefCallback? arg3);

    public ICefResourceHandler? GetResourceHandler(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2);

    public void OnResourceRedirect(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefResponse? arg3, out string? arg4);

    public int OnResourceResponse(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefResponse? arg3);

    public ICefResponseFilter? GetResourceResponseFilter(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefResponse? arg3);

    public void OnResourceLoadComplete(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefResponse? arg3, cef_urlrequest_status_t arg4, long arg5);

    public void OnProtocolExecution(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, int* arg3);
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_resource_request_handler_t</code> type.
/// </summary>
public unsafe partial interface ICefResourceRequestHandler : ICefBaseRefCounted
{
    new _cef_resource_request_handler_t* NativePtr { get; }

    public ICefCookieAccessFilter? GetCookieAccessFilter(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2);

    public cef_return_value_t OnBeforeResourceLoad(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefCallback? arg3);

    public ICefResourceHandler? GetResourceHandler(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2);

    public void OnResourceRedirect(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefResponse? arg3, out string? arg4);

    public int OnResourceResponse(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefResponse? arg3);

    public ICefResponseFilter? GetResourceResponseFilter(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefResponse? arg3);

    public void OnResourceLoadComplete(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, ICefResponse? arg3, cef_urlrequest_status_t arg4, long arg5);

    public void OnProtocolExecution(ICefBrowser? arg0, ICefFrame? arg1, ICefRequest? arg2, int* arg3);
}
#endif