#if OS_WIN
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_download_handler_t</code> type.
/// </summary>
public unsafe partial interface ICefDownloadHandler : ICefBaseRefCounted
{
    new _cef_download_handler_t* NativePtr { get; }

    public int CanDownload(ICefBrowser? arg0, string? arg1, string? arg2);

    public int OnBeforeDownload(ICefBrowser? arg0, ICefDownloadItem? arg1, string? arg2, ICefBeforeDownloadCallback? arg3);

    public void OnDownloadUpdated(ICefBrowser? arg0, ICefDownloadItem? arg1, ICefDownloadItemCallback? arg2);
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_download_handler_t</code> type.
/// </summary>
public unsafe partial interface ICefDownloadHandler : ICefBaseRefCounted
{
    new _cef_download_handler_t* NativePtr { get; }

    public int CanDownload(ICefBrowser? arg0, string? arg1, string? arg2);

    public int OnBeforeDownload(ICefBrowser? arg0, ICefDownloadItem? arg1, string? arg2, ICefBeforeDownloadCallback? arg3);

    public void OnDownloadUpdated(ICefBrowser? arg0, ICefDownloadItem? arg1, ICefDownloadItemCallback? arg2);
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_download_handler_t</code> type.
/// </summary>
public unsafe partial interface ICefDownloadHandler : ICefBaseRefCounted
{
    new _cef_download_handler_t* NativePtr { get; }

    public int CanDownload(ICefBrowser? arg0, string? arg1, string? arg2);

    public int OnBeforeDownload(ICefBrowser? arg0, ICefDownloadItem? arg1, string? arg2, ICefBeforeDownloadCallback? arg3);

    public void OnDownloadUpdated(ICefBrowser? arg0, ICefDownloadItem? arg1, ICefDownloadItemCallback? arg2);
}
#endif