#if OS_WIN
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_download_item_t</code> type.
/// </summary>
public unsafe partial interface ICefDownloadItem : ICefBaseRefCounted
{
    new _cef_download_item_t* NativePtr { get; }

    public int IsValid();

    public int IsInProgress();

    public int IsComplete();

    public int IsCanceled();

    public int IsInterrupted();

    public cef_download_interrupt_reason_t GetInterruptReason();

    public long GetCurrentSpeed();

    public int GetPercentComplete();

    public long GetTotalBytes();

    public long GetReceivedBytes();

    public DateTime GetStartTime();

    public DateTime GetEndTime();

    public string? GetFullPath();

    public uint GetId();

    public string? GetUrl();

    public string? GetOriginalUrl();

    public string? GetSuggestedFileName();

    public string? GetContentDisposition();

    public string? GetMimeType();

    public int IsPaused();
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_download_item_t</code> type.
/// </summary>
public unsafe partial interface ICefDownloadItem : ICefBaseRefCounted
{
    new _cef_download_item_t* NativePtr { get; }

    public int IsValid();

    public int IsInProgress();

    public int IsComplete();

    public int IsCanceled();

    public int IsInterrupted();

    public cef_download_interrupt_reason_t GetInterruptReason();

    public long GetCurrentSpeed();

    public int GetPercentComplete();

    public long GetTotalBytes();

    public long GetReceivedBytes();

    public DateTime GetStartTime();

    public DateTime GetEndTime();

    public string? GetFullPath();

    public uint GetId();

    public string? GetUrl();

    public string? GetOriginalUrl();

    public string? GetSuggestedFileName();

    public string? GetContentDisposition();

    public string? GetMimeType();

    public int IsPaused();
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_download_item_t</code> type.
/// </summary>
public unsafe partial interface ICefDownloadItem : ICefBaseRefCounted
{
    new _cef_download_item_t* NativePtr { get; }

    public int IsValid();

    public int IsInProgress();

    public int IsComplete();

    public int IsCanceled();

    public int IsInterrupted();

    public cef_download_interrupt_reason_t GetInterruptReason();

    public long GetCurrentSpeed();

    public int GetPercentComplete();

    public long GetTotalBytes();

    public long GetReceivedBytes();

    public DateTime GetStartTime();

    public DateTime GetEndTime();

    public string? GetFullPath();

    public uint GetId();

    public string? GetUrl();

    public string? GetOriginalUrl();

    public string? GetSuggestedFileName();

    public string? GetContentDisposition();

    public string? GetMimeType();

    public int IsPaused();
}
#endif