// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_linux_window_properties_t</code> type.
/// </summary>
public unsafe partial interface ICefLinuxWindowProperties
{
    _cef_linux_window_properties_t* NativePtr { get; }

    nuint Size { get; set; }

    string? WaylandAppId { get; set; }

    string? WmClassClass { get; set; }

    string? WmClassName { get; set; }

    string? WmRoleName { get; set; }
}
