// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_settings_t</code> type.
/// </summary>
public unsafe partial interface ICefSettings
{
    _cef_settings_t* NativePtr { get; }

    nuint Size { get; set; }

    int NoSandbox { get; set; }

    string? BrowserSubprocessPath { get; set; }

    string? FrameworkDirPath { get; set; }

    string? MainBundlePath { get; set; }

    int MultiThreadedMessageLoop { get; set; }

    int ExternalMessagePump { get; set; }

    int WindowlessRenderingEnabled { get; set; }

    int CommandLineArgsDisabled { get; set; }

    string? CachePath { get; set; }

    string? RootCachePath { get; set; }

    int PersistSessionCookies { get; set; }

    string? UserAgent { get; set; }

    string? UserAgentProduct { get; set; }

    string? Locale { get; set; }

    string? LogFile { get; set; }

    cef_log_severity_t LogSeverity { get; set; }

    cef_log_items_t LogItems { get; set; }

    string? JavascriptFlags { get; set; }

    string? ResourcesDirPath { get; set; }

    string? LocalesDirPath { get; set; }

    int RemoteDebuggingPort { get; set; }

    int UncaughtExceptionStackSize { get; set; }

    uint BackgroundColor { get; set; }

    string? AcceptLanguageList { get; set; }

    string? CookieableSchemesList { get; set; }

    int CookieableSchemesExcludeDefaults { get; set; }

    string? ChromePolicyId { get; set; }

    int ChromeAppIconId { get; set; }

    int DisableSignalHandlers { get; set; }

    int UseViewsDefaultPopup { get; set; }
}
