#if OS_WIN
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_context_menu_params_t</code> type.
/// </summary>
public unsafe partial interface ICefContextMenuParams : ICefBaseRefCounted
{
    new _cef_context_menu_params_t* NativePtr { get; }

    public int GetXcoord();

    public int GetYcoord();

    public cef_context_menu_type_flags_t GetTypeFlags();

    public cef_string_userfree_utf16_t GetLinkUrl();

    public cef_string_userfree_utf16_t GetUnfilteredLinkUrl();

    public cef_string_userfree_utf16_t GetSourceUrl();

    public int HasImageContents();

    public cef_string_userfree_utf16_t GetTitleText();

    public cef_string_userfree_utf16_t GetPageUrl();

    public cef_string_userfree_utf16_t GetFrameUrl();

    public cef_string_userfree_utf16_t GetFrameCharset();

    public cef_context_menu_media_type_t GetMediaType();

    public cef_context_menu_media_state_flags_t GetMediaStateFlags();

    public cef_string_userfree_utf16_t GetSelectionText();

    public cef_string_userfree_utf16_t GetMisspelledWord();

    public int GetDictionarySuggestions(ICefStringList? arg0);

    public int IsEditable();

    public int IsSpellCheckEnabled();

    public cef_context_menu_edit_state_flags_t GetEditStateFlags();

    public int IsCustomMenu();
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_context_menu_params_t</code> type.
/// </summary>
public unsafe partial interface ICefContextMenuParams : ICefBaseRefCounted
{
    new _cef_context_menu_params_t* NativePtr { get; }

    public int GetXcoord();

    public int GetYcoord();

    public cef_context_menu_type_flags_t GetTypeFlags();

    public cef_string_userfree_utf16_t GetLinkUrl();

    public cef_string_userfree_utf16_t GetUnfilteredLinkUrl();

    public cef_string_userfree_utf16_t GetSourceUrl();

    public int HasImageContents();

    public cef_string_userfree_utf16_t GetTitleText();

    public cef_string_userfree_utf16_t GetPageUrl();

    public cef_string_userfree_utf16_t GetFrameUrl();

    public cef_string_userfree_utf16_t GetFrameCharset();

    public cef_context_menu_media_type_t GetMediaType();

    public cef_context_menu_media_state_flags_t GetMediaStateFlags();

    public cef_string_userfree_utf16_t GetSelectionText();

    public cef_string_userfree_utf16_t GetMisspelledWord();

    public int GetDictionarySuggestions(ICefStringList? arg0);

    public int IsEditable();

    public int IsSpellCheckEnabled();

    public cef_context_menu_edit_state_flags_t GetEditStateFlags();

    public int IsCustomMenu();
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_context_menu_params_t</code> type.
/// </summary>
public unsafe partial interface ICefContextMenuParams : ICefBaseRefCounted
{
    new _cef_context_menu_params_t* NativePtr { get; }

    public int GetXcoord();

    public int GetYcoord();

    public cef_context_menu_type_flags_t GetTypeFlags();

    public cef_string_userfree_utf16_t GetLinkUrl();

    public cef_string_userfree_utf16_t GetUnfilteredLinkUrl();

    public cef_string_userfree_utf16_t GetSourceUrl();

    public int HasImageContents();

    public cef_string_userfree_utf16_t GetTitleText();

    public cef_string_userfree_utf16_t GetPageUrl();

    public cef_string_userfree_utf16_t GetFrameUrl();

    public cef_string_userfree_utf16_t GetFrameCharset();

    public cef_context_menu_media_type_t GetMediaType();

    public cef_context_menu_media_state_flags_t GetMediaStateFlags();

    public cef_string_userfree_utf16_t GetSelectionText();

    public cef_string_userfree_utf16_t GetMisspelledWord();

    public int GetDictionarySuggestions(ICefStringList? arg0);

    public int IsEditable();

    public int IsSpellCheckEnabled();

    public cef_context_menu_edit_state_flags_t GetEditStateFlags();

    public int IsCustomMenu();
}
#endif