#if OS_WIN
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_stream_reader_t</code> type.
/// </summary>
public unsafe partial interface ICefStreamReader : ICefBaseRefCounted
{
    new _cef_stream_reader_t* NativePtr { get; }

    public nuint Read(void* arg0, nuint arg1, nuint arg2);

    public int Seek(long arg0, int arg1);

    public long Tell();

    public int Eof();

    public int MayBlock();
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_stream_reader_t</code> type.
/// </summary>
public unsafe partial interface ICefStreamReader : ICefBaseRefCounted
{
    new _cef_stream_reader_t* NativePtr { get; }

    public nuint Read(void* arg0, nuint arg1, nuint arg2);

    public int Seek(long arg0, int arg1);

    public long Tell();

    public int Eof();

    public int MayBlock();
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_stream_reader_t</code> type.
/// </summary>
public unsafe partial interface ICefStreamReader : ICefBaseRefCounted
{
    new _cef_stream_reader_t* NativePtr { get; }

    public nuint Read(void* arg0, nuint arg1, nuint arg2);

    public int Seek(long arg0, int arg1);

    public long Tell();

    public int Eof();

    public int MayBlock();
}
#endif