#if OS_WIN
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_preference_observer_t</code> type.
/// </summary>
public unsafe partial interface ICefPreferenceObserver : ICefBaseRefCounted
{
    new _cef_preference_observer_t* NativePtr { get; }

    public void OnPreferenceChanged(string? arg0);
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_preference_observer_t</code> type.
/// </summary>
public unsafe partial interface ICefPreferenceObserver : ICefBaseRefCounted
{
    new _cef_preference_observer_t* NativePtr { get; }

    public void OnPreferenceChanged(string? arg0);
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_preference_observer_t</code> type.
/// </summary>
public unsafe partial interface ICefPreferenceObserver : ICefBaseRefCounted
{
    new _cef_preference_observer_t* NativePtr { get; }

    public void OnPreferenceChanged(string? arg0);
}
#endif