// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_rect_t</code> type.
/// </summary>
public unsafe partial interface ICefRect
{
    _cef_rect_t* NativePtr { get; }

    int X { get; set; }

    int Y { get; set; }

    int Width { get; set; }

    int Height { get; set; }
}
