#if OS_WIN
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_menu_model_t</code> type.
/// </summary>
public unsafe partial interface ICefMenuModel : ICefBaseRefCounted
{
    new _cef_menu_model_t* NativePtr { get; }

    public int IsSubMenu();

    public int Clear();

    public nuint GetCount();

    public int AddSeparator();

    public int AddItem(int arg0, string? arg1);

    public int AddCheckItem(int arg0, string? arg1);

    public int AddRadioItem(int arg0, string? arg1, int arg2);

    public ICefMenuModel? AddSubMenu(int arg0, string? arg1);

    public int InsertSeparatorAt(nuint arg0);

    public int InsertItemAt(nuint arg0, int arg1, string? arg2);

    public int InsertCheckItemAt(nuint arg0, int arg1, string? arg2);

    public int InsertRadioItemAt(nuint arg0, int arg1, string? arg2, int arg3);

    public ICefMenuModel? InsertSubMenuAt(nuint arg0, int arg1, string? arg2);

    public int Remove(int arg0);

    public int RemoveAt(nuint arg0);

    public int GetIndexOf(int arg0);

    public int GetCommandIdAt(nuint arg0);

    public int SetCommandIdAt(nuint arg0, int arg1);

    public cef_string_userfree_utf16_t GetLabel(int arg0);

    public cef_string_userfree_utf16_t GetLabelAt(nuint arg0);

    public int SetLabel(int arg0, string? arg1);

    public int SetLabelAt(nuint arg0, string? arg1);

    public cef_menu_item_type_t GetType(int arg0);

    public cef_menu_item_type_t GetTypeAt(nuint arg0);

    public int GetGroupId(int arg0);

    public int GetGroupIdAt(nuint arg0);

    public int SetGroupId(int arg0, int arg1);

    public int SetGroupIdAt(nuint arg0, int arg1);

    public ICefMenuModel? GetSubMenu(int arg0);

    public ICefMenuModel? GetSubMenuAt(nuint arg0);

    public int IsVisible(int arg0);

    public int IsVisibleAt(nuint arg0);

    public int SetVisible(int arg0, int arg1);

    public int SetVisibleAt(nuint arg0, int arg1);

    public int IsEnabled(int arg0);

    public int IsEnabledAt(nuint arg0);

    public int SetEnabled(int arg0, int arg1);

    public int SetEnabledAt(nuint arg0, int arg1);

    public int IsChecked(int arg0);

    public int IsCheckedAt(nuint arg0);

    public int SetChecked(int arg0, int arg1);

    public int SetCheckedAt(nuint arg0, int arg1);

    public int HasAccelerator(int arg0);

    public int HasAcceleratorAt(nuint arg0);

    public int SetAccelerator(int arg0, int arg1, int arg2, int arg3, int arg4);

    public int SetAcceleratorAt(nuint arg0, int arg1, int arg2, int arg3, int arg4);

    public int RemoveAccelerator(int arg0);

    public int RemoveAcceleratorAt(nuint arg0);

    public int GetAccelerator(int arg0, int* arg1, int* arg2, int* arg3, int* arg4);

    public int GetAcceleratorAt(nuint arg0, int* arg1, int* arg2, int* arg3, int* arg4);

    public int SetColor(int arg0, cef_menu_color_type_t arg1, uint arg2);

    public int SetColorAt(int arg0, cef_menu_color_type_t arg1, uint arg2);

    public int GetColor(int arg0, cef_menu_color_type_t arg1, uint* arg2);

    public int GetColorAt(int arg0, cef_menu_color_type_t arg1, uint* arg2);

    public int SetFontList(int arg0, string? arg1);

    public int SetFontListAt(int arg0, string? arg1);
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_menu_model_t</code> type.
/// </summary>
public unsafe partial interface ICefMenuModel : ICefBaseRefCounted
{
    new _cef_menu_model_t* NativePtr { get; }

    public int IsSubMenu();

    public int Clear();

    public nuint GetCount();

    public int AddSeparator();

    public int AddItem(int arg0, string? arg1);

    public int AddCheckItem(int arg0, string? arg1);

    public int AddRadioItem(int arg0, string? arg1, int arg2);

    public ICefMenuModel? AddSubMenu(int arg0, string? arg1);

    public int InsertSeparatorAt(nuint arg0);

    public int InsertItemAt(nuint arg0, int arg1, string? arg2);

    public int InsertCheckItemAt(nuint arg0, int arg1, string? arg2);

    public int InsertRadioItemAt(nuint arg0, int arg1, string? arg2, int arg3);

    public ICefMenuModel? InsertSubMenuAt(nuint arg0, int arg1, string? arg2);

    public int Remove(int arg0);

    public int RemoveAt(nuint arg0);

    public int GetIndexOf(int arg0);

    public int GetCommandIdAt(nuint arg0);

    public int SetCommandIdAt(nuint arg0, int arg1);

    public cef_string_userfree_utf16_t GetLabel(int arg0);

    public cef_string_userfree_utf16_t GetLabelAt(nuint arg0);

    public int SetLabel(int arg0, string? arg1);

    public int SetLabelAt(nuint arg0, string? arg1);

    public cef_menu_item_type_t GetType(int arg0);

    public cef_menu_item_type_t GetTypeAt(nuint arg0);

    public int GetGroupId(int arg0);

    public int GetGroupIdAt(nuint arg0);

    public int SetGroupId(int arg0, int arg1);

    public int SetGroupIdAt(nuint arg0, int arg1);

    public ICefMenuModel? GetSubMenu(int arg0);

    public ICefMenuModel? GetSubMenuAt(nuint arg0);

    public int IsVisible(int arg0);

    public int IsVisibleAt(nuint arg0);

    public int SetVisible(int arg0, int arg1);

    public int SetVisibleAt(nuint arg0, int arg1);

    public int IsEnabled(int arg0);

    public int IsEnabledAt(nuint arg0);

    public int SetEnabled(int arg0, int arg1);

    public int SetEnabledAt(nuint arg0, int arg1);

    public int IsChecked(int arg0);

    public int IsCheckedAt(nuint arg0);

    public int SetChecked(int arg0, int arg1);

    public int SetCheckedAt(nuint arg0, int arg1);

    public int HasAccelerator(int arg0);

    public int HasAcceleratorAt(nuint arg0);

    public int SetAccelerator(int arg0, int arg1, int arg2, int arg3, int arg4);

    public int SetAcceleratorAt(nuint arg0, int arg1, int arg2, int arg3, int arg4);

    public int RemoveAccelerator(int arg0);

    public int RemoveAcceleratorAt(nuint arg0);

    public int GetAccelerator(int arg0, int* arg1, int* arg2, int* arg3, int* arg4);

    public int GetAcceleratorAt(nuint arg0, int* arg1, int* arg2, int* arg3, int* arg4);

    public int SetColor(int arg0, cef_menu_color_type_t arg1, uint arg2);

    public int SetColorAt(int arg0, cef_menu_color_type_t arg1, uint arg2);

    public int GetColor(int arg0, cef_menu_color_type_t arg1, uint* arg2);

    public int GetColorAt(int arg0, cef_menu_color_type_t arg1, uint* arg2);

    public int SetFontList(int arg0, string? arg1);

    public int SetFontListAt(int arg0, string? arg1);
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_menu_model_t</code> type.
/// </summary>
public unsafe partial interface ICefMenuModel : ICefBaseRefCounted
{
    new _cef_menu_model_t* NativePtr { get; }

    public int IsSubMenu();

    public int Clear();

    public nuint GetCount();

    public int AddSeparator();

    public int AddItem(int arg0, string? arg1);

    public int AddCheckItem(int arg0, string? arg1);

    public int AddRadioItem(int arg0, string? arg1, int arg2);

    public ICefMenuModel? AddSubMenu(int arg0, string? arg1);

    public int InsertSeparatorAt(nuint arg0);

    public int InsertItemAt(nuint arg0, int arg1, string? arg2);

    public int InsertCheckItemAt(nuint arg0, int arg1, string? arg2);

    public int InsertRadioItemAt(nuint arg0, int arg1, string? arg2, int arg3);

    public ICefMenuModel? InsertSubMenuAt(nuint arg0, int arg1, string? arg2);

    public int Remove(int arg0);

    public int RemoveAt(nuint arg0);

    public int GetIndexOf(int arg0);

    public int GetCommandIdAt(nuint arg0);

    public int SetCommandIdAt(nuint arg0, int arg1);

    public cef_string_userfree_utf16_t GetLabel(int arg0);

    public cef_string_userfree_utf16_t GetLabelAt(nuint arg0);

    public int SetLabel(int arg0, string? arg1);

    public int SetLabelAt(nuint arg0, string? arg1);

    public cef_menu_item_type_t GetType(int arg0);

    public cef_menu_item_type_t GetTypeAt(nuint arg0);

    public int GetGroupId(int arg0);

    public int GetGroupIdAt(nuint arg0);

    public int SetGroupId(int arg0, int arg1);

    public int SetGroupIdAt(nuint arg0, int arg1);

    public ICefMenuModel? GetSubMenu(int arg0);

    public ICefMenuModel? GetSubMenuAt(nuint arg0);

    public int IsVisible(int arg0);

    public int IsVisibleAt(nuint arg0);

    public int SetVisible(int arg0, int arg1);

    public int SetVisibleAt(nuint arg0, int arg1);

    public int IsEnabled(int arg0);

    public int IsEnabledAt(nuint arg0);

    public int SetEnabled(int arg0, int arg1);

    public int SetEnabledAt(nuint arg0, int arg1);

    public int IsChecked(int arg0);

    public int IsCheckedAt(nuint arg0);

    public int SetChecked(int arg0, int arg1);

    public int SetCheckedAt(nuint arg0, int arg1);

    public int HasAccelerator(int arg0);

    public int HasAcceleratorAt(nuint arg0);

    public int SetAccelerator(int arg0, int arg1, int arg2, int arg3, int arg4);

    public int SetAcceleratorAt(nuint arg0, int arg1, int arg2, int arg3, int arg4);

    public int RemoveAccelerator(int arg0);

    public int RemoveAcceleratorAt(nuint arg0);

    public int GetAccelerator(int arg0, int* arg1, int* arg2, int* arg3, int* arg4);

    public int GetAcceleratorAt(nuint arg0, int* arg1, int* arg2, int* arg3, int* arg4);

    public int SetColor(int arg0, cef_menu_color_type_t arg1, uint arg2);

    public int SetColorAt(int arg0, cef_menu_color_type_t arg1, uint arg2);

    public int GetColor(int arg0, cef_menu_color_type_t arg1, uint* arg2);

    public int GetColorAt(int arg0, cef_menu_color_type_t arg1, uint* arg2);

    public int SetFontList(int arg0, string? arg1);

    public int SetFontListAt(int arg0, string? arg1);
}
#endif