// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_request_context_settings_t</code> type.
/// </summary>
public unsafe partial interface ICefRequestContextSettings
{
    _cef_request_context_settings_t* NativePtr { get; }

    nuint Size { get; set; }

    string? CachePath { get; set; }

    int PersistSessionCookies { get; set; }

    string? AcceptLanguageList { get; set; }

    string? CookieableSchemesList { get; set; }

    int CookieableSchemesExcludeDefaults { get; set; }
}
