// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_size_t</code> type.
/// </summary>
public unsafe partial interface ICefSize
{
    _cef_size_t* NativePtr { get; }

    int Width { get; set; }

    int Height { get; set; }
}
