#if OS_WIN
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_frame_handler_t</code> type.
/// </summary>
public unsafe partial interface ICefFrameHandler : ICefBaseRefCounted
{
    new _cef_frame_handler_t* NativePtr { get; }

    public void OnFrameCreated(ICefBrowser? arg0, ICefFrame? arg1);

    public void OnFrameDestroyed(ICefBrowser? arg0, ICefFrame? arg1);

    public void OnFrameAttached(ICefBrowser? arg0, ICefFrame? arg1, int arg2);

    public void OnFrameDetached(ICefBrowser? arg0, ICefFrame? arg1);

    public void OnMainFrameChanged(ICefBrowser? arg0, ICefFrame? arg1, ICefFrame? arg2);
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_frame_handler_t</code> type.
/// </summary>
public unsafe partial interface ICefFrameHandler : ICefBaseRefCounted
{
    new _cef_frame_handler_t* NativePtr { get; }

    public void OnFrameCreated(ICefBrowser? arg0, ICefFrame? arg1);

    public void OnFrameDestroyed(ICefBrowser? arg0, ICefFrame? arg1);

    public void OnFrameAttached(ICefBrowser? arg0, ICefFrame? arg1, int arg2);

    public void OnFrameDetached(ICefBrowser? arg0, ICefFrame? arg1);

    public void OnMainFrameChanged(ICefBrowser? arg0, ICefFrame? arg1, ICefFrame? arg2);
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_frame_handler_t</code> type.
/// </summary>
public unsafe partial interface ICefFrameHandler : ICefBaseRefCounted
{
    new _cef_frame_handler_t* NativePtr { get; }

    public void OnFrameCreated(ICefBrowser? arg0, ICefFrame? arg1);

    public void OnFrameDestroyed(ICefBrowser? arg0, ICefFrame? arg1);

    public void OnFrameAttached(ICefBrowser? arg0, ICefFrame? arg1, int arg2);

    public void OnFrameDetached(ICefBrowser? arg0, ICefFrame? arg1);

    public void OnMainFrameChanged(ICefBrowser? arg0, ICefFrame? arg1, ICefFrame? arg2);
}
#endif