#if OS_WIN
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_cookie_visitor_t</code> type.
/// </summary>
public unsafe partial interface ICefCookieVisitor : ICefBaseRefCounted
{
    new _cef_cookie_visitor_t* NativePtr { get; }

    public int Visit(ICefCookie? arg0, int arg1, int arg2, int* arg3);
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_cookie_visitor_t</code> type.
/// </summary>
public unsafe partial interface ICefCookieVisitor : ICefBaseRefCounted
{
    new _cef_cookie_visitor_t* NativePtr { get; }

    public int Visit(ICefCookie? arg0, int arg1, int arg2, int* arg3);
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_cookie_visitor_t</code> type.
/// </summary>
public unsafe partial interface ICefCookieVisitor : ICefBaseRefCounted
{
    new _cef_cookie_visitor_t* NativePtr { get; }

    public int Visit(ICefCookie? arg0, int arg1, int arg2, int* arg3);
}
#endif