#if OS_WIN
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_scheme_registrar_t</code> type.
/// </summary>
public unsafe partial interface ICefSchemeRegistrar : ICefBaseScoped
{
    new _cef_scheme_registrar_t* NativePtr { get; }

    public int AddCustomScheme(string? arg0, int arg1);
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_scheme_registrar_t</code> type.
/// </summary>
public unsafe partial interface ICefSchemeRegistrar : ICefBaseScoped
{
    new _cef_scheme_registrar_t* NativePtr { get; }

    public int AddCustomScheme(string? arg0, int arg1);
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_scheme_registrar_t</code> type.
/// </summary>
public unsafe partial interface ICefSchemeRegistrar : ICefBaseScoped
{
    new _cef_scheme_registrar_t* NativePtr { get; }

    public int AddCustomScheme(string? arg0, int arg1);
}
#endif