#if OS_WIN
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_resource_bundle_handler_t</code> type.
/// </summary>
public unsafe partial interface ICefResourceBundleHandler : ICefBaseRefCounted
{
    new _cef_resource_bundle_handler_t* NativePtr { get; }

    public int GetLocalizedString(int arg0, out string? arg1);

    public int GetDataResource(int arg0, void** arg1, nuint* arg2);

    public int GetDataResourceForScale(int arg0, cef_scale_factor_t arg1, void** arg2, nuint* arg3);
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_resource_bundle_handler_t</code> type.
/// </summary>
public unsafe partial interface ICefResourceBundleHandler : ICefBaseRefCounted
{
    new _cef_resource_bundle_handler_t* NativePtr { get; }

    public int GetLocalizedString(int arg0, string? arg1);

    public int GetDataResource(int arg0, void** arg1, nuint* arg2);

    public int GetDataResourceForScale(int arg0, cef_scale_factor_t arg1, void** arg2, nuint* arg3);
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_resource_bundle_handler_t</code> type.
/// </summary>
public unsafe partial interface ICefResourceBundleHandler : ICefBaseRefCounted
{
    new _cef_resource_bundle_handler_t* NativePtr { get; }

    public int GetLocalizedString(int arg0, string? arg1);

    public int GetDataResource(int arg0, void** arg1, nuint* arg2);

    public int GetDataResourceForScale(int arg0, cef_scale_factor_t arg1, void** arg2, nuint* arg3);
}
#endif