// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_life_span_handler_t</code> type.
/// </summary>
public unsafe partial interface ICefLifeSpanHandler : ICefBaseRefCounted
{
    new _cef_life_span_handler_t* NativePtr { get; }

    public int OnBeforePopup(ICefBrowser? arg0, ICefFrame? arg1, int arg2, string? arg3, string? arg4, cef_window_open_disposition_t arg5, int arg6, ICefPopupFeatures? arg7, ICefWindowInfo? arg8, _cef_client_t** arg9, ICefBrowserSettings? arg10, _cef_dictionary_value_t** arg11, int* arg12);

    public void OnBeforePopupAborted(ICefBrowser? arg0, int arg1);

    public void OnBeforeDevToolsPopup(ICefBrowser? arg0, ICefWindowInfo? arg1, _cef_client_t** arg2, ICefBrowserSettings? arg3, _cef_dictionary_value_t** arg4, int* arg5);

    public void OnAfterCreated(ICefBrowser? arg0);

    public int DoClose(ICefBrowser? arg0);

    public void OnBeforeClose(ICefBrowser? arg0);
}
