// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_v8_stack_frame_t</code> type.
/// </summary>
public unsafe partial interface ICefV8StackFrame : ICefBaseRefCounted
{
    new _cef_v8_stack_frame_t* NativePtr { get; }

    public int IsValid();

    public cef_string_userfree_utf16_t GetScriptName();

    public cef_string_userfree_utf16_t GetScriptNameOrSourceUrl();

    public cef_string_userfree_utf16_t GetFunctionName();

    public int GetLineNumber();

    public int GetColumn();

    public int IsEval();

    public int IsConstructor();
}
