#if OS_WIN
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_post_data_t</code> type.
/// </summary>
public unsafe partial interface ICefPostData : ICefBaseRefCounted
{
    new _cef_post_data_t* NativePtr { get; }

    public int IsReadOnly();

    public int HasExcludedElements();

    public nuint GetElementCount();

    public void GetElements(nuint* arg0, out ICefPostDataElement? arg1);

    public int RemoveElement(ICefPostDataElement? arg0);

    public int AddElement(ICefPostDataElement? arg0);

    public void RemoveElements();
}
#endif
#if OS_MAC
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_post_data_t</code> type.
/// </summary>
public unsafe partial interface ICefPostData : ICefBaseRefCounted
{
    new _cef_post_data_t* NativePtr { get; }

    public int IsReadOnly();

    public int HasExcludedElements();

    public nuint GetElementCount();

    public void GetElements(nuint* arg0, ICefPostDataElement? arg1);

    public int RemoveElement(ICefPostDataElement? arg0);

    public int AddElement(ICefPostDataElement? arg0);

    public void RemoveElements();
}
#endif
#if OS_LINUX
// <auto-generated/>
#nullable enable

using RawCef.Native;

namespace RawCef;

/// <summary>
/// Represents an instance of the <code>_cef_post_data_t</code> type.
/// </summary>
public unsafe partial interface ICefPostData : ICefBaseRefCounted
{
    new _cef_post_data_t* NativePtr { get; }

    public int IsReadOnly();

    public int HasExcludedElements();

    public nuint GetElementCount();

    public void GetElements(nuint* arg0, ICefPostDataElement? arg1);

    public int RemoveElement(ICefPostDataElement? arg0);

    public int AddElement(ICefPostDataElement? arg0);

    public void RemoveElements();
}
#endif