// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the cef_content_setting_values_t enum.
/// </summary>
public enum CefContentSettingValues : int
{
    Default,
    Allow,
    Block,
    Ask,
    SessionOnly,
    DetectImportantContentDeprecated,
    NumValues,
}
