// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the cef_cookie_same_site_t enum.
/// </summary>
public enum CefCookieSameSite : int
{
    Unspecified,
    NoRestriction,
    LaxMode,
    StrictMode,
    NumValues,
}
