// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the cef_docking_mode_t enum.
/// </summary>
public enum CefDockingMode : int
{
    CEF_DOCKING_MODE_TOP_LEFT,
    CEF_DOCKING_MODE_TOP_RIGHT,
    CEF_DOCKING_MODE_BOTTOM_LEFT,
    CEF_DOCKING_MODE_BOTTOM_RIGHT,
    CEF_DOCKING_MODE_CUSTOM,
    CEF_DOCKING_MODE_NUM_VALUES,
}
