// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the cef_media_route_connection_state_t enum.
/// </summary>
public enum CefMediaRouteConnectionState : int
{
    CEF_MRCS_UNKNOWN = -1,
    CEF_MRCS_CONNECTING,
    CEF_MRCS_CONNECTED,
    CEF_MRCS_CLOSED,
    CEF_MRCS_TERMINATED,
    CEF_MRCS_NUM_VALUES,
}
