// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the cef_message_loop_type_t enum.
/// </summary>
public enum CefMessageLoopType : int
{
    ML_TYPE_DEFAULT,
    ML_TYPE_UI,
    ML_TYPE_IO,
    ML_NUM_VALUES,
}
