// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the cef_quick_menu_edit_state_flags_t enum.
/// </summary>
public enum CefQuickMenuEditStateFlags : int
{
    None = 0,
    CanEllipsis = 1 << 0,
    CanCut = 1 << 1,
    CanCopy = 1 << 2,
    CanPaste = 1 << 3,
}
