// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the cef_thread_id_t enum.
/// </summary>
public enum CefThreadId : int
{
    TID_UI,
    TID_FILE_BACKGROUND,
    TID_FILE_USER_VISIBLE,
    TID_FILE_USER_BLOCKING,
    TID_PROCESS_LAUNCHER,
    TID_IO,
    TID_RENDERER,
    TID_NUM_VALUES,
}
