// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the cef_transition_type_t enum.
/// </summary>
public enum CefTransitionType : int
{
    Link,
    Explicit,
    AutoBookmark,
    AutoSubframe,
    ManualSubframe,
    Generated,
    AutoToplevel,
    FormSubmit,
    Reload,
    Keyword,
    KeywordGenerated,
    NumValues,
    SourceMask = 0xFF,
    BlockedFlag = 0x00800000,
    ForwardBackFlag = 0x01000000,
    DirectLoadFlag = 0x02000000,
    HomePageFlag = 0x04000000,
    FromApiFlag = 0x08000000,
    ChainStartFlag = 0x10000000,
    ChainEndFlag = 0x20000000,
    ClientRedirectFlag = 0x40000000,
    ServerRedirectFlag = unchecked((int)(0x80000000)),
    IsRedirectMask = unchecked((int)(0xC0000000)),
    QualifierMask = unchecked((int)(0xFFFFFF00)),
}
