// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the cef_xml_encoding_type_t enum.
/// </summary>
public enum CefXmlEncodingType : int
{
    XML_ENCODING_NONE,
    XML_ENCODING_UTF8,
    XML_ENCODING_UTF16LE,
    XML_ENCODING_UTF16BE,
    XML_ENCODING_ASCII,
    XML_ENCODING_NUM_VALUES,
}
