// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the cef_xml_encoding_type_t enum.
/// </summary>
public enum CefXmlEncodingType : int
{
    None,
    Utf8,
    Utf16le,
    Utf16be,
    Ascii,
    NumValues,
}
