// <auto-generated/>
#nullable enable

namespace RawCef.Native;

/// <summary>
/// Managed binding for the cef_zoom_command_t enum.
/// </summary>
public enum CefZoomCommand : int
{
    Out,
    Reset,
    In,
}
