<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <DefineConstants>$(DefineConstants);OS_WIN</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\RawCef.Binaries.Win64\RawCef.Binaries.Win64.csproj" />
        <ProjectReference Include="..\RawCef\RawCef.Windows.csproj" />
    </ItemGroup>

</Project>
